### ISSUE TITLE
CC onboarding for Eden Huthmacher

### ISSUE THREAD

**Issue by e0d** [openedx/axim-engineering#1000]
Nomination thread:

https://discuss.openedx.org/t/core-contributor-nomination-eden-huthmacher/11825/19

### Non-Coding CC Onboarding Checklist for Axim On-Call
- [x] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [x] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Set up access for CC in privacy & a11y courses (can skip for now, but let CC know that they may be upcoming)
- [x] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while).  Keep the ticket open with status “Blocked”, until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [x] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [x] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [x] Look up their record in Salesforce and grant them the Core Contributor role.
- [x] Send Dean a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)
- [x] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin

**Comment by e0d** [comment]
@ehuthmacher can you confirm you have received the invite to the CC onboarding course?

**Comment by ehuthmacher** [comment]
@e0d Not yet

**Comment by sarina** [comment]
@ehuthmacher could you please check your spam folder before I try resending? We've been having a bit of trouble with our invites being caught as spam.

Also please note you do not need to fill out the individual CLA or Core Contributor agreement while employed at Axim!

**Comment by ehuthmacher** [comment]
@sarina It was in my spam folder. I received it and completed the training.

**Comment by sarina** [comment]
Thanks @ehuthmacher - I'll complete the rest of the steps. Could you forward the invite that was in your spam to me and Feanil, so we can investigate why that continues to happen?

**Comment by ehuthmacher** [comment]
Sure, just sent it.
