### ISSUE TITLE
[GH Request] Offboard ytu

### ISSUE THREAD

**Issue by AmiraQuick** [openedx/axim-engineering#1003]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Yuchen Tu, @ytu

### End Date

18 December 2023

### Urgency

Low (2 weeks)

**Comment by sarina** [comment]
@AmiraQuick I couldn't find this user in our GitHub organization. Could you please check the username and advise?

**Comment by AmiraQuick** [comment]
@sarina Hi! Yes I have checked and confirmed based off of what I was provided and the username I was given was ytu. If you cannot locate this user, it is possible the user's account was never set up. Thank you for checking though!

**Comment by sarina** [comment]
Thanks!
