### ISSUE TITLE
[GH Request] Offboard zzzarius

### ISSUE THREAD

**Issue by AmiraQuick** [openedx/axim-engineering#1005]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Darius Zivertas, @ zzzarius

### End Date

18 December 2023

### Urgency

Low (2 weeks)

**Comment by sarina** [comment]
@AmiraQuick I have this user as belonging to a different company. Can you please advise as to whether or not they were actually employed by 2U?

**Comment by AmiraQuick** [comment]
@sarina That makes sense given the user was listed as a contractor. I am unable to see for which company however if need be I can find out to confirm!

**Comment by sarina** [comment]
That works, thank you!
