### ISSUE TITLE
[GH Request] Offboard andrewgwardwell

### ISSUE THREAD

**Issue by AmiraQuick** [openedx/axim-engineering#1006]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Andrew Wardwell, @ andrewgwardwell

### End Date

18 December 2023

### Urgency

Low (2 weeks)

**Comment by sarina** [comment]
@AmiraQuick I couldn't find this user in our GitHub organization. Could you please check the username and advise?

**Comment by AmiraQuick** [comment]
Hi! Yes I have checked and confirmed the username is andrewgwardwell. That is what I was provided however if you are unable to locate this user, it is possible their account was never set up. Thank you for checking!

**Comment by sarina** [comment]
Thanks!
