### ISSUE TITLE
[GH Request] Core Contributors Coordination Project Access Rights

### ISSUE THREAD

**Issue by antoviaque** [openedx/axim-engineering#1009]
### Firm Name

OpenCraft

### Urgency

Medium (< 2 weeks)

### Requested Change

I have created a project to coordinate issues brought up in retrospectives from core contributors and agenda items for the contributors meetup at https://github.com/orgs/openedx/projects/62 - I now need to make it public and share its admin with the rest of the core contributors. I was only able to invite the core contributor _committers_ as admin. Could we:
- create a group that includes all the core contributors, regardless of whether they can commit somewhere, to allow to give them admin rights on that project
- Allow all members of that group to add & edit tickets on the wg-coordination project
- Make the project public, to allow all contributors (core or not) to access it 

### Reasoning

The reasoning is to keep friction low to  for the group that´s trusted by the  project, and for contributors in general

**Comment by feanil** [comment]
Hi @antoviaque, by default everyone in the org already has write access to the project. I've made it default public so that it is visible to everyone even if they are not in the organization.  Also, everyone in the org should have triage access to `wg-coordination` and so should be able to already edit tickets.

Is there a specific thing you need them to do that requires admin access?

**Comment by antoviaque** [comment]
@feanil OK great, thank you!

For things core should be able to do - the important bit would be to be able to add tickets to the project, change their status and priority - is that already the case from having triage rights? Admin rights in general would be more of a nice to have, to make sure nobody in the group ever has friction when they want to do something with the board.

**Comment by feanil** [comment]
Correct, with triage access to the repo and write access to the board, members should be able to add tickets to the project, and modify ticket and project fields.  I think let's stick with that for now and if we see issues that merit admin access, we can add it in the future.

**Comment by antoviaque** [comment]
@feanil Sounds good then, let's do that :+1: - thanks!
