### ISSUE TITLE
[GH Request] Offboard Ali Adnan

### ISSUE THREAD

**Issue by Ali-D-Akbar** [openedx/axim-engineering#1010]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Hi there,

Can you please remove Ali Adnan from
https://github.com/orgs/openedx/teams/2u-phoenix? He has left team Phoenix
and we don't want him to be added in PRs as reviewers.

### End Date

2 Jan 2023

### Urgency

Low (2 weeks)

**Comment by feanil** [comment]
This is done.
