### ISSUE TITLE
[GH Request] Allow edx-transifex-bot to merge to frontend-component-ai-translations

### ISSUE THREAD

**Issue by hajorg** [openedx/axim-engineering#1012]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

We would like the edx-transifex-bot to be able to create/merge its own PRs into frontend-component-ai-translations. 

### Reasoning

There is a Jenkins job that creates i18n translations PRs but the job fails with the error message below whenever edx-transifex-bot tries to create a PR in the repo
`remote: Permission to openedx/frontend-component-ai-translations.git denied to edx-transifex-bot.
fatal: unable to access 'https://github.com/openedx/frontend-component-ai-translations.git/': The requested URL returned error: 403`

**Comment by feanil** [comment]
@OmarIthawi @brian-smith-tcril does it make sense to set up this new repo with the new OEP-58 tooling to begin with rather than with the old jenkins tooling internal to 2U?

**Comment by brian-smith-tcril** [comment]
>l does it make sense to set up this new repo with the new OEP-58 tooling to begin with rather than with the old jenkins tooling internal to 2U?

Yes. We should not be setting up `edx-transifex-bot` on new repos ([first commit](https://github.com/openedx/frontend-component-ai-translations/commit/da752f96d8895e15ef1b53f0995b36c9164702f7) is from Oct 18, 2023). @hajorg was there documentation you were following that recommended this? I'd like to make sure any docs recommending this are updated to point to https://docs.openedx.org/en/latest/developers/how-tos/enable-translations-new-repo.html

**Comment by hajorg** [comment]
> > l does it make sense to set up this new repo with the new OEP-58 tooling to begin with rather than with the old jenkins tooling internal to 2U?
> 
> Yes. We should not be setting up `edx-transifex-bot` on new repos ([first commit](https://github.com/openedx/frontend-component-ai-translations/commit/da752f96d8895e15ef1b53f0995b36c9164702f7) is from Oct 18, 2023). @hajorg was there documentation you were following that recommended this? I'd like to make sure any docs recommending this are updated to point to https://docs.openedx.org/en/latest/developers/how-tos/enable-translations-new-repo.html

Hi @brian-smith-tcril, https://github.com/openedx/frontend-platform/blob/master/docs/how_tos/i18n.rst is the documentation I was following for the setup. I wasn't aware there is another way of achieving translations.

**Comment by hajorg** [comment]
Hi, I forked https://github.com/openedx/openedx-translations and created a PR https://github.com/hajorg/openedx-translations/pull/1 following the steps outlined in https://docs.openedx.org/en/latest/developers/how-tos/enable-translations-new-repo.html#id7 but CI seems to be failing. It seems as though I might need an env variable. Can someone help verify if I’m doing the right thing and what I need to do to resolve the issue.

cc @brian-smith-tcril @feanil

**Comment by brian-smith-tcril** [comment]
@hajorg the `GH_TOKEN` error [here](https://github.com/hajorg/openedx-translations/actions/runs/7448989802/job/20296012175?pr=1) is coming from [here](https://github.com/openedx/openedx-translations/blob/5ef07aa9c987424727270670e6feddee95f5bfb9/.github/workflows/extract-translation-source-files.yml#L461-L463)

```yaml
        env:
          # This token requires Write access to the openedx-translations repo
          GITHUB_TOKEN: ${{ secrets.EDX_TRANSIFEX_BOT_GITHUB_TOKEN }}
```

I would not worry about that step failing on your fork, the branch created by the action seems to have a valid [`transifex_input.json` file](https://github.com/openedx/openedx-translations/compare/main...hajorg:openedx-translations:automated/extract-translation-source-files-20240109T100833#diff-3addddba192c7b3554293a24101746634e6934b2c2596d7d9997dd8122917fe2) in the `frontend-component-ai-translations` directory, which is more than enough to verify things are working as expected without merging into your fork's `main` branch.

**Comment by hajorg** [comment]
> @hajorg the `GH_TOKEN` error [here](https://github.com/hajorg/openedx-translations/actions/runs/7448989802/job/20296012175?pr=1) is coming from [here](https://github.com/openedx/openedx-translations/blob/5ef07aa9c987424727270670e6feddee95f5bfb9/.github/workflows/extract-translation-source-files.yml#L461-L463)
> 
> ```yaml
>         env:
>           # This token requires Write access to the openedx-translations repo
>           GITHUB_TOKEN: ${{ secrets.EDX_TRANSIFEX_BOT_GITHUB_TOKEN }}
> ```
> 
> I would not worry about that step failing on your fork, the branch created by the action seems to have a valid [`transifex_input.json` file](https://github.com/openedx/openedx-translations/compare/main...hajorg:openedx-translations:automated/extract-translation-source-files-20240109T100833#diff-3addddba192c7b3554293a24101746634e6934b2c2596d7d9997dd8122917fe2) in the `frontend-component-ai-translations` directory, which is more than enough to verify things are working as expected without merging into your fork's `main` branch.

Got it. Thanks @brian-smith-tcril. This means I can create a PR against https://github.com/openedx/openedx-translations, right?

**Comment by brian-smith-tcril** [comment]
> Got it. Thanks @brian-smith-tcril. This means I can create a PR against https://github.com/openedx/openedx-translations, right?

@hajorg Yes!

**Comment by feanil** [comment]
Ok, it sounds like you have what you need @hajorg , is there anything else you need before I close this ticket?

**Comment by hajorg** [comment]
> Ok, it sounds like you have what you need @hajorg , is there anything else you need before I close this ticket?

@feanil , thank you for your help. This can be closed.
