### ISSUE TITLE
[GH Request] 2u-phoenix in edx-val repository

### ISSUE THREAD

**Issue by Ali-D-Akbar** [openedx/axim-engineering#1015]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

Hi there,
Can someone add `2u-phoenix` team in edx-val contributors? 

### Reasoning

We're unable to add them as reviewers in automated update reqs PRs. https://github.com/openedx/edx-val/actions/runs/7417280718

**Comment by kdmccormick** [comment]
Added with Triage access: https://github.com/orgs/openedx/teams/2u-phoenix/repositories

Let's see if that works: https://github.com/openedx/edx-val/actions/runs/7417280718/job/20267365137

**Comment by kdmccormick** [comment]
Looks like it worked, let me know if you run in to any more issues with this repo.
