### ISSUE TITLE
[GH Request] Remove access for former employee

### ISSUE THREAD

**Issue by atrepca** [openedx/axim-engineering#1018]
### Firm Name

2U, Inc

### Urgency

High (< 3 days)

### Requested Change

Hi,

Please remove the user `adzuci` - Adam Blackwell - from this GitHub organization, he has left the company.

Thanks,

### Reasoning

Not with the company anymore, and access needs to be revoked.

**Comment by kdmccormick** [comment]
Dupe of https://github.com/openedx/axim-engineering/issues/1021, I'll use that ticket.
