### ISSUE TITLE
Remove Bok-choy usage in ecommerce repo

### ISSUE THREAD

**Issue by salman2013** [openedx/axim-engineering#1020]

**Comment by salman2013** [comment]
PR Link: https://github.com/orgs/openedx/projects/55/views/1?pane=issue&itemId=49965514

**Comment by kdmccormick** [comment]
Hi @salman2013 , is this a to-do item, or PR Review request? If it's a to-do item, please open an issue in the ecommerce repo. If it's a PR review request, just tag us on the PR you'd like reviewed. Thanks.
