### ISSUE TITLE
[GH Request] Onboard pomegranited to edx-platform

### ISSUE THREAD

**Issue by pomegranited** [openedx/axim-engineering#1023]
### Firm Name

OpenCraft

### User List (case sensitive!) - Please also include in ticket title

* pomegranited

### Start Date

17 January 2024

### Urgency

Low (2 weeks)

### Special Requests

https://discuss.openedx.org/t/coding-cc-rights-expansion-jillian-vogel/12016

Please extend my merge rights to include edx-platform, and point me towards any CC rules/guidelines specific to this repo.

Thank you!

**Comment by kdmccormick** [comment]
I created a new team for this, with Jill as its first member: https://github.com/orgs/openedx/teams/committers-edx-platform/members

Congrats @pomegranited !! Let me know if you run any issues with your access.
