### ISSUE TITLE
[GH Request] Bad Slack link on openedx.org is preventing some signups

### ISSUE THREAD

**Issue by timmc-edx** [openedx/axim-engineering#1024]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

There are two Slack invite links on https://openedx.org/community/connect/ and one of them is incorrect, preventing signups.

- The correct link (`https://openedx.org/slack`) is at the bottom of the page.
- The incorrect one (`http://openedx-slack-invite.herokuapp.com/`) is just above the form, about one screen from the top. It only allows signup with tcril or blend-ed email addresses.

### Reasoning

-

**Comment by timmc-edx** [comment]
@sarina ^ Created the issue I mentioned in Slack.

**Comment by feanil** [comment]
@sarina it looked like the herokup app was redirecting to a different URL than what we were doing in the openedx.org/slack redirection.  I've updated the herokuapp to match what we are redirecting to from openedx.org/slack but if it's possible to have all of the internal urls in the site point to the one redirect, that would be better.  So leaving this ticket open to track the work of removing the http://openedx-slack-invite.herokuapp.com url from anywhere in the wordpress site, but ideally this should resolve the current issues where the two URLs behave differently.

**Comment by sarina** [comment]
I honestly can't figure out how to edit that menu (it's somehow included on the page, but I suck at wordpress and don't know how it's defined). I changed as many references on "pages" as I can find, and will make a ticket on the website team's board to do a find and replace for the rest.
