### ISSUE TITLE
[GH Request] Offboard SRE users

### ISSUE THREAD

**Issue by atrepca** [openedx/axim-engineering#1025]
### Firm Name

2U, Inc

### Urgency

High (< 3 days)

### Requested Change

Hi,

Please remove access for SREs that are no longer with the company:

jdmulloy, Joe Mulloy
matthugs, Matt Hughes
thomty, Tyler Thompson

Thanks,
Alex

### Reasoning

The engineers left the company yesterday, 1/17/24.

**Comment by kdmccormick** [comment]
Will be handled by https://github.com/openedx/axim-engineering/issues/1026
