### ISSUE TITLE
[GH Request] Please enable dependabot alerts for several Enterprise repos

### ISSUE THREAD

**Issue by pwnage101** [openedx/axim-engineering#1027]
### Repositories

* openedx/openedx-ledger
* openedx/enterprise-subsidy
* openedx/frontend-app-enterprise-public-catalog
* openedx/frontend-app-enterprise-public-catalog

### Urgency

Low (2 weeks)

### Requested Change

Please enable dependabot alerts for these repos.

### Reasoning

Good to keep on top of dependency updates for better security.

**Comment by brian-smith-tcril** [comment]
I've enabled dependabot alerts on:
* https://github.com/openedx/openedx-ledger
* https://github.com/openedx/enterprise-subsidy
* https://github.com/openedx/frontend-app-enterprise-public-catalog

If you encounter any issues please let me know!
