### ISSUE TITLE
[GH Request] Update 2u-sre team

### ISSUE THREAD

**Issue by atrepca** [openedx/axim-engineering#1029]
### Firm Name

2U, Inc

### Urgency

Low (2 weeks)

### Requested Change

Hi,

Please update the [2u-sre](https://github.com/orgs/openedx/teams/2u-sre) GitHub team from this organization:
- remove [Rhodester](https://github.com/Rhodester), he's no longer with the SRE team
- Add missing team members:
Sinjin Swanepoel [theonlysinjin](https://github.com/theonlysinjin)
Daniel Boyd [dfboyd](https://github.com/dfboyd)
Craig Phillips [the-real-cphillips](https://github.com/the-real-cphillips)
Heinrich Lotze [HeinrichL93](https://github.com/HeinrichL93)
Warren Groenewald [wgroenewald](https://github.com/wgroenewald)
Chris Montanaro [CMontanaro-11](https://github.com/CMontanaro-11)

Thanks,
Alex

### Reasoning

The 2U SRE team has changed structure and this is not updated.

**Comment by sarina** [comment]
@atrepca for those newcomers who are not a part of the Open edX organization, please first have them follow the steps to be onboarded. You can check who is in the organization here: https://github.com/orgs/openedx/people?query=

Once they are onboarded to the Open edX organization, we can adjust group membership.

**Comment by atrepca** [comment]
Thanks @sarina, can you please point me to what they have to do in order to be invited to the `openedx` GitHub organization? Is a specific process documented somewhere?

Thanks,

**Comment by sarina** [comment]
@atrepca please reach out to 2U's IT department, they should know how to onboard new employees.

**Comment by brian-smith-tcril** [comment]
completed via https://github.com/openedx/axim-engineering/issues/1031 and https://github.com/openedx/axim-engineering/issues/1032
