### ISSUE TITLE
Can I get access to Confluence on openx.atlassian.net?

### ISSUE THREAD

**Issue by Yagnesh1998** [openedx/axim-engineering#1030]
### Firm Name

manprax

### Urgency

Low (2 weeks)

### Problem/Request

I am a reviewer in the Hindi language in Trasifix and I also contribute to DEPR and as well another data working group as per Eden's suggestion I create an account in Confluence but I am not able to access openedx  pages and I am facing the following error. as well as Diana who handles DEPR WG also tried to invite me to Confluence but she doesn't have access.
yagnesh.nayi@manprax.com (firm id) as well  nayiyagnesh7@gmail.com ** (personal id) **But I don't have access to Confluence on openedx.atlassian.net.**

### Reasoning

![Screenshot from 2024-01-19 20-10-03](https://github.com/openedx/axim-engineering/assets/127923546/fc64d930-dfdd-4a2b-bd22-43fe9179ef73)
![Screenshot from 2024-01-20 19-29-37](https://github.com/openedx/axim-engineering/assets/127923546/9c5a3ffe-0001-42c0-8e48-0a9127da3651)

I try to tag my name like all Open edX members because I am working in another wing with Transifex, and I am trying to contribute my best to the community.
as per Robert's (2U member) suggestion, I create a ticket here.
thanks

**Comment by sarina** [comment]
@Yagnesh1998 - I've invited both email addresses. Could you please try now?

**Comment by Yagnesh1998** [comment]
@sarina Thank you very much, problem solved.
