### ISSUE TITLE
[GH Request] Onboard <theonlysinjin, dfboyd, the-real-cphillips, HeinrichL93, wgroenewald, CMontanaro-11>

### ISSUE THREAD

**Issue by kmedina2u** [openedx/axim-engineering#1031]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Sinjin Swanepoel, [theonlysinjin](https://github.com/theonlysinjin)
* Daniel Boyd, [dfboyd](https://github.com/dfboyd)
* Craig Phillips, [the-real-cphillips](https://github.com/the-real-cphillips)
* Heinrich Lotze, [HeinrichL93](https://github.com/HeinrichL93)
* Warren Groenewald, [wgroenewald](https://github.com/wgroenewald)
* Chris Montanaro, [CMontanaro-11](https://github.com/CMontanaro-11)

### User Squad

2u-sre

### Start Date

23 January 2024

### Urgency

Low (2 weeks)

### Special Requests

Related to issue #1029 submitted by @atrepca 

* Sinjin Swanepoel, [sswanepoel@2u.com](mailto:sswanepoel@2u.com)
* Daniel Boyd, [dboyd@2u.com](mailto:dboyd@2u.com)
* Craig Phillips, [cphillips@2u.com](mailto:cphillips@2u.com)
* Heinrich Lotze, [hlotze@2u.com](mailto:hlotze@2u.com)
* Warren Groenewald, [wgroenewald@2u.com](mailto:wgroenewald@2u.com)
* Chris Montanaro, [cmontanaro@2u.com](mailto:cmontanaro@2u.com)

**Comment by brian-smith-tcril** [comment]
@alexrileyswan01 I have assigned this to myself and will complete it on Monday.

**Comment by alexrileyswan01** [comment]
@brian-smith-tcril Thank you, Hope you have a good weekend

**Comment by brian-smith-tcril** [comment]
I have
* Added all requested users to the CLA database
* Invited all requested users
  * to the openedx GitHub Org
  * to the 2u-edx-legacy team
  * to the openedx-triage team
  * to the 2u-sre team
