### ISSUE TITLE
[GH Request] Onboard @sohailfatima @eemaanamir

### ISSUE THREAD

**Issue by sohailfatima** [openedx/axim-engineering#1037]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Fatima Sohail @sohailfatima
Eemaan Amir @eemaanamir

### User Squad

Infinity

### Start Date

31 January 2024

### Urgency

High (< 3 days)

### Special Requests

Need access to the following teams:
1. openedx/2u-infinity
2. openedx/edx-infinity
3. openedx/openedx-triage
4. openedx/2u-edx-legacy
5. edx/edx-infinity

Access is especially urgent as this is blocking the team.
Team Lead: Asad Azam @asadazam93

**Comment by brian-smith-tcril** [comment]
@georgebabey - can you verify this request is approved? Also, should @asadazam93 be added as an approver in the CLA database?

**Comment by georgebabey** [comment]
Sorry about that @brian-smith-tcril  - we're going to have helpdesk reopen this one

**Comment by brian-smith-tcril** [comment]
@sohailfatima - @georgebabey mentioned that a new request would be made through the helpdesk. A new request has not been submitted.
