### ISSUE TITLE
[GH Request] Peter Pinch - expand access to  docs.openedx.org repo

### ISSUE THREAD

**Issue by pdpinch** [openedx/axim-engineering#1039]
### Firm Name

MIT Open Learning

### Urgency

Low (2 weeks)

### Requested Change

Please add commit rights to https://github.com/openedx/docs.openedx.org/ for https://github.com/orgs/openedx/teams/ccp-committer-pdpinch

### Reasoning

Self-nominated and approved: https://discuss.openedx.org/t/coding-cc-rights-expansion-peter-pinch/11909

**Comment by bmtcril** [comment]
Should be all set, let me know if you run into any issues!
