### ISSUE TITLE
Recommend/create service account for geoipupdate

### ISSUE THREAD

**Issue by pshiu** [openedx/axim-engineering#1046]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

May I request a recommendation for a GitHub (service) account for one of our bots to use to continue to refresh file GeoLite2-Country.mmdb in openedx/edx-platform?

I would need assistance getting the username, email, and a personal access token for that account, and in ensuring that the account and token has access to push commits and open/merge PRs in edx-platform.

### Reasoning

- **Bot purpose**: We run a Jenkins job called "update-geoip-db" that refreshes the edx-platform file GeoLite2-Country.mmdb [[example PR](https://github.com/openedx/edx-platform/pull/34208/files)] using a script from openedx/ecommerce-scripts called [**geoipupdate/pull.py**](https://github.com/openedx/ecommerce-scripts/blob/master/geoipupdate/pull.py).
- **Bot relevance**: The path to this file is stored in an LMS setting called [GEOIP_PATH](https://github.com/openedx/edx-platform/blob/3919c45c98063dc9303c514e40cd2845c120d786/lms/envs/common.py#L1118), used by [country_code_from_ip()](https://github.com/openedx/edx-platform/blob/3919c45c98063dc9303c514e40cd2845c120d786/openedx/core/djangoapps/geoinfo/api.py#L21), used in a couple places [[GitHub search](https://github.com/search?q=repo%3Aopenedx/edx-platform%20country_code_from_ip&type=code)] across LMS.
- **Why now?** Our job is currently failing because it piggybacked on the `edx-transifex-bot` user, which was recently deprecated [[public-engineering#225](https://github.com/openedx/public-engineering/issues/225)]
- **How does the script auth?** The script uses [[transifex/utils.py](https://github.com/openedx/ecommerce-scripts/blob/0ae1aa6c921723312ac36a487d585c71620d8395/transifex/utils.py#L139)] to authenticate with GitHub, which requires a [GitHub personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#using-a-personal-access-token-on-the-command-line) to use.
- **What permissions?** The script will write commits, open PRs, and merge PRs in edx-platform.

**Comment by pshiu** [comment]
cc: @robrap

**Comment by bmtcril** [comment]
Hi @pshiu, we're kicking around the best way to go about keeping this job around. I'm currently leaning toward moving it to a Github action and bringing the code into edx-platform. Are there other repos using it that you know of?

**Comment by bmtcril** [comment]
@feanil this seems like a bigger issue than on-call, if we wanted to bring this code into edx-platform in a way similar to the tubular migration, then create a github action for it, do you think that's work aximprovements could pick up?

**Comment by pshiu** [comment]
Hey @bmtcril! The only repo it runs on is edx-platform. No particular rush on this one - thank you.

**Comment by bmtcril** [comment]
Hi @openedx/axim-aximprovements ! I spoke with @feanil about this task and I think it's too big for us to handle as an on-call ticket. Can you take a look and let me know if you have any questions? I believe the work here is:

- Move the scripts from `ecommerce-scripts` to `edx-platform` similar to the tubular work
- Create a bot user with permissions to create PRs against edx-platform
- Get credentials from maxmind to access the GeoIP web service and store them in the github secrets for edx-platform
- Create a github action to run weekly that will download the new file and open a PR if there are any changes

This isn't super urgent, but shouldn't sit longer than a few weeks. Thanks!

**Comment by farhan** [comment]
Adding details as per discussed with @feanil 
We have to convert the following script into Github Actions workflow rather than calling the script.
https://github.com/openedx/ecommerce-scripts/blob/master/geoipupdate/pull.py

**Comment by feanil** [comment]
This is now a github workflow running monthly.

**Comment by farhan** [comment]
@feanil Shouldn't we remove these docs from its repo now? Follow up ticket?
https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/user_retire/index.html
