### ISSUE TITLE
[GH Request] Offboard tpreston2u

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#1047]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Currently, https://github.com/orgs/openedx/teams/teaching-and-learning contains Taylor Preston.  However, taylor finished the internship and should be removed from the team.

### Reasoning

Keep it clean!

**Comment by bmtcril** [comment]
Thanks Jeremy! I've removed him from the team, but should he be totally offboarded? It doesn't look like there's an offboarding ticket for him and he still has other access and is likely under the 2U CLA.

**Comment by jristau1984** [comment]
Yes, that would be great.  Thanks!

**Comment by bmtcril** [comment]
All set, thanks for staying on top of these!
