### ISSUE TITLE
[GH Request] Failing Github action pr-automerge-open-release

### ISSUE THREAD

**Issue by bmtcril** [openedx/axim-engineering#1048]
### Firm Name

Axim

### Urgency

Low (2 weeks)

### Problem/Request

The Github action pr-automerge-open-release in edx-platform has been failing for 4 months. Do we still need this? 

```
 Invalid workflow file: .github/workflows/pr-automerge-open-release.yml#L24
error parsing called workflow
".github/workflows/pr-automerge-open-release.yml"
-> "openedx/.github/.github/workflows/pr-automerge-open-release.yml@master"
: failed to fetch workflow: workflow was not found.
```

### Reasoning

If we don't need this we should delete it, if we do need it we should fix it. Just creating this to make sure it doesn't get lost.

**Comment by arbrandes** [comment]
Assigning myself as on-call to take a peek.

**Comment by arbrandes** [comment]
We're not using that workflow anymore: see https://github.com/openedx/axim-engineering/issues/898.

What I don't understand is why that workflow is running at all.  It doesn't exist in `master` anymore (as of https://github.com/openedx/edx-platform/pull/33369).  I went ahead and disabled it manually, though.

@feanil, anything else that need be done, here?

**Comment by feanil** [comment]
I think this is sufficient for now, the workflow still exists on old branches of edx-platform which is why we're seeing this. Once we stop having PRs to palm branches, this will go away on its own but I think the manual disable is the correct choice in the mean time.
