### ISSUE TITLE
[GH Request] Mobile Designer access

### ISSUE THREAD

**Issue by marcotuts** [openedx/axim-engineering#1054]
### Firm Name

Schema

### Urgency

Low (2 weeks)

### Requested Change

We’d like to move our design backlog into GitHub but this requires expanded access for sdaitzman and lizc577. Both are schema team members who need to be able to edit and contribute to the openedx mobile roadmap project but I cannot assign them a role for that project unless they are in the openedx org possibly? 

### Reasoning

Module design backlog in community context of github

**Comment by marcotuts** [comment]
I had to self assign this to let it’ll the creation validation work but I hope that doesn’t break any automation

**Comment by arbrandes** [comment]
Yeah, I think they need to be in the org with triage access.  I'll check if there's anything else that needs to happen for them to get this access.

**Comment by arbrandes** [comment]
Invited both to the org with triage access.  Let me know if this turns out not to be enough!  Closing, for now.
