### ISSUE TITLE
[GH Request] archive frontend-app-programs-dashboard.

### ISSUE THREAD

**Issue by deborahgu** [openedx/axim-engineering#1064]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

Please  recategorize  the repository https://github.com/openedx/frontend-app-programs-dashboard as unsupported (or archive it).

### Reasoning

See the [corresponding DEPR ticket](https://github.com/openedx/frontend-app-programs-dashboard/issues/5). This repository was created as a stub for hackathon project has never held any code. A fork was created as part of that experiment but there has never been anything in this repository  per se, and the fork was never used. It will not make any changes to any instances whatsoever.

**Comment by arbrandes** [comment]
Archived: https://github.com/openedx-unsupported/frontend-app-programs-dashboard
