### ISSUE TITLE
[GH Request] frontend-app-learning translation job is failing

### ISSUE THREAD

**Issue by leangseu-edx** [openedx/axim-engineering#1066]
### Repository

axim-engineering

### Urgency

Low (2 weeks)

### Requested Change

add `openedx-transifex-bot` as contributor with permission to write for frontend-app-learning. The job for translation is failing with message `remote: Permission to openedx/frontend-app-learning.git denied to openedx-transifex-bot`

### Reasoning

We need automation for translation running.

**Comment by brian-smith-tcril** [comment]
Where is this job? If there is a job running that is trying to directly commit translations to `frontend-app-learning` it should be turned off. Translations for `frontend-app-learning` are available here https://github.com/openedx/openedx-translations/tree/main/translations/frontend-app-learning/src/i18n. There is also a DEPR notice here https://discuss.openedx.org/t/deprecation-removal-edx-transifex-bot-public-engineering-225/12218

**Comment by leangseu-edx** [comment]
The job is running on jenkins. Should it be turn off for all of MFE repository on openedx? For both `push` and `pull` script?

**Comment by brian-smith-tcril** [comment]
> Should it be turn off for all of MFE repository on openedx? For both `push` and `pull` script?

Yes. All transifex integration goes through the `openedx-translations` repository now.
