### ISSUE TITLE
[GH Request] Update frontend-app-authn reviewers

### ISSUE THREAD

**Issue by zainab-amir** [openedx/axim-engineering#1067]
### Repository

axim-engineering

### Urgency

Low (2 weeks)

### Requested Change

I am in the process of updating the team information for frontend-app-authn to use @openedx/2u-vanguards 
PR: https://github.com/openedx/frontend-app-authn/pull/1177. However the team does not have the correct permissions on this repo. 

- Please provide the same access to @openedx/2u-vanguards as the original @openedx/vanguards group had. 
- Can I also get maintainer access for the team @openedx/2u-vanguards 

### Reasoning

Moving away from using legacy vanguards group to @openedx/2u-vanguards group

**Comment by zainab-amir** [comment]
@arbrandes to add/remove team members if needed

**Comment by arbrandes** [comment]
Ah, I misread the original request: you're asking for maintainership of the team, not the repo.  Perfect, done!

Also added 2u-vanguards with write access to edx-platform.
