### ISSUE TITLE
[GH Request] frontend-app-course-authoring does not appear to require a review before a merge

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#1068]
### Repository

axim-engineering

### Urgency

Low (2 weeks)

### Requested Change

frontend-app-course-authoring does not appear to require a review before a merge.  Can someone look into this, and make sure that this repo is configured to the expectations of Axim?

### Reasoning

Gotta keep stuff safe, ya know?

**Comment by arbrandes** [comment]
It's currently configured to require one approval, as well as pass checks:

![image](https://github.com/openedx/axim-engineering/assets/759355/4a820288-21a6-4bca-a1f2-1b8ddf2460f2)

May I ask what leads you to believe otherwise?

**Comment by arbrandes** [comment]
@jristau1984, does anything look funny in the repo settings? :)

**Comment by jristau1984** [comment]
@arbrandes I cannot see repo settings.

**Comment by arbrandes** [comment]
Sorry, I meant in the screenshot I sent in the comment above.
