### ISSUE TITLE
[GH Request] @zwidekalanga and @jono-booth the openedx github organization

### ISSUE THREAD

**Issue by macdiesel** [openedx/axim-engineering#1069]
### Firm Name

2u

### Urgency

Medium (< 2 weeks)

### Requested Change

Please add
@zwidekalanga and @jono-booth the openedx github organization https://github.com/orgs/openedx/people and titans team: https://github.com/orgs/openedx/teams/enterprise-titans

### Reasoning

These folks are contractors working on edX software based out of ZA.

**Comment by arbrandes** [comment]
Done!
