### ISSUE TITLE
[GH Request] Archive the EASE repo

### ISSUE THREAD

**Issue by timmc-edx** [openedx/axim-engineering#1070]
### Repository

openedx-unsupported/ease

### Urgency

Low (2 weeks)

### Requested Change

https://github.com/openedx-unsupported/ease should be archived, as it has been moved to the unsupported org.

### Reasoning

This is really a suggestion, not a request, but I'm guessing this was overlooked when the repo was deprecated.

Currently it's the only one in that org that is not archived: https://github.com/orgs/openedx-unsupported/repositories?type=all&q=archived%3Afalse

**Comment by arbrandes** [comment]
Nice catch!  Thanks, @timmc-edx, and done.
