### ISSUE TITLE
[GH Request] Onboard <alaaet>

### ISSUE THREAD

**Issue by alaaet** [openedx/axim-engineering#1074]
### Firm Name

no firm

### User List (case sensitive!) - Please also include in ticket title

Alaa Abuiteiwi

### User Squad

no squad

### Start Date

01/03/2024

### Urgency

Low (2 weeks)

**Comment by arbrandes** [comment]
Are you asking this on behalf of an organization?  If so, which one?  If not, are you being onboarded as a core contributor?  If so, can you point to your nomination?

**Comment by arbrandes** [comment]
Ah, in that case:

1. Thank you for volunteering!  The best place to start contributing on translation issues would be joining [the Translation Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3157524644/Translation+Working+Group#How-to-join-us).
2. These onboarding requests are specific to people being inducted into the [core contributor program](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0054-core-contributors.html), which is something to aim for, but it's not the first step in getting involved.
