### ISSUE TITLE
2U (LP) Github Team updates

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#1076]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Please remove the following members from existing teams:
* 2u-arbi-bom: awais786, irtazaakram, zubairshakoorarbisoft
* 2u-arch-bom: jmbowman, nedbat, rgraber
* 2u-aurora: jszewczulak, mattcarter, muselesscreator
* 2u-cosmonauts: chennigan2u
* 2u-fed-bom: Mashal-m, Syed-Ali-Abbas-Zaidi
* 2u-tnl: kenclary

Please add the following members to existing teams:
* 2u-aurora: BrandonHBodine, hajorg, Rodra

### Reasoning

Changes in the past several weeks require updates to our existing team set up.  There will be other tickets as well to delete unnecessary teams, update other domains inside of 2U engineering, etc.  This is the first.

**Comment by kdmccormick** [comment]
FYI @openedx/axim-oncall -- Jeremy and I have been talking about these team updates for a while, and I've given him the green light to file them as bulk tickets. This series of updates will allow 2U to set themselves as maintainers in various catalog-info.yamls, which is important item in Maintenance WG right now.

I know that, simultaneously, Feanil is revoking admin rights from teams, and Ed/George are talking about onboarding 2U devs as CCs. Try to keep these updates separate from those. That is, just make these team changes using whatever today's permissions are, and if we need to change team permissions again in a week or two, that's OK.
