### ISSUE TITLE
[GH Request] Onboard <ADD USERNAMES HERE>

### ISSUE THREAD

**Issue by BrookHabte1** [openedx/axim-engineering#1077]
### Firm Name

Brook

### User List (case sensitive!) - Please also include in ticket title

BrookHabte1

### Start Date

7 March 2024

### Urgency

Low (2 weeks)

**Comment by ormsbee** [comment]
Hello. Unless you are a 2U employee/contractor or a Core Contributor, there is no need to file an onboarding ticket. If you are one of those, please re-open this ticket and either tag your 2U manager or put a link to your CC nomination thread.

If you wish to contribute to the project, you can open a pull request from your own fork of any of the repos, and it will send you information about how to sign our Contributor License Agreement.

Thank you.
