### ISSUE TITLE
Update templates with new catalog-info field and remove openedx.yaml

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#1079]
With https://github.com/openedx/repo-tools/issues/439 completed, we should update the frontend and python templates so that for new repos we no longer create `openedx.yaml` files and the templated `catalog-info.yaml` file has an example entry for release tagging.

### Repos to update 

- [x] frontend-template-application
- [x] edx-cookiecutters

**Comment by irtazaakram** [comment]
PRs ready for review:
- https://github.com/openedx/frontend-template-application/pull/771
- https://github.com/openedx/edx-cookiecutters/pull/452
