### ISSUE TITLE
edx-platform needs @openedx/axim-oncall given write access

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#1080]
### Repository

axim-engineering

### Urgency

Low (2 weeks)

### Requested Change

https://github.com/openedx/edx-platform/blob/master/.github/CODEOWNERS says there is an error...

> Unknown owner on line 50: make sure the team @openedx/axim-oncall exists, is publicly visible, and has write access to the repository
> …/dashboard.html               @openedx/axim-oncall

### Reasoning

CODEOWNERS is throwing an error, and perhaps axim-oncall is not being notified when they should be?

**Comment by ormsbee** [comment]
@openedx/axim-oncall now has write access to edx-platform.
