### ISSUE TITLE
Add "2u-tnl" team to frontend-app-course-authoring with Write permission

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#1081]
### Repository

frontend-app-course-authoring

### Urgency

Medium (< 2 weeks)

### Requested Change

T&L has updated the codeowners to point to a new team, but that team does not have the appropriate permissions on the repo.  They need to have write permissions given to them.  Then, the old "teaching-and-learning" team can be removed from the repo altogether.

### Reasoning

2024 GH Team cleanup

**Comment by ormsbee** [comment]
@openedx/2u-tnl now has write access to openedx/frontend-app-course-authoring.

@jristau1984: Just want to verify that it's now okay for me to remove @openedx/teaching-and-learning ?

**Comment by jristau1984** [comment]
@ormsbee can you please also add me to the 2u-tnl team?

**Comment by jristau1984** [comment]
You can remove the old team from CA repo now.  Thanks!

**Comment by ormsbee** [comment]
Removed teaching-and-learning's access to frontend-app-course-authoring.
