### ISSUE TITLE
[GH Request] Increase permissions for OpenCraft product team

### ISSUE THREAD

**Issue by ali-hugo** [openedx/axim-engineering#1083]
### Firm Name

OpenCraft

### Urgency

Low (2 weeks)

### Requested Change

Increase Github permissions for Ali Hugo (@ali-hugo) and Cassie Zamparini (@cassiezamparini) so that they are able to move tickets from one column to another in [this view](https://github.com/orgs/openedx/projects/4/views/20).

### Reasoning

OpenCraft product managers would like to perform product reviews on PR's, but are unable to move tickets between the "[PR Review] Needs Product Review" and "[PR Review] In Product Review" columns of the [Product Review view](https://github.com/orgs/openedx/projects/4/views/20) on the Open edX Roadmap.

We were told that we may need "triage access" in order to make such changes.

**Comment by sarina** [comment]
@ormsbee members of working groups should get Triage access plus, if it exists, membership to the appropriate WG group which grants access to the board: in this case, https://github.com/orgs/openedx/teams/wg-product/

@ali-hugo - I think what I've done solves your problem. Could you test, and close this ticket if it meets your needs?

**Comment by ali-hugo** [comment]
That worked! Thanks @sarina 💐
