### ISSUE TITLE
[GH Request] Need write access to merge PRs for enterprise-access

### ISSUE THREAD

**Issue by alex-sheehan-edx** [openedx/axim-engineering#1085]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

despite being part of the [enterprise-titans](https://github.com/orgs/openedx/teams/enterprise-titans) github group I seems I'm unable to merge PR's in the [enterprise-access](https://github.com/openedx/enterprise-access) repo

### Reasoning

Best guess is that this may be related to recent downgrading of admin/maintain access to write access work [ttps://twou.slack.com/archives/C049C2JGH3L/p1710254160790649](https://twou.slack.com/archives/C049C2JGH3L/p1710254160790649)

**Comment by alex-sheehan-edx** [comment]
@macdiesel

**Comment by alex-sheehan-edx** [comment]
![image](https://github.com/openedx/axim-engineering/assets/67655836/11838b07-4d0b-4d50-b90b-e8d006a69879)

**Comment by feanil** [comment]
That team has write access to that repo, oh but maybe someone added branch protection rules before,  I'll take a look at those

**Comment by feanil** [comment]
Yep, looks like the issue is 
![image](https://github.com/openedx/axim-engineering/assets/781561/90c8e743-21fc-45b6-86e3-8f54bf121a68)
 which should not be necessary if all pushes have to come via PRs and is not a setting we generally turn  on.  Disabling it now.

**Comment by feanil** [comment]
I've confirmed with @alex-sheehan-edx that this is now resolved.
