### ISSUE TITLE
[GH Request] Jeremy Bowman Confluence access

### ISSUE THREAD

**Issue by jmbowman** [openedx/axim-engineering#1086]
### Firm Name

Formerly 2U

### Urgency

Low (2 weeks)

### Problem/Request

My Confluence access was linked to my 2U account, so I no longer have a working login for the wiki.  I'd like to grant access to my atlassian@portabase.org Atlassian account (or can create a new account if necessary).

### Reasoning

My ability to search for even content I wrote myself is limited as an anonymous user, and I'd like to have the option of commenting on pages related to work I was involved in so I can provide additional context.

**Comment by ormsbee** [comment]
I've sent an invitation to atlassian@portabase.org. Please create a new account. Thank you.
