### ISSUE TITLE
[GH Request] Onboard eemaanamir (2U)

### ISSUE THREAD

**Issue by eemaanamir** [openedx/axim-engineering#1087]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

I need to be added to GitHub teams for push/pull access and CLA to repositories to be able to follow a regular workflow and contribute effectively to the team. I am currently blocked due to no access. I need to be added to the following teams:

1. openedx/2u-infinity
2. openedx/edx-infinity
3. openedx/openedx-triage
4. openedx/2u-edx-legacy

Team: Infinity Squad

### Reasoning

I need to be added to GitHub teams for push/pull access and CLA to repositories to be able to follow a regular workflow and contribute effectively to the team. I am currently blocked due to no access. I need to be added to the following teams:

1. openedx/2u-infinity
2. openedx/edx-infinity
3. openedx/openedx-triage
4. openedx/2u-edx-legacy

Team: Infinity Squad

**Comment by ormsbee** [comment]
@eemaanamir: Please have a 2U engineering manager (@hurtstotouchfire? @georgebabey?) comment in this request to verify this request. Thank you.

**Comment by eemaanamir** [comment]
@hurtstotouchfire  please approve this request. I am a part of the Infinity Squad and need this access to contribute effectively to the team.

**Comment by hurtstotouchfire** [comment]
@ormsbee I approve this 👍

**Comment by ormsbee** [comment]
@eemaanamir: I've sent you an invite to the `openedx` GitHub org and those teams. Please let me know if have any trouble. Thank you.
