### ISSUE TITLE
[GH Request] Onboard Mahendra040

### ISSUE THREAD

**Issue by antoviaque** [openedx/axim-engineering#1088]
### Firm Name

Independent

### User List (case sensitive!) - Please also include in ticket title

* Mahendra Chaudhari, @Mahendra040

### Start Date

March 18th 2023

### Urgency

Medium (< 2 weeks)

### Special Requests

Not sure if this is the right type of ticket - this is for onboarding @Mahendra040 as a core contributor (as a forum moderator), following this nomination thread: https://discuss.openedx.org/t/core-contributor-nomination-mahendra-chaudhari/12345

### Non-Coding CC Onboarding Checklist for Axim On-Call

- [x] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [x] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Let CC know that they may be required to take the privacy and a11y courses when they become available.
- [x] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while).  Keep the ticket open with status “Blocked”, until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [x] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [x] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [x] Look up their record in Salesforce and grant them the Core Contributor role.
- [x] Send Dean a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)
- [x] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

**Comment by ormsbee** [comment]
@Mahendra040: I sent an invite to the onboarding course to the gmail account listed in your Slack profile. Please let me know if you've gotten it or not.

**Comment by Mahendra-TitanEd** [comment]
Hi @ormsbee Yes, I received invite for the "Core Contributor Onboarding" course. I can access it without any issues.

**Comment by ormsbee** [comment]
@sarina: Per the script, putting this into "blocked", pending verification that legal docs are signed.

**Comment by ormsbee** [comment]
> Hi @ormsbee Yes, I received invite for the "Core Contributor Onboarding" course. I can access it without any issues.

@Mahendra040: That's great! Please note that you may be required to take the privacy and a11y courses at a later date, when those courses eventually become available. It's not going to block this onboarding ticket.

**Comment by Mahendra-TitanEd** [comment]
Hi @ormsbee. What's the next step here?

**Comment by sarina** [comment]
Hi @Mahendra-TitanEd - we spoke via email. I will continue processing this request once your agreement is signed with our Legal team (next week).

**Comment by sarina** [comment]
@Mahendra040 I've just sent you an invite to GitHub, please let me know when you've accepted it!

**Comment by mahendra0401** [comment]
Hi @sarina 
I received below things:
- Added in Open edX Core Contributors (All) google group
- Added in #core-contributors and #discourse-moderators slack channels

I didn't received any invite from Github.

**Comment by sarina** [comment]
@mahendra0401 you're using multiple different GitHub accounts. We can only add one for you. Please let me know which you prefer:

@mahendra0401 
@Mahendra-TitanEd 
@Mahendra040

**Comment by mahendra0401** [comment]
Sorry, for confusing.

You can use chaudhari040@gmail.com(@mahendra0401) which is my personal github account.

**Comment by sarina** [comment]
@mahendra0401 I've invited you to GitHub at this account. You are now onboarded!
