### ISSUE TITLE
[GH Request] Learner Dashboard MFE: Requesting branch protections for a 2U branch in the `openedx` GitHub org

### ISSUE THREAD

**Issue by justinhynes** [openedx/axim-engineering#1089]
### Repository

frontend-app-learner-dashboard

### Urgency

Medium (< 2 weeks)

### Requested Change

Would it be possible to add branch protections to the `2u/main` branch for the Learner Dash MFE in the `openedx` GitHub org? We'd like to make it so the branch can't be deleted. 

### Reasoning

2U would like to deploy the Learner Dashboard MFE from its own branch. We didn't want to hard fork, as we are not planning on modifying or otherwise customizing the project at this time. Instead, we created the `2u/main` branch under the `openedx` GitHub org. 

We want to ensure a chance to scrutinize any changes that are being deployed rather than always deploying the latest version. This will allow us to deploy the changes faster than adopting named releases as part of our deployment strategy. 

Having branch protections that prevent deletion at this time would help us feel a bit better about this approach.

**Comment by ormsbee** [comment]
After discussion with @justinhynes, also added the requirement that changes to `2u/main` will require a pull request.
