### ISSUE TITLE
[GH Request] Onboard MoisesGSalas

### ISSUE THREAD

**Issue by jfavellar90** [openedx/axim-engineering#1090]
### Firm Name

edunext

### User List (case sensitive!) - Please also include in ticket title

Moises de Jesus Gonzalez, @MoisesGSalas

### Start Date

19 March 2024

### Urgency

Low (2 weeks)

### Special Requests

Requesting CC access for Moises de Jesus Gonzalez with gh username @MoisesGSalas to [codejail](https://github.com/openedx/codejail) and [codejail includes](https://github.com/openedx/codejail-includes) repositories and the Core Contributor Onboarding course.

**Reasoning**
Moises was nominated via the CC process and was approved by the other members.

Here is the nomination thread:
https://discuss.openedx.org/t/nominating-moises-gonzalez-as-core-contributor-for-openedx/12399

### Coding CC Onboarding Checklist for Axim On-Call

- [x] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [x] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Let CC know that they may be required to take the privacy and a11y courses when they become available.
- [x] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while). Keep the ticket open with status “Blocked” until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [x] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [x] Add the CC to the `@core-contributor-committers` Slack user group
- [x] Remind them to add themselves to the relevant shared Slack channel(s) corresponding to their merge accesses (some [additional context](https://docs.google.com/document/d/1-G-v3nrP8RN_j0P8gEsdI0ahdOoJFePiDHFOuPlUjlk/edit#heading=h.wsc5ai1lrvb6) if you’re curious). Here’s a DM you can copy and use: “For the repositories you have merge access to, [please join the Slack room(s) that correspond to your repositories](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit#gid=0). These rooms are where to coordinate timing on merging breaking or major changes. Keep in mind that 2U runs CI/CD off the tip of master branches, so major changes will impact their site first. It's generally OK to announce in these rooms that you are merging a pr with 24 hour or more notice (eg, I'm merging this tomorrow at 1500 UTC), and engage in discussion with anyone who expresses concern. These rooms are also a good place to ask for a 2U review on critical/breaking change PRs before you get to the merging state.”
- [x] Add them to the [Google group](https://groups.google.com/a/axim.org/g/core-contributors-dev). This is very low traffic, meant primarily for announcements we want to be sure get to all developers. Also add them to the [overall CC group](https://groups.google.com/a/axim.org/g/core-contributors/members?pli=1).
- [x] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [x] Look up their record in Salesforce and grant them the Core Contributor role.
- [x] Ensure they are in the openedx GitHub organization and a member of the [openedx-triage](https://github.com/orgs/openedx/teams/openedx-triage) and [committers](https://github.com/orgs/openedx/teams/committers) teams.
- [x] Grant write access to the repositories described in the vote. Do not grant it directly to the user; instead, use existing **committers-** teams, making new ones as you need to. [See this page for details](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3555852316/GitHub+Access+Team+Structure#Team-names-and-types).
- [x] Send Fox a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)
- [x] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

**Comment by ormsbee** [comment]
@MoisesGSalas: I've sent you an invite to the onboarding course. Please verify that you've received it. Please note that you may be required to take the privacy and a11y courses when they eventually become available, but that will not block this CC onboarding.

**Comment by ormsbee** [comment]
@sarina: Per the script, moving this to "blocked" until legal doc completion is verified.

**Comment by MoisesGSalas** [comment]
Hi @ormsbee, I can confirm I've received the course.

**Comment by sarina** [comment]
@ormsbee documents are signed!

**Comment by sarina** [comment]
@ormsbee have you worked on this ticket or do you need me to take it over?

**Comment by ormsbee** [comment]
@sarina: Sorry, I lost track of this after my on-call handoff. I can get to it this afternoon.

**Comment by ormsbee** [comment]
@MoisesGSalas: I created the group @openedx/committers-codejail with write access to https://github.com/openedx/codejail and https://github.com/openedx/codejail-includes, and added you to it.

**Comment by MoisesGSalas** [comment]
Hi, one thing the ticket mentioned was the Listaflow invitation, but I'm still yet to receive one. Is that something that was missed or is on the way?

cc @ormsbee
