### ISSUE TITLE
[GH Request] Add write permissions for felipemontoya in the openedx/openedx-wordpress-ecommerce repo

### ISSUE THREAD

**Issue by felipemontoya** [openedx/axim-engineering#1091]
### Firm Name

eduNEXT

### Urgency

Low (2 weeks)

### Requested Change

I'd like to get write access to the openedx/openedx-wordpress-ecommerce repository.

### Reasoning

I nominated myself and after the review period the expansion was accepted.

https://discuss.openedx.org/t/core-contributor-rights-expansion-felipe-montoya/12496

**Comment by ormsbee** [comment]
@felipemontoya: Write access granted via your @openedx/ccp-committer-felipemontoya group. I'm having separate conversation as to whether it makes sense to make a different group to control access to that repo. Either way though, it shouldn't block you–we'll add you to the relevant group if we re-organize things. Thank you.
