### ISSUE TITLE
[GH Request] Check on ecommerce branch protection settings

### ISSUE THREAD

**Issue by christopappas** [openedx/axim-engineering#1092]
### Firm Name

2U

### Urgency

High (< 3 days)

### Problem/Request

Hi there,

2U person here 👋 -- I'm looking to schedule a brief time to hop on a call with someone from Axim to help me understand the current state of branch protection for [ecommerce](https://github.com/openedx/ecommerce).

### Reasoning

I believe 2u/main is a protected branch (and it should be). I was asked to verify this was the case on short notice, but I no longer have admin privileges to the repo since the recent access changes, and cannot check that out myself

**Comment by ormsbee** [comment]
Attached are screenshots of the branch protection rules for `2u/main`:

![Screenshot 2024-03-20 at 11 37 21 AM](https://github.com/openedx/axim-engineering/assets/41625/36508db5-2d32-4341-86d5-5b0539d5b3cd)
![Screenshot 2024-03-20 at 11 37 29 AM](https://github.com/openedx/axim-engineering/assets/41625/cc601a58-c411-4410-85bf-cb8a6f996641)

I'm closing this ticket for now, but please re-open if you still think a call is necessary.

**Comment by christopappas** [comment]
Hi Dave, thanks for the prompt response. I'll pass these along and will reach out if I need more info.
