### ISSUE TITLE
[GH Request] Onboard pomegranited

### ISSUE THREAD

**Issue by pomegranited** [openedx/axim-engineering#1093]
### Firm Name

OpenCraft

### User List (case sensitive!) - Please also include in ticket title

* pomegranited

### Start Date

21 March 2024

### Urgency

Low (2 weeks)

### Special Requests

Requesting maintainer status on these repos:

* https://github.com/openedx/edx-submissions/
* https://github.com/openedx/completion/

Reason: https://discuss.openedx.org/t/core-contributor-rights-expansion-maintainership-jillian-vogel/12452

Thank you!

**Comment by e0d** [comment]
@pomegranited I've invited you to two new teams that have been given write access to the repositories in question.

I noticed that @pkulkark has separate access to https://github.com/openedx/completion.  Should they be added to the new team so the permissions are rationalized?

**Comment by pomegranited** [comment]
@e0d Yes please -- @pkulkark [is CC for completion](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Core+Contributors+to+the+Open+edX+Project), but I think that was done before Axim started grouping us in teams.

**Comment by e0d** [comment]
@pkulkark I've added you to the shared cc group, you should see an invitation to join it.  I've remove a legacy group from the repo, 
"CCP Committer: pkulkark"  If you accept the invitation, you should be in business.

**Comment by e0d** [comment]
@pomegranited can you confirm your access looks good?

**Comment by pomegranited** [comment]
@e0d Confirmed, thank you 😄
