### ISSUE TITLE
[GH Request] Lost merge access to taxonomy-connector

### ISSUE THREAD

**Issue by muhammad-ammar** [openedx/axim-engineering#1094]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

I am a member of [markhors](https://github.com/orgs/openedx/teams/2u-markhors) and I used to have the merge access on https://github.com/openedx/taxonomy-connector/ but now I can not merge. 

### Reasoning

Our team has the ownership of https://github.com/openedx/taxonomy-connector/ so we need access to merge our work. Thanks!

**Comment by e0d** [comment]
Assuming you are attempting to merge as the GitHub user muhammad-ammar, you are a member of the team enterprise-markhors in GitHub ant that team has write access to https://github.com/openedx/taxonomy-connector.

Can you please provide more information about what you are seeing?

**Comment by muhammad-ammar** [comment]
Please see the below screenshot.

<img width="1053" alt="Screenshot 2024-03-23 at 1 12 50 AM" src="https://github.com/openedx/axim-engineering/assets/6767924/39642ac7-fc86-4d95-9a0c-1596fb3415c9">

**Comment by muhammad-ammar** [comment]
@e0d Can you please look into this? We are currently blocked due this issue. Thank you!

**Comment by e0d** [comment]
Hi @muhammad-ammar it looks like this repo has custom branch protection on it.  I need to understand what that's the case.  I hope to have an answer for you tomorrow.

**Comment by muhammad-ammar** [comment]
@e0d Thank you! Problem solved. We have the merge access now.
