### ISSUE TITLE
[GH Request] Onboard sameeramin

### ISSUE THREAD

**Issue by dkim2u** [openedx/axim-engineering#1095]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Muhammad Sameer sameeramin

### Start Date

27 March 2024

### Urgency

Low (2 weeks)

**Comment by e0d** [comment]
@dkim2u can you please let me know what squad they are joining.

**Comment by dkim2u** [comment]
Hi! They’re an advisory contractor joining under george babey! George may
be able to give more insight.

*Kim* | she, her, hers
IT HelpDesk Provisioning Associate
7900 Harkins Road, Lanham, MD 20706
Office: 301-892-4350
***@***.*** <https://bit.ly/31YJPg1> | @edxonline
<https://bit.ly/3cnlmDa> | @Lifeat2U <https://bit.ly/3cda0BJ> | #NoBackRow
<https://bit.ly/3iBmIO3>*
Unlock your potential at edX.org <https://edx.org/> and 2u.com/careers/.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system.

**Comment by e0d** [comment]
@georgebabey can you specify the squad?

**Comment by georgebabey** [comment]
@e0d This would be the Iris squad that @sameenfatima78 leads

**Comment by e0d** [comment]
@sameenfatima78 Is Iris a new squad or was markhors renamed?

**Comment by georgebabey** [comment]
Iris is a relatively new squad - formed in the fall - separate from Markhors. Focused on integrations and APIs in the b2b space so they work with a similar set of repos. 

Members: @sameenfatima78, @hamzawaleed01, @MueezKhan246, @zamanafzal and this request for @sameeramin

Want to piggyback the creation of iris squad with this, or a new ticket?

**Comment by sameenfatima78** [comment]
@e0d Hi Edward, just wanted to follow-up on the request here. cc: @sameeramin

**Comment by feanil** [comment]
I'll create the new team and add these folks to it.  @georgebabey are there specific repos they should have access to? I can update the team now while I'm making it.

**Comment by feanil** [comment]
I've created the team and sent Sameer an invite.

**Comment by sameenfatima78** [comment]
George is on leave this week so responding here. The team mostly works in these repositories:

- https://github.com/openedx/edx-platform
- https://github.com/openedx/edx-enterprise
- https://github.com/openedx/edx-enterprise-data
- https://github.com/openedx/license-manager
- https://github.com/openedx/frontend-app-learner-portal-enterprise
- https://github.com/openedx/enterprise-catalog
- https://github.com/openedx/frontend-app-admin-portal
- https://github.com/openedx/enterprise-access
- https://github.com/openedx/course-discovery


Also, would it be possible to add @sameeramin to [2u-edx-legacy](https://github.com/orgs/openedx/teams/2u-edx-legacy) as he still doesn't have write access to any of the Openedx repositories.

**Comment by sameenfatima78** [comment]
@feanil CLA check is failing for Sameer on his PRs. 
- https://github.com/openedx/license-manager/pull/640
- https://github.com/openedx/frontend-app-admin-portal/pull/1204

**Comment by feanil** [comment]
Taking a look now.

**Comment by feanil** [comment]
This should be all set.  @sameenfatima78 Sameer had not been added to our CLA database yet, I've added him now but it takes about 24hrs for that change to propagate so hopefully it should be all set by Monday morning.  If not, please open a new ticket and I can take a further look at it.
