### ISSUE TITLE
[GH Request] enable renovate and renovate-approve for frontend-app-learner-dashboard

### ISSUE THREAD

**Issue by deborahgu** [openedx/axim-engineering#1097]
### Repository

frontend-app-learner-dashboard

### Urgency

Low (2 weeks)

### Requested Change

Hi, we would like renovate and renovate-approve enabled, please. `renovate.json` does exist in the repository.

### Reasoning

The only reason it was never turned on was because the repo wasn't officially maintained, and now it's official. We would definitely like to get all of the updates in and stable before Redwood is cut.

**Comment by e0d** [comment]
@deborahgu I've added this repo to the allow list.  I believe that because there's already a config file, renovate hasn't created a PR to add one.  I'll keep open until we see a PR come through with updates.

**Comment by deborahgu** [comment]
Thanks, we'll keep an eye 🤞

**Comment by deborahgu** [comment]
it's been over a week and I find it pretty unlikely that renovate wouldn't have found something to update by now.  are there any renovate logs anywhere so I can see why this isn't being updated? I wonder if the config file is wrong, although it looks correct.

**Comment by e0d** [comment]
I see something I will try as that repo has protected branches, but it is included in the renovate allow list.  If this doesn't fix the issue, I think removing the config file, re-enrolling, taking the generated file, updating it may be the right approach.

**Comment by deborahgu** [comment]
woot woot, we have [a renovate ticket on the project](https://github.com/openedx/frontend-app-learner-dashboard/pull/314): 

![PRs for frontend-app-learner-dashboard, with a renovate PR at the top](https://github.com/openedx/axim-engineering/assets/260800/cda6dd5e-d410-4f24-9351-5e1782b0bca6)

 thanks so much for all your help!

**Comment by e0d** [comment]
:+1: glad this is all set, sorry for the delay in getting it working.
