### ISSUE TITLE
[GH Request] Recover discourse account?

### ISSUE THREAD

**Issue by davidjoy** [openedx/axim-engineering#1098]
### Firm Name

N/A

### Urgency

Low (2 weeks)

### Problem/Request

Hi all - I'm trying to figure out if there's a way for me to recover and change the email address on my `@djoy` account on Discourse.  Currently I think it's email address points at djoy@2u.com, which I obviously don't have access to anymore.  And the account is also in an edX/2U group which it should be removed from.  I have lots of history with that account (and badges!), I'd love to be able to keep using it instead of just making a new Discourse identity. 

### Reasoning

I intend to stay involved in the community and am currently contracting with Axim, I'd like to be able to keep my identity.

**Comment by e0d** [comment]
I've updated your email to the address that we have on file.  You should receive an email to verify the address and the change.

**Comment by davidjoy** [comment]
Thanks @e0d!  Appreciate it.
