### ISSUE TITLE
[GH Request] Repair of the RevSquad Group for frontend-app-ecommerce

### ISSUE THREAD

**Issue by grmartin** [openedx/axim-engineering#1099]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

My team is the core Revenue and Purchase Squad at 2U (group `openedx/revenue-squad`) under @colinbrash. We have write access as far as we know to all of our core repos, however we are missing access to `openedx/frontend-app-ecommerce`.

Can we have the group permitted to merge as core contributors?

Current Members:

* @colinbrash 
* @grmartin 
* @christopappas 
* @julianajlk 
* @shafqatfarhan 

### Reasoning

We are the core contributor team to this repo. Initial word during the transition was that we would remain so.

**Comment by grmartin** [comment]
This is related to: https://github.com/openedx/frontend-app-ecommerce/pull/379

**Comment by e0d** [comment]
@grmartin can you verify that this list of ecommerce maintainers is correct?  This repo and other commerce related ones have merge restrictions to support 2U compliance needs.  In this case the merge restriction was sublimated by admin access, which has been dialed back.  Adding the ecommerce-maintainers team as allowed mergers will fix this, but I wanted to confirm membership first.

FYI, @jristau1984 and @georgebabey 

macdiesel	[Brian Beggs](https://github.com/orgs/openedx/people/macdiesel) macdiesel
	grmartin	[Glenn R. Martin](https://github.com/orgs/openedx/people/grmartin) grmartin
	colinbrash	[Colin Brash](https://github.com/orgs/openedx/people/colinbrash) colinbrash
	iloveagent57	[Alex Dusenbery](https://github.com/orgs/openedx/people/iloveagent57) iloveagent57
	adamstankiewicz	[Adam Stankiewicz](https://github.com/orgs/openedx/people/adamstankiewicz) adamstankiewicz
	pshiu	[Phillip Shiu](https://github.com/orgs/openedx/people/pshiu) pshiu
	jawad-khan	[jawad khan](https://github.com/orgs/openedx/people/jawad-khan) jawad-khan
	christopappas	[Chris Pappas](https://github.com/orgs/openedx/people/christopappas) christopappas
	julianajlk	[Juliana Kang](https://github.com/orgs/openedx/people/julianajlk) julianajlk
	moeez96	[Moeez Zahid](https://github.com/orgs/openedx/people/moeez96) moeez96
	zubair-ce07	[Muhammad Zubair](https://github.com/orgs/openedx/people/zubair-ce07) zubair-ce07
	mumarkhan999	[Muhammad Umar Khan](https://github.com/orgs/openedx/people/mumarkhan999) mumarkhan999
	JadeyOlivier	[Jade Olivier](https://github.com/orgs/openedx/people/JadeyOlivier) JadeyOlivier
	[MushtaqRossier](https://github.com/orgs/openedx/people/MushtaqRossier)	MushtaqRossier

**Comment by grmartin** [comment]
@e0d: Per @colinbrash this is correct for the moment! No need to cut anyone.

**Comment by e0d** [comment]
Can you verify that you can now merge?

**Comment by grmartin** [comment]
@e0d i can and have, Thank you!

**Comment by georgebabey** [comment]
Thank you @e0d! Appreciate the quick response
