### ISSUE TITLE
[GH Request] User Audit for 2U

### ISSUE THREAD

**Issue by georgebabey** [openedx/axim-engineering#1100]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Problem/Request

2U would like to perform a user audit to ensure that access granted on our side has been tracked and that offboarding has properly resulted in access revoked. Can you provide a list of all users from 2U that have been granted access to openedx?

### Reasoning

While our processes for onboarding and offboarding have improved significantly, we want to make sure everyone is accounted for.

**Comment by sarina** [comment]
@georgebabey ack on this request. I am slammed this week but will take a look next week.

**Comment by feanil** [comment]
@georgebabey sorry this took a while, the list of 2U users that are in the openedx org are attached.
[2u_github_users.txt](https://github.com/openedx/axim-engineering/files/15165823/2u_github_users.txt)
