### ISSUE TITLE
[GH Request] Onboard  Yagnesh1998 

### ISSUE THREAD

**Issue by Yagnesh1998** [openedx/axim-engineering#1106]
### Firm Name

ManpraX

### User List (case sensitive!) - Please also include in ticket title

Yagnesh Nayi  @Yagnesh1998 

### Start Date

04 April 2024

### Urgency

Low (2 weeks)

### Special Requests

https://discuss.openedx.org/t/core-contributor-nomination-yagnesh-nayi/12596

### CC Onboarding Checklist for Axim On-Call

- [x] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [x] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Let CC know that they may be required to take the privacy and a11y courses when they become available.
- [x] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while). Keep the ticket open with status “Blocked” until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [x] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [x] Add them to the [Google group](https://groups.google.com/a/axim.org/g/core-contributors-dev). This is very low traffic, meant primarily for announcements we want to be sure get to all developers. Also add them to the [overall CC group](https://groups.google.com/a/axim.org/g/core-contributors/members?pli=1).
- [x] Look up their record in Salesforce and grant them the Core Contributor role.
- [x] Ensure they are in the openedx GitHub organization and a member of the [openedx-triage](https://github.com/orgs/openedx/teams/openedx-triage)
- [x] Send Fox a direct message on Slack with the full name and email address of the new CC. (Fox will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). 
- [x] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

**Comment by Yagnesh1998** [comment]
I will close it and open a new one with updates

**Comment by yagnesh77** [comment]
https://github.com/openedx/axim-engineering/issues/1107

**Comment by sarina** [comment]
I have invited you to the CC onboarding course. Please confirm you have received the invitation. The next steps will be in the course.

**Comment by Yagnesh1998** [comment]
Yes I received. thank you :)

**Comment by Yagnesh1998** [comment]
@sarina I've completed the Contributor License Agreement (CLA) and attached it for your review. 
thank you

**Comment by sarina** [comment]
@Yagnesh1998 please look for TWO documents from DocuSign, and sign them using DocuSign. Please do not attach any agreements in GitHub or to emails to me.

**Comment by sarina** [comment]
@Yagnesh1998 you are fully onboarded from our side. Welcome!

**Comment by Yagnesh1998** [comment]
@sarina  Thank you very much :)
