### ISSUE TITLE
[GH Request] Authn MFE: Requesting branch protections for a 2U branch in the openedX GitHub org

### ISSUE THREAD

**Issue by zainab-amir** [openedx/axim-engineering#1108]
### Repository

axim-engineering

### Urgency

Medium (< 2 weeks)

### Requested Change

Would it be possible to add branch protections to the 2u-main branch for the Authn MFE in the openedX GitHub org? We'd like to make it so the branch can't be deleted and nothing can be merged in it without a PR.

### Reasoning

2U would like to deploy the Authn MFE from its own branch. We didn't want to hard fork, as we want to make some temporary changes to the routes and run some experimentation. We will be deleting this 2U specific branch after our experimentation is done.

**Comment by sarina** [comment]
I am adding the branch protection rule, please let me know if other options should be required:

<img width="783" alt="image" src="https://github.com/openedx/axim-engineering/assets/1985317/f3506dda-6988-411b-a588-5d555b7ab6b9">

<img width="842" alt="image" src="https://github.com/openedx/axim-engineering/assets/1985317/156aa4a5-b6a8-4cb6-a1a8-28ca02148c64">

**Comment by zainab-amir** [comment]
@sarina please add the following
* Require review from code owners
* Require status checks to pass before merging

**Comment by sarina** [comment]
Done, please open a new ticket if there's any other updates you need.
