### ISSUE TITLE
[GH Request] Cannot merge PRs. CodeCov uploads failing despite retries

### ISSUE THREAD

**Issue by jesperhodge** [openedx/axim-engineering#1109]
### Firm Name

2U

### Urgency

High (< 3 days)

### Problem/Request

It looks like pipelines are failing across different PRs and different repos (course-authoring MFE, learning MFE) due to inability to upload to CodeCov. I know in the past retrying solved this, but I retried 10 times now on my PR and it didn't fix this.
Here's some examples:
- https://github.com/openedx/frontend-app-course-authoring/pull/846 (problem was first observed here)
- https://github.com/openedx/frontend-app-course-authoring/actions/runs/8604487493/job/23601521237#step:6:38
- https://github.com/openedx/frontend-app-course-authoring/actions/runs/8617944055/job/23619770035#step:6:38
- https://github.com/openedx/frontend-app-learning/actions/runs/8597532108/job/23612808929?pr=1346
- https://github.com/openedx/frontend-app-learning/actions/runs/8608881905/job/23591952269?pr=1348

Could you look into this?

### Reasoning

This blocks our ability to merge PRs

**Comment by sarina** [comment]
Hi @jesperhodge - this is related to a change that Codecov made regarding per-repo tokens. @feanil and @brian-smith-tcril are going to take the lead on figuring out how we're going to address this. Apologies that this is happening.

**Comment by jesperhodge** [comment]
Thanks for looking into it!

**Comment by mariajgrimaldi** [comment]
Hi folks. Should we move to python-coverage-comment-action? Or are there more advantages to using the codecov service? There might be use cases that I'm missing though. A few weeks ago I picked up the work Ned started for the replacement: https://github.com/openedx/openedx-events/pull/323

**Comment by feanil** [comment]
@mariajgrimaldi @brian-smith-tcril pointed out that codecov has support for JS which the alternative that we are looking at does not support, so we may need to do more research before we can move off of codecov.

**Comment by feanil** [comment]
@jesperhodge This should be fixed once https://github.com/openedx/frontend-app-course-authoring/pull/950 and https://github.com/openedx/frontend-app-learning/pull/1351 land, can you please review and feel free to merge if they look good to you.

**Comment by mariajgrimaldi** [comment]
@feanil: is that secret common to all openedx repositories? Or do we have to set it up manually? I tried updating codecov [here](https://github.com/openedx/openedx-events/pull/339) but it didn't work:
https://github.com/openedx/openedx-events/actions/runs/8662684410/job/23755234691?pr=339

**Comment by feanil** [comment]
@mariajgrimaldi annoyingly it is per repository, I've added the scertes for openedx-events and filters as well to unblock that codecov update over there if you want to make the github actions updates on those repos.

**Comment by DawoudSheraz** [comment]
The job is failing for edx-val as well https://github.com/openedx/edx-val/pull/496. I followed https://github.com/openedx/i18n-tools/commit/939d4e3b6f22fa7cef5ac4f8ab15f40dc417109d but as @feanil  mentioned, it seems the token would need to be configured for each repository separately.

**Comment by mariajgrimaldi** [comment]
It's also failing in edx-ora2: https://github.com/openedx/edx-ora2/actions/runs/8690285459/job/23829862863?pr=2203

**Comment by feanil** [comment]
edx-ora2 and edx-val have both been updated with the new tokens.

PR for edx-ora2 to update the workflow: https://github.com/openedx/edx-ora2/pull/2206

**Comment by feanil** [comment]
The relevant PRs for the original request have merged so this is all set.  If we find more repos with the same issue, please create new requests and we'll update the repos with tokens.
