### ISSUE TITLE
[GH Request] Remove Code Owner Restriction on 2 Repos

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#1113]
### Repository

axim-engineering

### Urgency

Low (2 weeks)

### Requested Change

The `frontend-app-payment` and `frontend-app-ecommerce` repos should no longer have any 2U specific merge restrictions.

### Reasoning

The `frontend-app-payment` and `frontend-app-ecommerce` repositories are no longer being maintained by 2U and they have their own forks (See attached Image).  We no longer need to have 2U specific code-owner restrictions on these repos for SOX compliance.

![image](https://github.com/openedx/axim-engineering/assets/781561/c11686fa-3464-4a8c-8a2b-234040d20635)

**Comment by christopappas** [comment]
Hey there @feanil I've created the following PRs:

Payment MFE PR: https://github.com/openedx/frontend-app-payment/pull/867
Ecommerce MFE PR: https://github.com/openedx/frontend-app-ecommerce/pull/380

Let me know if this was not what you had in mind.

Thanks!

**Comment by feanil** [comment]
Thanks @christopappas, those looked good and I've merged them.  I've also removed the restriction that codeowner based approval is needed to merge and the restriction that only the revenue squad can merge to master on these repos.  This should be all set.
