### ISSUE TITLE
[GH Request] Move edx-app-ios to openedx-unsupported organization

### ISSUE THREAD

**Issue by marcotuts** [openedx/axim-engineering#1114]
This task should ensure that there is edX / 2U visibility into the timeline in case there are any pipeline issues, but we would like to proceed with moving the edx-ios repository to the openedx-unsupported organization. 

The communicated / accepted DEPR ticket for iOS is here: https://github.com/openedx/public-engineering/issues/260
The Discourse update is here: https://discuss.openedx.org/t/deprecation-removal-edx-mobile-ios-edx-mobile-android-https-github-com-openedx-edx-app-ios-issues-1804-1804/12430
FYI to edX mobile leads - @moiz994 , @miankhalid. 

I will create a similar task for the Android application next.

**Comment by sarina** [comment]
@marcotuts - yeah, next time use the right template so I get alerted to it. But this ticket is fine, because I see it! :)

Could you update the link to the Discourse post? Currently it's a link to the OEP.

**Comment by sarina** [comment]
@marcotuts ping on updating the links properly

**Comment by feanil** [comment]
@sarina @marcotuts I linked to the correct discourse post in the description but it looks like the READMEs in both repos have not been updated to have a deprecation warning and point to the new repos.  @marcotuts can you make those changes on both this and the Android app repos?

**Comment by marcotuts** [comment]
I cannot directly make those changes but @moiz994  / @miankhalid were going to review the readme details updated in their sprint work this month, I will get an update soon hopefully on how that is going soon! 

I pasted a screenshot of the tasks from the linked iOS ticket with the tasks currently planned, if there are other suggestions beyond the readme / deprecation warning note above let me know. 

<img width="878" alt="image" src="https://github.com/openedx/axim-engineering/assets/2023680/ad7661a3-b15b-4c4e-968d-26c0fa39953f">

**Comment by kdmccormick** [comment]
Looks like Ed already took care of the README. I'll archive this repo right after the Redwood cut on May 9th so that we can have it tagged one final time.

**Comment by kdmccormick** [comment]
We talked in standup, and decided that we'll archive this repo now in order to make it clear that it's unsupported. We'll talk to BTR about whether they'd like us to retroactively tag them for Redwood.

**Comment by kdmccormick** [comment]
Archived and moved to openedx-unuspported!

We did the same for [edx-app-android](https://github.com/openedx/axim-engineering/issues/1115), as well as edx-app-test, which was only used by these two deprecated app repos.
