### ISSUE TITLE
[GH Request] Move edx-app-android to openedx-unsupported

### ISSUE THREAD

**Issue by marcotuts** [openedx/axim-engineering#1115]
### Repository

edx-app-android

### Urgency

Low (2 weeks)

### Requested Change

This task should ensure that there is edX / 2U visibility into the timeline in case there are any pipeline issues, but we would like to proceed with moving the edx-android repository to the openedx-unsupported organization. 

The communicated / accepted DEPR ticket for Android is here: https://github.com/openedx/public-engineering/issues/261
The Discourse update is here: https://discuss.openedx.org/t/deprecation-removal-edx-mobile-ios-edx-mobile-android-https-github-com-openedx-edx-app-ios-issues-1804-1804/12430

FYI to edX mobile leads - @moiz994 , @miankhalid. 

I created a similar task for the iOS application but I think used the wrong category, my apologies. I think it is in the 'internal AXIM category'. If I need to recreate let me know for the other issue, I'm hoping it is an easy reclassification

### Reasoning

Deprecation / Shift to the new openedx applications

**Comment by sarina** [comment]
@marcotuts  could you edit the description with a link to the Discourse post? Currently it's a link to the OEP

**Comment by sarina** [comment]
@marcotuts ping on updating the links properly

**Comment by feanil** [comment]
@sarina @marcotuts I linked to the correct discourse post in the description but it looks like the READMEs in both repos have not been updated to have a deprecation warning and point to the new repos.  @marcotuts can you make those changes on both this and the iOS app repos?

**Comment by kdmccormick** [comment]
Ed already took care of both old app READMEs, I think Feanil you may be looking at something else? I'll archive this repo right after the Redwood cut on May 9th so that we can have it tagged one final time.

**Comment by kdmccormick** [comment]
We talked in standup, and decided that we'll archive this repo now in order to make it clear that it's unsupported. We'll talk to BTR about whether they'd like us to retroactively tag them for Redwood.
