### ISSUE TITLE
[GH Request] Please create codecov keys for enterprise repositories

### ISSUE THREAD

**Issue by macdiesel** [openedx/axim-engineering#1117]
### Firm Name

2u

### Urgency

Medium (< 2 weeks)

### Requested Change

Please create codecov tokens for each of the following repos and add the value to the secrets so the enterprise teams can do something similar to this: https://github.com/openedx/edx-val/pull/496/files

Repos:
- https://github.com/openedx/edx-enterprise/
- https://github.com/openedx/enterprise-access/
- https://github.com/openedx/enterprise-catalog/
- https://github.com/openedx/enterprise-subsidy/
- https://github.com/openedx/license-manager
- https://github.com/openedx/openedx-ledger
- https://github.com/openedx/frontend-enterprise
- https://github.com/openedx/frontend-app-learner-portal-enterprise/
- https://github.com/openedx/frontend-app-admin-portal/
- https://github.com/openedx/frontend-app-enterprise-public-catalog/

### Reasoning

- We need code coverage reports to ensure code quality on these repositories.
- I would do this myself, but I no longer have the access necessary to facilitate our day to day operations.

**Comment by macdiesel** [comment]
A few more additions I added late: 
- https://github.com/openedx/frontend-enterprise
- https://github.com/openedx/frontend-app-learner-portal-enterprise/
- https://github.com/openedx/frontend-app-admin-portal/

**Comment by macdiesel** [comment]
Added one more:
- https://github.com/openedx/frontend-app-enterprise-public-catalog/

**Comment by feanil** [comment]
Cool, will do these today.

**Comment by macdiesel** [comment]
🙇

**Comment by feanil** [comment]
These are all set, all of theme should now have a repo secret named `CODECOV_TOKEN` with the correct value in it.
