### ISSUE TITLE
[GH Request] Offboard <@irtazaakram><@Mashal-m><@awais786><@Syed-Ali-Abbas-Zaidi>

### ISSUE THREAD

**Issue by stooks61** [openedx/axim-engineering#1119]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Irtaza Akram, @irtazaakram
Mashal Malik, @Mashal-m
Awais Qureshi, @awais786
Syed Ali Abbas Zaidi, @Syed-Ali-Abbas-Zaidi
Zubair Shkoor, @zubairshakoorarbisoft

### End Date

18 April 2024

### Urgency

Medium (< 2 weeks)

**Comment by stooks61** [comment]
Hey Team - please also depro the user below: 

Zubair Shkoor, @zubairshakoorarbisoft

**Comment by feanil** [comment]
will do, thanks!

**Comment by feanil** [comment]
All off-boardings completed.
