### ISSUE TITLE
[GH Request] Onboard <kalpakkitukaler>

### ISSUE THREAD

**Issue by kalpakkitukaler** [openedx/axim-engineering#1120]
### Firm Name

Ramanbyte

### User List (case sensitive!) - Please also include in ticket title

I am kalpak kitukale , I want to start using open edx and contribute to it.
I have 15 plus years of experience in microsoft stack ie . .net plus mvc asp angular flutter ionic, typescript.
I am new to python , react so could you provide me document or pdf by which I can proceed with understanding , debuging and developing  . could contribute in future 

### Start Date

25 April 2024

### Urgency

High (< 3 days)

**Comment by sarina** [comment]
Hi @kalpakkitukaler and welcome! To begin contributing to the Open edX platform, please see our developer docs here: https://docs.openedx.org/en/latest/developers/index.html

Our discussion forums are also a great place to get help - https://discuss.openedx.org/ - I recommend you search for your topic before making a new post.

You can also learn more about the project on our wiki, https://openedx.atlassian.net/wiki/spaces/COMM/overview

You can contribute to this open source project like you would any other, by forking the code repo you wish to contribute to, making changes on your fork, and submitting a pull request. You can earn merge rights to the project by becoming a _core contributor_, which is described here: https://docs.openedx.org/projects/openedx-proposals/en/latest/processes/oep-0054-core-contributors.html - note, we do not expect contributors to the project to become Core Contributors. All contributions, big or small, are welcome at any time!

**Comment by kalpakkitukaler** [comment]
Hello,
   Thanks .

/Kalpak
