### ISSUE TITLE
[GH Request] Update CCs for openedx/edx-organizations to include felipemontoya

### ISSUE THREAD

**Issue by felipemontoya** [openedx/axim-engineering#1122]
### Firm Name

eduNEXT

### Urgency

Low (2 weeks)

### Requested Change

Write access for @felipemontoya to the https://github.com/openedx/edx-organizations repo.

### Reasoning

As per the nomination:
https://discuss.openedx.org/t/core-contributor-rights-expansion-maintainership-felipe-montoya/12685

I volunteered to become maintainer & cc of edx-organizations.

**Comment by feanil** [comment]
@felipemontoya all set, you should be able to update the catalog-info.yaml and do any other maintenance needed on that repo now.
