### ISSUE TITLE
[GH Request] Remove codecov from required checks in edx-django-utils

### ISSUE THREAD

**Issue by timmc-edx** [openedx/axim-engineering#1124]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

We'd like to have the `codecov/patch` and `codecov/project` status checks removed from the branch protection required checks in <https://github.com/openedx/edx-django-utils>.

### Reasoning

Codecov has been failing to upload for several days now, and it's preventing us from merging. Even the PR to make codecov stop breaking the CI checks can't be merged: https://github.com/openedx/edx-django-utils/pull/410

**Comment by feanil** [comment]
@timmc-edx do you want to upgrade it as suggested [here](https://discuss.openedx.org/t/codecov-upload-breakages/12877) instead?

**Comment by timmc-edx** [comment]
I'd rather just remove it from the blocking path for now. Not sure yet what we want to do after that.

**Comment by feanil** [comment]
All set!
