### ISSUE TITLE
Please create codecov keys for edx-submissions repository

### ISSUE THREAD

**Issue by pomegranited** [openedx/axim-engineering#1125]
## Firm Name

OpenCraft

## Urgency

Medium (< 2 weeks)

## Requested Change

Please create codecov tokens for https://github.com/openedx/edx-submissions and add the value to the secrets so that CI will pass, cf  https://github.com/openedx/edx-submissions/pull/241

## Reasoning

* We need code coverage reports to ensure code quality on this repository.

**Comment by kdmccormick** [comment]
Hi @pomegranited , can do.

By the way, I think you may have picked "Axim Engineering Task" from the [request board](https://github.com/openedx/axim-engineering/issues/new/choose)? We don't actually get notified when someone creates an issue that way. Choose any of the "Request" options next time, and it'll show up on our on-call board right away 🙂

**Comment by pomegranited** [comment]
Oh thanks @kdmccormick ! I can't remember exactly what options I saw when I created this ticket, but now I can see I should have chosen "GitHub Request - Repository Settings". Thanks for moving this into the queue :)

**Comment by kdmccormick** [comment]
@pomegranited No problem! I added the CODECOV_TOKEN as specified in https://openedx.atlassian.net/wiki/spaces/COMM/pages/3438280709/Adding+Codecov. Hopefully codecov will work on that PR now?

**Comment by kdmccormick** [comment]
On second thought, I might be confused about how codecov is supposed to be configured. I'll come back to this tomorrow.

**Comment by pomegranited** [comment]
Thanks @kdmccormick :) I don't know if it helps, but https://github.com/openedx/completion has the `CODECOV_TOKEN` set up already.

**Comment by kdmccormick** [comment]
@pomegranited I had the secret wrong the first time. Should be all set now, try pushing to your PR :)  If that doesn't work, feel free to reopen this.

**Comment by pomegranited** [comment]
Thank you for your help @kdmccormick ! It's all working now.
