### ISSUE TITLE
[GH Request] Onboard Chelsea Rathbun as Product Manager CC

### ISSUE THREAD

**Issue by sarina** [openedx/axim-engineering#1127]
### Firm Name

Axim

### Urgency

Low (2 weeks)

### Problem/Request

Requesting CC onboarding for Chelsea Rathbun

### Reasoning

https://discuss.openedx.org/t/cc-nomination-for-chelsea-rathbun/12681/7

**Comment by sarina** [comment]
@crathbun428

**Comment by kdmccormick** [comment]
### CC Onboarding Checklist for Axim On-Call
- [ ] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [ ] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [ ] Let CC know that they may be required to take the privacy and a11y courses when they become available.
- [ ] ~Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while). Keep the ticket open with status “Blocked” until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).~ N/A for Axim
- [ ] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [ ] Add them to the [overall CC mailing list](https://groups.google.com/a/axim.org/g/core-contributors/members?pli=1).
- [ ] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [ ] Look up their record in Salesforce and grant them the Core Contributor role.
- [ ] Ensure they are in the openedx GitHub organization and a member of the [openedx-triage](https://github.com/orgs/openedx/teams/openedx-triage)
- [ ] Send Fox a direct message on Slack with the full name and email address of the new CC. (Fox will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). 
- [ ] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

**Comment by kdmccormick** [comment]
Congrats on your well-deserved confirmation as a core contributor @crathbun428 😄 

I've invited you to the [CC onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023) using your Axim email. Let me know if you have any issues accessing that, or if you have an account under a different email. Ping @openedx/axim-oncall here once you've completed the course, and we'll wrap up the remaining steps.

Heads up that there are no Privacy or A11y training courses yet, but if/when those courses do go live, you (and all of us CCs) may need to take them.

**Comment by crathbun428** [comment]
I've got the course! I just need to complete it (will do next week).

**Comment by arbrandes** [comment]
Think we're done here!
