### ISSUE TITLE
Extend "Release Blocker" label to all repos

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/axim-engineering#1129]
Currently, the "Release Blocker" label does not extend to all repos. This means that if a bug ticket is created in a repo like the frontend-app-course-authoring repo and then added to the BTR Project Board, it's not possible to add the blocker label.

**Comment by kdmccormick** [comment]
Will do @jmakowski1123 

By the way, I think you created this by picking "Axim Engineering Task" from the [request board](https://github.com/openedx/axim-engineering/issues/new/). That option doesn't actually notify on-call, so it's easy for us to miss. Choose any of the GitHub Request options next time, and the on-call will get a ping immediately.
