### ISSUE TITLE
Adding new label to all repos

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/axim-engineering#1130]
### Firm Name

Axim

### Urgency

High (< 3 days)

### Problem/Request

Adding a new label = **"needs reviewer assigned"** to all repos. This will help with OSPR triage and providing better visibility to CCs for OSPRs that don't have reviewers, or OSPRs that have reviewers assigned that Tim and Michelle can't remove (e.g. reviewers who have since abandoned the PR or that are no longer responsible for that repo). 

cc: @feanil from our discussion in the Maintenance WG meeting

### Reasoning

The goal is have a filtered view of this label on the [contributions board](https://github.com/orgs/openedx/projects/19/views/1?layout=table&filterQuery=open-source-contribution+&groupedBy%5BcolumnId%5D=Status&visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C4685363%2C4782458%2C%22Labels%22%2C25518352%2C%22Repository%22%5D&sortedBy%5Bdirection%5D=&sortedBy%5BcolumnId%5D=) to get stalled OSPRs and OSPRs in unmaintained repos reviewed.

**Comment by kdmccormick** [comment]
Thanks for the ticket, I'll take care of this today.

**Comment by kdmccormick** [comment]
@mphilbrick211 thanks for you patience, this label should now exist in every repo.
