### ISSUE TITLE
[GH Request] Codecov token for frontend-platform 

### ISSUE THREAD

**Issue by dcoa** [openedx/axim-engineering#1131]
### Firm Name

edunext

### Urgency

Medium (< 2 weeks)

### Requested Change

Please create a codecov token for the repo https://github.com/openedx/frontend-platform  so that the coverage report can be uploaded.

### Reasoning

This change is necessary to upgrade codecov to v4

**Comment by kdmccormick** [comment]
Thanks for the ticket, I'll take care of this today.

**Comment by kdmccormick** [comment]
I added the CODECOV_TOKEN, and opened a PR to use the token: https://github.com/openedx/frontend-platform/pull/692

Hopefully, that will build and successfully invoke codecov.

**Comment by kdmccormick** [comment]
I think I'm confused about how codecov is supposed to be configured. I'll come back to this tomorrow.
