### ISSUE TITLE
[GH Request] Onboard <ADD USERNAMES HERE>

### ISSUE THREAD

**Issue by ibarends-2U** [openedx/axim-engineering#1132]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

ibarends@2u.com

### Start Date

14 May 2024

### Urgency

High (< 3 days)

### Special Requests

I need to adop repos into edx org from GitHub openedX (OCM)

**Comment by brian-smith-tcril** [comment]
@georgebabey it seems this is a self-onboard request. Is this authorized?

**Comment by georgebabey** [comment]
@brian-smith-tcril following up internally

**Comment by ibarends-2U** [comment]
I no longer need access for now
