### ISSUE TITLE
[GH Request] Onboard Awais Qureshi

### ISSUE THREAD

**Issue by awais786** [openedx/axim-engineering#1137]
### Firm Name

Arbisoft

### User List (case sensitive!) - Please also include in ticket title

[awais786](https://github.com/awais786/)

Repos list
https://github.com/openedx/edx-platform
https://github.com/openedx/django-lang-pref-middleware
https://github.com/openedx/edx-organizations

Reasoning
https://discuss.openedx.org/t/core-contributor-nomination-awais-qureshi/12792

### Start Date

14 May 2024

### Urgency

Medium (< 2 weeks)

**Comment by brian-smith-tcril** [comment]
@georgebabey it seems this is a self-onboard request. Is this authorized?

**Comment by awais786** [comment]
@feanil FYI

**Comment by regisb** [comment]
@brian-smith-tcril I'm not sure what you mean by "self-onboard". In case it wasn't clear, this is following Awais' CC nomination: https://discuss.openedx.org/t/core-contributor-nomination-awais-qureshi/12792

**Comment by brian-smith-tcril** [comment]
My mistake! I didn't notice this was a CC onboarding request! Sorry about that.

### CC Onboarding Checklist for Axim On-Call
- [ ] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [ ] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [ ] Let CC know that they may be required to take the privacy and a11y courses when they become available.
- [ ] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while). Keep the ticket open with status “Blocked” until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [ ] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [ ] Add them to the [overall CC mailing list](https://groups.google.com/a/axim.org/g/core-contributors/members?pli=1).
- [ ] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [ ] Look up their record in Salesforce and grant them the Core Contributor role.
- [ ] Ensure they are in the openedx GitHub organization and a member of the [openedx-triage](https://github.com/orgs/openedx/teams/openedx-triage)
- [ ] Send Fox a direct message on Slack with the full name and email address of the new CC. (Fox will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). 
- [ ] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).
### Additional, for Coding Roles Only
- [ ] Add them to the [Google group](https://groups.google.com/a/axim.org/g/core-contributors-dev). This is very low traffic, meant primarily for announcements we want to be sure get to all developers.
- [ ] Add the CC to the `@core-contributor-committers` Slack user group
- [ ] Remind them to add themselves to the relevant shared Slack channel(s) corresponding to their merge accesses (some [additional context](https://docs.google.com/document/d/1-G-v3nrP8RN_j0P8gEsdI0ahdOoJFePiDHFOuPlUjlk/edit#heading=h.wsc5ai1lrvb6) if you’re curious). Here’s a DM you can copy and use: “For the repositories you have merge access to, [please join the Slack room(s) that correspond to your repositories](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit#gid=0). These rooms are where to coordinate timing on merging breaking or major changes. Keep in mind that 2U runs CI/CD off the tip of master branches, so major changes will impact their site first. It's generally OK to announce in these rooms that you are merging a pr with 24 hour or more notice (eg, I'm merging this tomorrow at 1500 UTC), and engage in discussion with anyone who expresses concern. These rooms are also a good place to ask for a 2U review on critical/breaking change PRs before you get to the merging state.”
- [ ] Also add them to the GitHub group [committers](https://github.com/orgs/openedx/teams/committers) teams.
- [ ] Grant write access to the repositories described in the vote. Do not grant it directly to the user; instead, use existing **committers-** teams, making new ones as you need to. [See this page for details](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3555852316/GitHub+Access+Team+Structure#Team-names-and-types).

**Comment by brian-smith-tcril** [comment]
@awais786 I have invited you to the CC Onboarding course using the email on your GitHub profile. Please let me know if you have any issues with that!

**Comment by awais786** [comment]
@brian-smith-tcril I have a question about adding my name here is this [list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Core+Contributors+to+the+Open+edX+Project). Should I add it myself or some one else will do this from openedx ?

**Comment by brian-smith-tcril** [comment]
@awais786 I can add you to that list. I just checked and I see you have completed some but not all of the onboarding course using the email associated with your GitHub account. Earlier you mentioned you had

> also sent the email from personal account

 Did you mean that you had completed the onboarding course using another account?

**Comment by awais786** [comment]
yes, I have completed the course.

**Comment by sarina** [comment]
@brian-smith-tcril Awais has signed the Core Contributor agreement.
