### ISSUE TITLE
[GH Request] Brian Smith expansion rights to edx-platform

### ISSUE THREAD

**Issue by sarina** [openedx/axim-engineering#1139]
### Firm Name

Axim

### Urgency

Low (2 weeks)

### Requested Change

@brian-smith-tcril added to edx-platform as a CC

### Reasoning

https://discuss.openedx.org/t/cc-rights-expansion-brian-smith-edx-platform/12937

**Comment by brian-smith-tcril** [comment]
@sarina it seems https://github.com/orgs/openedx/teams/committers-frontend/repositories already includes `edx-platform`

**Comment by sarina** [comment]
That... is probably not right 😬
