### ISSUE TITLE
[GH Request] Onboard sburns

### ISSUE THREAD

**Issue by saraburns1** [openedx/axim-engineering#1142]
### Firm Name

Axim

### User List (case sensitive!) - Please also include in ticket title

Sara Burns, saraburns1

### Start Date

17 May 2024

### Urgency

Medium (< 2 weeks)

**Comment by sarina** [comment]
- Add to triage in this org
- Add as member of the Axim private org
- Add confluence user to Axim group (I think we have one?)
- Add Slack user to relevant rooms and teams (I think I did this already but a double-check wouldn't hurt)
- Any other access that you can think of (and note here, so we can capture for next onboarding)

**Comment by saraburns1** [comment]
@brian-smith-tcril - sorry about that, updated!
