### ISSUE TITLE
[GH Request] Codecov token for frontend-build

### ISSUE THREAD

**Issue by dcoa** [openedx/axim-engineering#1148]
### Firm Name

edunext

### Urgency

Medium (< 2 weeks)

### Requested Change

Requested Change
Please create a codecov token for the repo https://github.com/openedx/frontend-build so that the coverage report can be uploaded.

### Reasoning

This change is necessary to upgrade codecov to v4

**Comment by brian-smith-tcril** [comment]
Token added, tested and working in https://github.com/openedx/frontend-build/pull/548
