### ISSUE TITLE
[GH Request] Onboard DonatoBD

### ISSUE THREAD

**Issue by DonatoBD** [openedx/axim-engineering#1150]
### Firm Name

edunext

### User List (case sensitive!) - Please also include in ticket title

Jose Donato Bracuto Delgado, @DonatoBD

### User Squad

BTR - bug triager

### Start Date

30 May 2024

### Urgency

High (< 3 days)

### Special Requests

It would be ideal to have the permissions to be able to assign issues and modify tags on the [btr board](https://github.com/orgs/openedx/projects/28/views/16?sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=111811488) and thus fulfill the bug triager tasks during the redwood release without depending on other colleagues :smile:

**Comment by bmtcril** [comment]
Welcome! I've sent you an invite which should grant triage team access, let me know if you run into any issues with permissions after accepting it.

**Comment by DonatoBD** [comment]
Hi @bmtcril !   I just checked and now I have all the permissions I need, thank you very much 😊
