### ISSUE TITLE
[GH Request] Changes in openedx-wordpress-ecommerce

### ISSUE THREAD

**Issue by MaferMazu** [openedx/axim-engineering#1153]
### Repository

openedx-wordpress-ecommerce

### Urgency

Low (2 weeks)

### Requested Change

I would like you to help me remove the PR reviews dismissed with the changes. I believe this option is not enabled in other repos, such as edx-platform, and it makes the reviewers have to review again.

Note: if you have to leave the option for some reason, there is no problem.

Another thing I would like to change is the repository's About link. It currently has an old documentation link, and it would be good to put the correct link.
The correct link: https://docs.openedx.org/projects/wordpress-ecommerce-plugin/en/latest/index.html

![Screenshot from 2024-06-07 17-29-02](https://github.com/openedx/axim-engineering/assets/35668326/2919769e-4276-497b-83ba-0735d87de24e)

### Reasoning

The first one is to avoid reviewers making a review again.

And the second one is to have consistent information.

**Comment by bmtcril** [comment]
Both changes should be done, let me know if you run into any issues!

**Comment by MaferMazu** [comment]
That was quick. Thanks @bmtcril 🙌
