### ISSUE TITLE
[GH Request] Onboard Prashant Makwana (pmakwana93)

### ISSUE THREAD

**Issue by bcitro** [openedx/axim-engineering#1157]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Prashant Makwana, pmakwana93

### User Squad

Enterprise Quokkas

### Start Date

10 June 2024

### Urgency

High (< 3 days)

### Special Requests

Please add Prashant to the [enterprise-quokkas](https://github.com/orgs/openedx/teams/enterprise-quokkas) team as well, thanks!

**Comment by arbrandes** [comment]
Done!
