### ISSUE TITLE
[GH Request] Core Contributor rights expansion & maintainership

### ISSUE THREAD

**Issue by gabor-boros** [openedx/axim-engineering#1158]
### Firm Name

OpenCraft

### Urgency

Low (2 weeks)

### Requested Change

Please add `gabor-boros` user (me) as a maintainer to the edx-rest-api-client and edx-drf-extensions repositories.

### Reasoning

https://discuss.openedx.org/t/core-contributor-rights-expansion-maintainership-gabor-boros/12726

**Comment by bmtcril** [comment]
Hi there, you should be all set. Let me know if you run into any issues!

**Comment by gabor-boros** [comment]
Thank you, @bmtcril! I'm going to check it out soon.
