### ISSUE TITLE
[GH Request] Onboard Andrei-V-Z

### ISSUE THREAD

**Issue by dkim2u** [openedx/axim-engineering#1160]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Andrei Zhukavets Andrei-V-Z

### Start Date

10 June 2024

### Urgency

Low (2 weeks)

### Special Requests

Any questions regarding access can be directed to their manager, Alex Trepca

**Comment by arbrandes** [comment]
I've invited Andrei-V-Z to the openedx org with triage access.  If additional permissions are required, please reopen this ticket and let us know.
