### ISSUE TITLE
[GH Request] Onboard @PKulkoRaccoonGang

### ISSUE THREAD

**Issue by PKulkoRaccoonGang** [openedx/axim-engineering#1163]
### Firm Name

Raccoon Gang

### User List (case sensitive!) - Please also include in ticket title

Peter Kulko, @PKulkoRaccoonGang

### Start Date

21 June 2024

### Urgency

Low (2 weeks)

### Special Requests

Requesting CC access for Peter Kulko with gh username @PKulkoRaccoonGang to repo:
- https://github.com/openedx/paragon

Reason:
- https://discuss.openedx.org/t/core-contributor-nomination-peter-kulko/13058

Instructions: Please give access to https://github.com/openedx/paragon

**Comment by arbrandes** [comment]
Waiting on Peter's email in order to invite him to the course.  (Sent a DM on Slack.)

**Comment by PKulkoRaccoonGang** [comment]
Hi @arbrandes
To finish the course I have:
- get access to the [Paragon](https://github.com/openedx/paragon) repository
- ensure that information about me appears on [the Core Contributor wiki page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Core+Contributors+to+the+Open+edX+Project)
- get an invitation to [Listaflow](https://listaflow.com/)

**Comment by sarina** [comment]
Peter's documents have been signed!

**Comment by sarina** [comment]
Hi @PKulkoRaccoonGang I have fully onboarded you! I sent a few Slack messages that will be sent in a few hours, so please be mindful of those.

**Comment by PKulkoRaccoonGang** [comment]
Hi @sarina I think I still don't have rights to the Paragon repository

**Comment by sarina** [comment]
Sorry! I forgot to grant "write". Could you please check again?

**Comment by PKulkoRaccoonGang** [comment]
@sarina Thanks! Everything is great 💯
