### ISSUE TITLE
[GH Request] Onboard Apgomeznext

### ISSUE THREAD

**Issue by felipemontoya** [openedx/axim-engineering#1167]
### Firm Name

edunext

### User List (case sensitive!) - Please also include in ticket title

* Ana Paula Gomez (@apgomeznext) ana.gomez@edunext.co

### Start Date

18 Jun 2024

### Urgency

Low (2 weeks)

### Special Requests

Ana is working in the documentation of aspects and requires access to the triage group

**Comment by bmtcril** [comment]
I can see her in Salesforce and have sent a github invite, should be all set. Thanks @felipemontoya !
