### ISSUE TITLE
[GH Request] Additional merge rights for bradenmacdonald

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/axim-engineering#1170]
### Firm Name

OpenCraft

### Urgency

Low (2 weeks)

### Requested Change

As agreed via https://discuss.openedx.org/t/core-contributor-rights-expansion-braden-macdonald/13195 I would like to get commit rights for https://github.com/openedx/frontend-app-course-authoring/

### Reasoning

In order to review and merge PRs! Also being able to edit issues that others have created would be very helpful for the ongoing Libraries Relaunch work, which we're organizing using GitHub issues on that repo.

**Comment by arbrandes** [comment]
Done!  Apologies for the delay!

**Comment by bradenmacdonald** [comment]
Thanks!
