### ISSUE TITLE
[GH Request] Remove devstack from readthedocs

### ISSUE THREAD

**Issue by robrap** [openedx/axim-engineering#1173]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

The docs at https://edx.readthedocs.io/projects/open-edx-devstack are out-of-date (from one perspective), because the openedx-unsupported/devstack repo has been archived, but 2U is still maintaining a fork. I'm wondering if we could kill this RTD project if you no longer need it? We could also forward to 2U's, but we don't yet have docs published anywhere.

### Reasoning

Leads to confusion.

**Comment by sarina** [comment]
@robrap I'm of two minds. I think for newcomers, these docs should not be findable, or - if they are - they should clearly state it's unsupported. However, we have many in our community on older releases who may need references to devstack. I'm not sure what to do. @feanil is out but would be good to have him weigh in.

**Comment by feanil** [comment]
I think leaving the docs up but having a banner saying that it's no longer supported is probably the best choice.  I agree with Sarina that people may still want to reference the docs if they're running on old code and still using Devstack for development.

**Comment by robrap** [comment]
Just wondering whether or not you'd allow interested orgs to get a link added to the banner. For example:
- See Org 1's devstack fork docs.
- See 2U's devstack fork docs.
Note: I'm not sure where the banner would be configured, and if you need to unarchive devstack to configure this banner, or if it will be simpler to edit as-needed.

**Comment by sarina** [comment]
I don't know how to do banners in RTD. @feanil do you? If not I can look into it in the following weeks.

**Comment by sarina** [comment]
@robrap I don't mind adding links for forked docs

**Comment by feanil** [comment]
You can do the banner like this: https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/announcements.html#announcement-banners

**Comment by robrap** [comment]
Thanks @sarina. We haven't found a way to publish the docs ourselves yet, and haven't even had time to update the README. If you added a link for docs for the 2U fork, you could add it to https://github.com/edx/devstack/blob/master/README.rst.

**Comment by sarina** [comment]
Thanks @feanil - to add the banner I'll need to update https://github.com/openedx-unsupported/devstack, correct? Is the right way to go to unarchive it, make the changes, then archive it again?

**Comment by sarina** [comment]
@robrap when you say you `haven't even had time to update the README`, do you mean the README on the main devstack repo? If I'm going to end up unarchiving it, now would be the time to indicate how you'd like the README updated.

**Comment by feanil** [comment]
> Thanks @feanil - to add the banner I'll need to update https://github.com/openedx-unsupported/devstack, correct? Is the right way to go to unarchive it, make the changes, then archive it again?

Yea, you can unarchive, update and then I would suggest waiting for the publish to occur before you archive to make sure it took.  Feel free to ping me if you run into issues.  The build logs can be found here if you run into issues: https://readthedocs.org/projects/open-edx-devstack/builds/
