### ISSUE TITLE
[GH Request]  Update Read the Docs for Redwood

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/axim-engineering#1175]
### Firm Name

BTR WG

### Urgency

High (< 3 days)

### Problem/Request

We cut the open-release/redwood.1 tag and need someone from Axim to perform [Step 4a from the "Process to create an Open edX Release" page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#4a.-Ask-Axim-to-un-hide-the-release-versions-of-each-book) (pointing Read the Docs to the new version).

### Reasoning

Following documented steps at the https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release after cutting a new release tag.

**Comment by ormsbee** [comment]
I've made the changes, though the one for the roots doc site (docs.openedx.org) isn't showing up properly. I'm thinking that maybe that's just a CDN caching issue, so I'll wait until I verify it's showing the redwood release before marking this ticket as completed.

The following repos hadn't been updated to show Palm or Quince:

* https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/
* https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/
* https://edx.readthedocs.io/projects/open-edx-learner-guide/en/latest/

They are now set to show Redwood, Quince, Palm, and Olive.

**Comment by ormsbee** [comment]
Done thanks to @feanil for getting the build working again. 😄
