### ISSUE TITLE
[GH Request] Create frontend-base repository

### ISSUE THREAD

**Issue by davidjoy** [openedx/axim-engineering#1176]
### Firm Name

Joy Engineering

### Urgency

Medium (< 2 weeks)

### Problem/Request

As part of FC-0058 we need to create a new repository called 'frontend-base' in the openedx org.  

### Reasoning

This repo will be a successor to frontend-build, frontend-platform, frontend-plugin-framework, frontend-component-header, frontend-component-footer, and eslint-config.  We need it to get started with the FC-0058 work.

**Comment by sarina** [comment]
https://github.com/openedx/frontend-base
