### ISSUE TITLE
[GH Request] Grant write access to Dcoa on frontend-build

### ISSUE THREAD

**Issue by felipemontoya** [openedx/axim-engineering#1179]
### Firm Name

edunext

### Urgency

Low (2 weeks)

### Requested Change

Grant the user @dcoa write access (or the appropiate for a maintainer) to https://github.com/openedx/frontend-build

### Reasoning

She was voted in as a CC and maintainer in https://discuss.openedx.org/t/core-contributor-nomination-diana-olarte/12527 and she is in https://github.com/orgs/openedx/teams/committers-frontend-build but the permissions seem to not be working.

**Comment by felipemontoya** [comment]
@dcoa you can put more info here if you need.

**Comment by sarina** [comment]
Weird, `frontend-build` was not in the https://github.com/orgs/openedx/teams/committers-frontend-build/repositories team - I've added it.

Closing this but @dcoa please let me know if you need anything else.
