### ISSUE TITLE
[GH Request] Get admin access for config file update in `frontend-app-ora`

### ISSUE THREAD

**Issue by Rodra** [openedx/axim-engineering#1185]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

I need admin access for myself (Rodrigo Martin ([rmartin3@2u.com](mailto:rmartin3@2u.com))) so that I can perform some modifications in this file https://github.com/openedx/frontend-app-ora/blob/master/Makefile to create translations using ATLAS for this repo.

### Reasoning

Set up Atlas, to improve localization of LMS [ORA](https://github.com/edx/edx-internal/blob/fc59bb563c23d271a01b5f597a5da45c6250c883/gocd/generated-pipelines/frontend-generator-inputs.yaml#L194)

Many translations in some repos will be going away in the next few weeks. We are making sure our MFEs has the `@edx/openedx-atlas` dependency and uses atlas as part of `make pull_translations` (this has been done for many repos already).

**Comment by sarina** [comment]
Hi @Rodra - only Axim has access to repos.

Could you make the modifications to the Makefile in a pull request and tag @brian-smith-tcril who will be able to help with any needed admin modifications.

**Comment by Rodra** [comment]
PR https://github.com/openedx/frontend-app-ora/pull/225

**Comment by sarina** [comment]
Closing this request as the PR has been made. Brian is at the Open edX conference so his responses may be delayed.
