### ISSUE TITLE
[GH Request] Onboard <NoyanAziz>

### ISSUE THREAD

**Issue by hmccauley** [openedx/axim-engineering#1186]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Noyan Aziz, NoyanAziz, naziz1@2u.com

### Start Date

2 July 2024

### Urgency

High (< 3 days)

### Special Requests

user requesting to be added to the "revenue-squad" team as well - thank you!

**Comment by sarina** [comment]
@colinbrash can you please confirm @NoyanAziz is a new member of revenue-squad?

**Comment by sarina** [comment]
Sent an invite to @NoyanAziz - please check your email.
Addition to revenue-squad is awaiting Colin's response.

**Comment by colinbrash** [comment]
@sarina confirmed, he is a new member of this team.  Thanks!

**Comment by sarina** [comment]
@colinbrash of course! Done on my end, please open a new ticket if anything else is needed.
