### ISSUE TITLE
[GH Request] <Provide access to the openedx-website repo>

### ISSUE THREAD

**Issue by ehuthmacher** [openedx/axim-engineering#1210]
### Firm Name

Axim

### Urgency

Medium (< 2 weeks)

### Requested Change

Please add the following users to the  openedx-website repo: 

adelkth
nadheembl
Abdulahadtp

### Reasoning

We are working with the Blend-Ed team to redesign the Open edX website.

**Comment by sarina** [comment]
I've sent them the invite. They'll be receiving an email shortly. They can also visit https://github.com/openedx to accept the invitation, which they need to do within 7 days.

If you need an invite resent after 7 days, or need to onboard new team members, don't hesitate to make a new ticket!
