### ISSUE TITLE
[GH Request] Ability to add members to 2u-phoenix and course-discovery-maintainers teams

### ISSUE THREAD

**Issue by DawoudSheraz** [openedx/axim-engineering#1216]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Hello,
My team in 2U is responsible for managing course-discovery repository. We also manage some other repos like edx-val and publisher. We have two Github teams in openedx

- https://github.com/orgs/openedx/teams/2u-phoenix
- https://github.com/orgs/openedx/teams/course-discovery-maintainers

Being the lead/EM for the team, I need the ability to add/remove members from the team. We have a new member onboarded who also needs to be added to those teams.

### Reasoning

Our previous lead/manager, Kashif Chaudhry, offboarded from 2U. He had the said permissions.

**Comment by arbrandes** [comment]
Hi @DawoudSheraz!  It's now org policy that only Axim can manage team membership when repository write access to repositories is involved.  When you need people added or removed to those teams, please open a GH Request issue with the user-specific info.
