### ISSUE TITLE
[GH Request] Add Hamza Shafique to GitHub teams

### ISSUE THREAD

**Issue by DawoudSheraz** [openedx/axim-engineering#1218]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Please add Hamza Shafique (https://github.com/hamza-56) to the following teams:

- https://github.com/orgs/openedx/teams/2u-phoenix
- https://github.com/orgs/openedx/teams/course-discovery-maintainers

### Reasoning

Hamza is a new addition to edX - Marketplace - Inspire team. As owner and maintainer of course-discovery and a few other repos, Hamza needs to be added to these teams so that he has the appropriate access. Thanks

**Comment by arbrandes** [comment]
Done!
