### ISSUE TITLE
[GH Request] <ADD harrisonlc12 to https://github.com/orgs/openedx/projects/68>

### ISSUE THREAD

**Issue by ehuthmacher** [openedx/axim-engineering#1221]
### Firm Name

Axim

### Urgency

High (< 3 days)

### Requested Change

Please add harrisonlc12 tothe following board,  https://github.com/orgs/openedx/projects/68

### Reasoning

Assisting with tickets

**Comment by arbrandes** [comment]
Invited @harrisonlc12 to the org as a member of https://github.com/orgs/openedx/teams/edunext-website.
