### ISSUE TITLE
[GH Request] please remove required check on license-manager repo

### ISSUE THREAD

**Issue by macdiesel** [openedx/axim-engineering#1225]
### Firm Name

2u

### Urgency

Medium (< 2 weeks)

### Requested Change

In the license manager repo: https://github.com/openedx/license-manager/ please remove required CI check: check migration for MySql8 (ubuntu-20.04, 3.8) 

### Reasoning

There is a required CI check for: "check migration for MySql8 (ubuntu-20.04, 3.8) ". However in this PR we drop python 3.8 support: https://github.com/openedx/license-manager/pull/655. We can not merge the python 3.12 PR and other dependencies until this required check is removed.

**Comment by kdmccormick** [comment]
Should be all set. Let me know if you want any of the Py3.12 checks to be marked as required.

**Comment by macdiesel** [comment]
Thank you Sir!
