### ISSUE TITLE
[GH Request] Github runners not picking up jobs

### ISSUE THREAD

**Issue by bmtcril** [openedx/axim-engineering#1226]
### Firm Name

Axim

### Urgency

High (< 3 days)

### Problem/Request

Github runners seem unavailable for most jobs. Github is not reporting any issues, our org is showing 0 runners in use. This is happening in at least 3 repos, so seems org wide.

Logs for things like commitlint look like:

```
Requested labels: ubuntu-20.04
Job defined at: openedx/.github/.github/workflows/commitlint.yml@refs/heads/master
Reusable workflow chain:
openedx/xapi-db-load/.github/workflows/commitlint.yml@refs/pull/118/merge (d6d3143615a9b2391879f892aae3fc287030b2cd)
-> openedx/.github/.github/workflows/commitlint.yml@refs/heads/master (4cd16d7b750f2699a99dd6a85c264453d396d238)
Waiting for a runner to pick up this job...
```

Examples:

https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1136
https://github.com/openedx/xapi-db-load/pull/118
https://github.com/openedx/edx-platform/pull/35206

### Reasoning

Should be obvious. :) I'm looking into this currently, but could use more eyes.

**Comment by kdmccormick** [comment]
There was an incident earlier today involving degraded hosted actions runners, but it marked as resolved: https://www.githubstatus.com/incidents/y0gqch2dhw5l

Still, no running jobs: https://github.com/organizations/openedx/settings/actions/hosted-runners

**Comment by bmtcril** [comment]
I saw that, but I don't believe we're using large runners so didn't think it applied. The later [redis issue](https://www.githubstatus.com/incidents/dy0rbtrxtwlh) also impacted actions but was supposedly fixed 5 hrs ago.

**Comment by kdmccormick** [comment]
And just like that, looks like jobs are getting processed again: https://github.com/organizations/openedx/settings/actions/hosted-runners

We've got like 14 pages of queued jobs just for edx-platform, so it'll take some time to catch up, but I think we're good now.
