### ISSUE TITLE
[GH Request] Onboard dandcproctor

### ISSUE THREAD

**Issue by AmiraQuick** [openedx/axim-engineering#1238]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

David Proctor, @ dandcproctor

### Start Date

3 September 2024

### Urgency

Medium (< 2 weeks)

**Comment by kdmccormick** [comment]
@AmiraQuick What team is dandcproctor part of? Here are the 2U teams we have listed in our system: https://github.com/orgs/openedx/teams?query=2u-

**Comment by kdmccormick** [comment]
@AmiraQuick , please let me know what team dandcproctor should be part of, otherwise I will need to close this request.

**Comment by kdmccormick** [comment]
If this is still relevant, please open a new request and include mention of which team the employee is part of. Thanks!
