### ISSUE TITLE
[GH Request] Onboard saraburns1

### ISSUE THREAD

**Issue by saraburns1** [openedx/axim-engineering#1240]
### Firm Name

Axim

### User List (case sensitive!) - Please also include in ticket title

Sara Burns saraburns1

### Start Date

30 Aug 2024

### Urgency

Low (2 weeks)

### Special Requests

Requesting CC access for Sara Burns with gh username saraburns1 to repos 
aspects-dbt
event-bus-redis
openedx-aspects
platform-plugin-aspects
tutor-contrib-aspects
xapi-db-load

Reason: https://discuss.openedx.org/t/cc-nomination-sara-burns/13689

**Comment by brian-smith-tcril** [comment]
I have invited @saraburns1 to the `committers-analytics` team.

**Comment by kdmccormick** [comment]
Thanks @brian-smith-tcril !

**Comment by saraburns1** [comment]
Thank you!
