### ISSUE TITLE
[GH Request] Archive frontend-lib-content-components

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/axim-engineering#1241]
### Repository

axim-engineering

### Urgency

Low (2 weeks)

### Requested Change

Please merge https://github.com/openedx/frontend-lib-content-components/pull/506 and then archive that repository, as its code has been merged into the course-authoring MFE repo.

### Reasoning

See https://github.com/openedx/frontend-app-course-authoring/pull/1208 for details.

**Comment by kdmccormick** [comment]
I pushed one last `feat!` commit in hopes that it'll trigger a release to NPM

**Comment by kdmccormick** [comment]
Done!

**Comment by bradenmacdonald** [comment]
Thanks!
