### ISSUE TITLE
[GH Request] Onboard @cmltaWt0 <Max Sokolski>

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/axim-engineering#1242]
### Firm Name

Raccoon Gang

### User List (case sensitive!) - Please also include in ticket title

* Max Sokolski @cmltaWt0 

### Start Date

09 September 2024

### Urgency

Low (2 weeks)

### Special Requests

Requesting CC extension for @cmltaWt0 (Max Sokolski) to [cypress-e2e-tests](https://github.com/openedx/cypress-e2e-tests) repo as long as Maintainer rights/responsibilities.
Reason: https://discuss.openedx.org/t/core-contributor-rights-expansion-maintainership-max-sokolski/13666
Instructions: Please give access to https://github.com/openedx/cypress-e2e-tests

**Comment by brian-smith-tcril** [comment]
@cmltaWt0 I have created a new `committers-cypress-e2e-tests` team, given that team `write` access to the `cypress-e2e-tests` repo, and added you as a member of that team.

This should grant you the appropriate permissions, so I am going to close out this issue. If you encounter any permissions issues please let me know and I'll be happy to reopen it and look into them!
