### ISSUE TITLE
[GH Request] Grant edit rights to the Confluence site

### ISSUE THREAD

**Issue by VineetManuja** [openedx/axim-engineering#1245]
### Firm Name

TitanEd

### Urgency

High (< 3 days)

### Problem/Request

Need edit access to https://openedx.atlassian.net/wiki/spaces

### Reasoning

I am one of the facilitators of the new Working Group - Biz Dev, and need access to create, edit, and moderate activities on the WG pages. It is urgent as the WG activities have commenced and I need to send updates, including meeting minutes and notes.

**Comment by brian-smith-tcril** [comment]
I'm more than happy to help you with this, but I'm not sure I understand this request fully. It's not clear what access you're missing. Examples would be incredibly helpful for my understanding here. Do you have any examples of things you've tried to do on the wiki that haven't worked?

Thanks!

**Comment by VineetManuja** [comment]
Hi Brian, I am the facilitator of the new Biz Dev WG - BizDev Working Group - Open edX Community - Open edX Community Wiki (atlassian.net)<https://openedx.atlassian.net/wiki/spaces/COMM/pages/4404543516/BizDev+Working+Group>, and need edit rights to its hosted Wiki pages and other associated pages on Confluence.

I can view the pages, but cannot edit.

This is what I see on the top right section

***@***.***

If I click on the 'sign-in' icon (top right), it redirects me back to the same page.

Hope it clarifies.

**Comment by VineetManuja** [comment]
Let me know if you need additional information about this request. I can really use the access as there's quite a lot of edits that are pending for me to make on Confluence.

**Comment by brian-smith-tcril** [comment]
I'm still unsure what is happening with your user account. I do not see you on the list of users or in the pending requests section in Confluence (I searched for both "Vineet" and "Manuja"). I am also unable to use the "invite users" functionality without having an email address to send the invite to. Feel free to message me on Slack if you'd prefer not to share the email address I should search for/send an invite to on a public GitHub issue.

**Comment by VineetManuja** [comment]
I just messaged you on Slack, Brian. Thank you.
