### ISSUE TITLE
[GH Request] Remove required checks from auth-backends and edx-django-utils

### ISSUE THREAD

**Issue by huniafatima-arbi** [openedx/axim-engineering#1247]
### Repository

auth-backends, edx-django-utils

### Urgency

Medium (< 2 weeks)

### Requested Change

Need to remove required checks of py38 from `auth-backends` and `edx-django-utils` repo in order to merge Python 3.8 support DEPR PRs. PR links are mentioned below

- https://github.com/openedx/auth-backends/pull/333
- https://github.com/openedx/edx-django-utils/pull/441

### Reasoning

We are dropping the support of Python 3.8 as Python 3.8 end of life is Oct 2204. We need to upgrade to Python 3.12 before that to avoid breaking anything.

**Comment by brian-smith-tcril** [comment]
@huniafatima-arbi I have removed the required checks and I have a question. On `auth-backends` I see both 3.11 and 3.12 tests in CI now - which should I add required checks for? Both? Just 3.12?

**Comment by huniafatima-arbi** [comment]
@brian-smith-tcril we will be adding the required checks for just 3.12.

**Comment by brian-smith-tcril** [comment]
I've added the required checks for `3.12` on `auth-backends`. Please let me know if you run into any issues or if there's anything I missed and I can reopen this!
