### ISSUE TITLE
[GH Request] Onboard <mfarhan943>

### ISSUE THREAD

**Issue by dkim-2u** [openedx/axim-engineering#1249]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Muhammad Farhan mfarhan943

### User Squad

arbisoft

### Start Date

11 September 2024

### Urgency

Low (2 weeks)

### Special Requests

New arbisoft contractor reporting to jeremy ristau, please direct any access questions to jeremy, thank you!

**Comment by brian-smith-tcril** [comment]
I have invited @mfarhan943 to the `openedx` GitHub org as well as the `openedx-triage` team, and added an entry in the CLA database.

Please let me know if you have any issues!
