### ISSUE TITLE
[GH Request] Update everything to 2u-infinity and repositories access

### ISSUE THREAD

**Issue by sundasnoreen12** [openedx/axim-engineering#1253]
### Firm Name

2u-infinity

### Urgency

Low (2 weeks)

### Requested Change

Hi Team,

We currently have two groups, edx-infinity and 2u-infinity, listed in the [maintainers spreadsheet](https://docs.google.com/spreadsheets/d/1rMwbRldYwp-xPsAG2vijqwB__9M7P2AgjDxX31G7ucA/edit?gid=0#gid=0), but we would like to update the references to 2u-infinity across the board.

Additionally, the 2U-Infinity team would like to add the following repositories to our team on GitHub at the provided [link](https://github.com/orgs/openedx/teams/2u-infinity/repositories), so we can be included in the reviewers list for these repositories:

- frontend-app-discussions
- frontend-app-profile
- frontend-app-account
- frontend-app-authn

### Reasoning

We are requesting this change to ensure that our team is included in the reviewers list for the aforementioned repositories, enabling us to participate in the review process effectively.

**Comment by sundasnoreen12** [comment]
Hi team,

We are currently facing this issue, and I’m sharing it for your reference.

![Screenshot 2024-09-10 at 4 34 52 PM](https://github.com/user-attachments/assets/9f6590b6-ba45-4132-a852-1583af28dcbb)

**Comment by sundasnoreen12** [comment]
Hi, @brian-smith-tcril , any updates on this?

**Comment by brian-smith-tcril** [comment]
I have given `2u-infinity` write permissions on the listed repositories.

I also noticed that the `edx-infinity` team still exists, but does not have any associated permissions. Does anything need to be done before that team can be removed from the org?

**Comment by asadazam93** [comment]
@brian-smith-tcril the edx-infinity team is safe to remove.

**Comment by sarina** [comment]
Is there work remaining on this issue?

**Comment by brian-smith-tcril** [comment]
As of 5 minutes ago I have deleted the `edx-infinity` team from the GH org. This is now complete.
