### ISSUE TITLE
[GH Request] <Please re-create the Translation, Marketing, and BizDev Working Group Meetings, using Mr. Meeting as the owner>

### ISSUE THREAD

**Issue by ehuthmacher** [openedx/axim-engineering#1255]
### Firm Name

Axim

### Urgency

Low (2 weeks)

### Requested Change

Translation Working Group Meeting, occurs on every third Wed of the month at 9 AM (EDT) via Google Handout. Co-hosts should be Brian Smith (Axim) and Ghassan Maslamani (ghassan.maslamani@gmail.com )

Marketing Working Group Meeting, occurs on every third Wed of the month at 10 AM (EDT) via Google Handout. Co-host should be Nicole Kessler (nicole.kessler@abstract-technology.de )

BizDev Working Group Meeting, occurs on every 4th Wed of the month at 9 AM (EDT) via Google Handout. Co-hosts should be Stefania Trabucchi (stefania.trabucchi@abstract-technology.de) and Vineet Manuja (VineetM@TitanEd.com) 

### Reasoning

Streamlined approach to record WG meetings, based on https://openedx.atlassian.net/wiki/spaces/~618bf0adcc2d7c00717a67d8/pages/4428496908/Open+edX+Meeting+Configuration

**Comment by e0d** [comment]
@brian-smith-tcril I'll work with @ehuthmacher on this.  Will assign to me.

**Comment by e0d** [comment]
@ehuthmacher I've updated ownership of the Marketing Working Group.  I've added yourself and Nichole as co-hosts, but I've used Nichole's gmail address.  If it's better to use the Abstract account, let me know and I can change it.  The event was using a MS Teams meeting, so folks will need to update their links.

**Comment by ehuthmacher** [comment]
Ok, no problem. Did it generate a new Google Meets link that we can use?

**Comment by e0d** [comment]
Yes, the link is in the invite.

**Comment by ehuthmacher** [comment]
So, people will automatically receive the updated link; no need for us to notify or change anything among attendees, correct?

**Comment by e0d** [comment]
People should make sure they haven't copied the event to their calendar rather than subscribing to the version is will update automatically.  Otherwise all should be good.
