### ISSUE TITLE
[GH Request] Add master branch merge rights for committers-cookie-policy-banner

### ISSUE THREAD

**Issue by GlugovGrGlib** [openedx/axim-engineering#1256]
### Firm Name

Raccoon Gang

### Urgency

Medium (< 2 weeks)

### Requested Change

Allow merge to master branch for the group https://github.com/orgs/openedx/teams/committers-cookie-policy-banner in the repository https://github.com/openedx/frontend-component-cookie-policy-banner.

### Reasoning

Group https://github.com/orgs/openedx/teams/committers-cookie-policy-banner was created and granted write access to https://github.com/openedx/frontend-component-cookie-policy-banner in https://github.com/openedx/axim-engineering/issues/1147, but there's no merge rights to master, group require it to continue maintenance of the repository as per nomination https://discuss.openedx.org/t/cc-rights-expansion-to-enable-raccoongang-to-maintain-frontend-component-cookie-policy-banner/10828

AR:
<img width="996" alt="image" src="https://github.com/user-attachments/assets/89c031db-716b-44f0-a452-8d8af159c025">

**Comment by brian-smith-tcril** [comment]
Looks like there was a branch protection rule "Restrict who can push to matching branches" set to a legacy 2u team. I've removed that rule from the branch protections.
