### ISSUE TITLE
[GH Request] Onboard CodeWithEmad

### ISSUE THREAD

**Issue by CodeWithEmad** [openedx/axim-engineering#1257]
### Firm Name

edSPIRIT

### User List (case sensitive!) - Please also include in ticket title

Emad Rad, CodeWithEmad

### Start Date

16 Sep 2024

### Urgency

Low (2 weeks)

### Special Requests

Requesting CC access and maintainership for Emad Rad with gh username codewithemad to repos
https://github.com/openedx/openedx-chem
https://github.com/openedx/frontend-app-ora-grading
https://github.com/openedx/olxcleaner
https://github.com/openedx/acid-block

Reason: https://discuss.openedx.org/t/core-contributor-nomination-emad-rad/13697

**Comment by bmtcril** [comment]
### CC Onboarding Checklist for Axim On-Call
- [ ] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [ ] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [ ] Let CC know that they may be required to take the privacy and a11y courses when they become available.
- [ ] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while). Keep the ticket open with status “Blocked” until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [ ] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [ ] Add them to the [overall CC mailing list](https://groups.google.com/a/axim.org/g/core-contributors/members?pli=1).
- [ ] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [ ] Look up their record in Salesforce and grant them the Core Contributor role.
- [ ] Ensure they are in the openedx GitHub organization and a member of the [openedx-triage](https://github.com/orgs/openedx/teams/openedx-triage)
- [ ] Send Fox a direct message on Slack with the full name and email address of the new CC. (Fox will contact the new CC explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). 
- [ ] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

### Additional, for Coding Roles Only
- [ ] Add them to the [Google group](https://groups.google.com/a/axim.org/g/core-contributors-dev). This is very low traffic, meant primarily for announcements we want to be sure get to all developers.
- [ ] Add the CC to the `@core-contributor-committers` Slack user group
- [ ] Remind them to add themselves to the relevant shared Slack channel(s) corresponding to their merge accesses (some [additional context](https://docs.google.com/document/d/1-G-v3nrP8RN_j0P8gEsdI0ahdOoJFePiDHFOuPlUjlk/edit#heading=h.wsc5ai1lrvb6) if you’re curious). Here’s a DM you can copy and use: “For the repositories you have merge access to, [please join the Slack room(s) that correspond to your repositories](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit#gid=0). These rooms are where to coordinate timing on merging breaking or major changes. Keep in mind that 2U runs CI/CD off the tip of master branches, so major changes will impact their site first. It's generally OK to announce in these rooms that you are merging a pr with 24 hour or more notice (eg, I'm merging this tomorrow at 1500 UTC), and engage in discussion with anyone who expresses concern. These rooms are also a good place to ask for a 2U review on critical/breaking change PRs before you get to the merging state.”
- [ ] Also add them to the GitHub group [committers](https://github.com/orgs/openedx/teams/committers) teams.
- [ ] Grant write access to the repositories described in the vote. Do not grant it directly to the user; instead, use existing **committers-** teams, making new ones as you need to. [See this page for details](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3555852316/GitHub+Access+Team+Structure#Team-names-and-types).

**Comment by bmtcril** [comment]
Hi @CodeWithEmad , congratulations and welcome! I've invited you to the CC course at your edspirit.com email address. Please let me know that you're able to get into the course. As new trainings become available for things like accessibility and privacy you may be required to take additional trainings as well.

Once I have confirmation that you have signed the Core Contributor agreement I'll be able to finish the rest of the onboarding steps for you. Please let me know if you have any questions!

**Comment by bmtcril** [comment]
### CC Onboarding Checklist for Axim On-Call
- [x] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [ ] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [ ] Let CC know that they may be required to take the privacy and a11y courses when they become available.
- [ ] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while). Keep the ticket open with status “Blocked” until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [ ] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [ ] Add them to the [overall CC mailing list](https://groups.google.com/a/axim.org/g/core-contributors/members?pli=1).
- [ ] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [ ] Look up their record in Salesforce and grant them the Core Contributor role.
- [ ] Ensure they are in the openedx GitHub organization and a member of the [openedx-triage](https://github.com/orgs/openedx/teams/openedx-triage)
- [ ] Send Fox a direct message on Slack with the full name and email address of the new CC. (Fox will contact the new CC explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). 
- [ ] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

### Additional, for Coding Roles Only
- [ ] Add them to the [Google group](https://groups.google.com/a/axim.org/g/core-contributors-dev). This is very low traffic, meant primarily for announcements we want to be sure get to all developers.
- [ ] Add the CC to the `@core-contributor-committers` Slack user group
- [ ] Remind them to add themselves to the relevant shared Slack channel(s) corresponding to their merge accesses (some [additional context](https://docs.google.com/document/d/1-G-v3nrP8RN_j0P8gEsdI0ahdOoJFePiDHFOuPlUjlk/edit#heading=h.wsc5ai1lrvb6) if you’re curious). Here’s a DM you can copy and use: “For the repositories you have merge access to, [please join the Slack room(s) that correspond to your repositories](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit#gid=0). These rooms are where to coordinate timing on merging breaking or major changes. Keep in mind that 2U runs CI/CD off the tip of master branches, so major changes will impact their site first. It's generally OK to announce in these rooms that you are merging a pr with 24 hour or more notice (eg, I'm merging this tomorrow at 1500 UTC), and engage in discussion with anyone who expresses concern. These rooms are also a good place to ask for a 2U review on critical/breaking change PRs before you get to the merging state.”
- [ ] Also add them to the GitHub group [committers](https://github.com/orgs/openedx/teams/committers) teams.
- [ ] Grant write access to the repositories described in the vote. Do not grant it directly to the user; instead, use existing **committers-** teams, making new ones as you need to. [See this page for details](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3555852316/GitHub+Access+Team+Structure#Team-names-and-types).

**Comment by CodeWithEmad** [comment]
Hello @bmtcril. Yes, I've registered and have access to the course.

**Comment by CodeWithEmad** [comment]
Should I bother you for Listaflow access?

**Comment by bmtcril** [comment]
Hi @CodeWithEmad , the rest of the checklist above will be done once I've gotten confirmation that you've signed the Core Contributor agreement. So I'll let Fox know to add you to Listaflow and complete the work you requested [here](https://github.com/openedx/axim-engineering/issues/1263) once that happens. If you've signed the paperwork (which should be linked from the course) I'll confirm that on our side and finish this up.

For now I'm going to close that other ticket and wait to hear from you that the paperwork is all done.

**Comment by CodeWithEmad** [comment]
Thanks, @bmtcril. Yes, I got the final email from @sarina yesterday, saying that it's completed and signed by all parties.

**Comment by bmtcril** [comment]
Ok @CodeWithEmad you should be set up. Fox from OpenCraft will be in touch shortly about the Listaflow process. You may also want to join the following Slack channels related to the repositories that you now have write access to. 

- #cc-openedx-utils
- #cc-frontend-apps
- #cc-xblocks

As it says above:

> For the repositories you have merge access to, [please join the Slack room(s) that correspond to your repositories](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit#gid=0). These rooms are where to coordinate timing on merging breaking or major changes. Keep in mind that 2U runs CI/CD off the tip of master branches, so major changes will impact their site first. It's generally OK to announce in these rooms that you are merging a pr with 24 hour or more notice (eg, I'm merging this tomorrow at 1500 UTC), and engage in discussion with anyone who expresses concern. These rooms are also a good place to ask for a 2U review on critical/breaking change PRs before you get to the merging state.


Welcome, and let me know if you have any questions or run into any issues!
