### ISSUE TITLE
[GH Request] Codecov token not found in Credentials

### ISSUE THREAD

**Issue by MaxFrank13** [openedx/axim-engineering#1262]
### Repository

credentials

### Urgency

Medium (< 2 weeks)

### Requested Change

When running code coverage in CI for the [credentials repo](https://github.com/openedx/credentials), the workflow throws an error because it is unable to find a Codecov token ([source](https://github.com/openedx/credentials/actions/runs/10830430688/job/30051980800?pr=2576)). We'd like to have a token added to the repository ([docs](https://docs.codecov.com/docs/adding-the-codecov-token)).

### Reasoning

We want this change to be made so that code coverage can run in CI.

**Comment by bmtcril** [comment]
@MaxFrank13 there was a duplicate codecov token in the repo, which I've removed per the instructions here: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3438280709/Adding+Codecov . I _think_ tests were running a second time unnecessarily just for Codecov, so I'm removing that and testing things here: https://github.com/openedx/credentials/actions/runs/10962121735/job/30440625824?pr=2588 if you'd like to follow along.

**Comment by bmtcril** [comment]
Ok this should be set if anyone wants to review and merge it:

```
info - 2024-09-20 15:46:49,142 -- Found 1 coverage files to report
info - 2024-09-20 15:46:49,142 -- > /home/runner/work/credentials/credentials/coverage.xml
info - 2024-09-20 15:46:49,869 -- Your upload is now processing. When finished, results will be available at: https://app.codecov.io/github/openedx/credentials/commit/9540d2e586c6b1ffe8eeff1dd66923019d3ddf77
info - 2024-09-20 15:46:50,183 -- Process Upload complete
```

**Comment by bmtcril** [comment]
Looks like this is doing the right thing, now so I'm going to close it. LMK if you run into any issues.

**Comment by MaxFrank13** [comment]
Thanks @bmtcril!
