### ISSUE TITLE
[GH Request] Access Request 

### ISSUE THREAD

**Issue by CodeWithEmad** [openedx/axim-engineering#1263]
### Firm Name

edSPIRIT

### Urgency

Medium (< 2 weeks)

### Requested Change

I'll be maintaining the following repositories:
- https://github.com/openedx/openedx-chem
- https://github.com/openedx/frontend-app-ora-grading
- https://github.com/openedx/olxcleaner
- https://github.com/openedx/acid-block

Nomination URL: https://discuss.openedx.org/t/core-contributor-nomination-emad-rad/13697
@kdmccormick nominated me in the following thread. 

### Reasoning

well, I'm the new maintainer :)

**Comment by bmtcril** [comment]
This work will be handled here once all of the paperwork is signed: https://github.com/openedx/axim-engineering/issues/1257
