### ISSUE TITLE
[GH Request] temp remove branch protections for frontend-app-learner-dashboard/ branch 2u/main

### ISSUE THREAD

**Issue by deborahgu** [openedx/axim-engineering#1265]
### Firm Name

2u

### Urgency

High (< 3 days)

### Requested Change

Remove the branch protections, temporarily, on `2U/main`, so I can do a **one time** cleanup.

### Reasoning

The `2u/main` branch has branch protections, at 2U's request. Because we let it get  into a bad state, I would like to temporarily remove the branch protections so that I can force push a rebased branch with a cleaned up reflog, before I have everyone on the team switch to using explicit git CLI settings  so I guarantee we don't end up with out of sync reflog again.

I acknowledge that we have asked you to jump through this hoop a couple of times in the past, and it must be annoying; if this happens again, we will just cut bait and switch to a fork.

**Comment by bmtcril** [comment]
Hey @deborahgu, no worries. If you want I can schedule time with you after 3pm eastern today to do this semi-synchronously together over Slack.

**Comment by deborahgu** [comment]
that would be awesome; I'll reach out on slack for a time.

**Comment by bmtcril** [comment]
We did this synchronously and the permissions have been reset.
