### ISSUE TITLE
[GH Request] Termination of work relationship between edunext and Santiago Suárez (CC)

### ISSUE THREAD

**Issue by jalondonot** [openedx/axim-engineering#1275]
### Firm Name

edunext

### Urgency

Low (2 weeks)

### Problem/Request

I would like to inform you that the employment contract of Santiago Suárez (Core Contributor) and therefore the employment relationship between edunext and him has been terminated as of today. Santiago has the will to continue contributing to the Open edX community as a contributor not associated to any provider and leaves edunext on very good terms. Please let me know if there is anything else we need to do in addition to this notification.

### Reasoning

I've already added all the details in the previous section.

**Comment by ormsbee** [comment]
FYI to @crathbun428 and @jmakowski1123: I've disassociated Santiago's Salesforce account from eduNEXT, but he remains a Product Core Contributor.
