### ISSUE TITLE
[GH Request] remove/re-enable static-assets-check for edx-platform in order to land a PR

### ISSUE THREAD

**Issue by dianakhuang** [openedx/axim-engineering#1276]
### Repository

edx-platform

### Urgency

High (< 3 days)

### Requested Change

In order to land the PR to fix edx-platform testing, we need to disable the static-assets-check as a required check in the branch protection rules of edx-platform, as it's pinned to ubuntu-latest: https://github.com/openedx/edx-platform/pull/35635

For example:
```
static-assets-check (ubuntu-latest, 3.11, 18, 10.5.x, 7.0)
```

Once the PR has landed, we would like to enable these checks again for ubuntu-22.04.

### Reasoning

The rollover to ubuntu-24.04 caused a bunch of things to be broken in our current edx-platform workflows. We want to pin to ubuntu-22.04 while we work out how to upgrade the workflows and edx.org to ubuntu-24.04. The PR has more context.

**Comment by ormsbee** [comment]
I removed the two status-assets-check checks from the [branch protection rules](https://github.com/openedx/edx-platform/settings/branch_protection_rules/8021) for `master` on `edx-platform`.

![assets-checks](https://github.com/user-attachments/assets/95c189e5-4f54-4827-a304-9136a8be046f)

**Comment by ormsbee** [comment]
FYI @feanil as this is related to targeting ubuntu-latest.

**Comment by ormsbee** [comment]
I removed the status checks at around 9:56 EDT and put ubuntu-22.04 versions of them back in place at about 11:03 EDT.

![Image](https://github.com/user-attachments/assets/73b77dd6-4928-4d51-85ee-448cded33556)
