### ISSUE TITLE
[GH Request] flaky-test repo label and process questions

### ISSUE THREAD

**Issue by robrap** [openedx/axim-engineering#1277]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

I merged https://github.com/openedx/repo-tools/pull/566, and don't yet see the label in repositories. 
1. When and how do these definitions turn into actual labels on the repositories?
2. Could we update the file with more details (or a link to more details) about how often the sync is run?

### Reasoning

Completing updated flaky test process.

**Comment by feanil** [comment]
This is done. I ran it along side other updates I was making.

**Comment by timmc-edx** [comment]
Thank you!
