### ISSUE TITLE
[GH Request] Transfer Mobile Repositories into the OpenEdX organization

### ISSUE THREAD

**Issue by volodymyr-chekyrta** [openedx/axim-engineering#1279]
### Firm Name

RaccoonGang

### Urgency

High (< 3 days)

### Requested Change

Transfer the [foundation-ios](https://github.com/raccoongang/openedx-app-foundation-ios) and [foundation-android](https://github.com/raccoongang/openedx-app-foundation-android) repositories into the openedx organization.

### Reasoning

These two repositories were created as part of the migration process for mobile projects to the plugin architecture.
These plugins were developed and are available on the Raccoon Gang organization's GitHub account to facilitate development.
Since the code base of the mobile app([ios](https://github.com/openedx/openedx-app-ios/), [android](https://github.com/openedx/openedx-app-android/)) is in the openedx organization, we want to move the foundation plugins there as well.
After the transfer, we will configure CI and finalize the publishing process.

I'd like to ask for high urgency to meet the expected deadline.

**Comment by ormsbee** [comment]
@volodymyr-chekyrta: Please make me an admin for those repos.

Also, please list in this ticket the FCs that funded the work on those repos.

**Comment by volodymyr-chekyrta** [comment]
@ormsbee, I've granted you admin permissions those repos.
I'm not 100% sure, but I think it should be FC-0072.

**Comment by ormsbee** [comment]
@e0d: Just wanted to check that you're good with this before transferring.

**Comment by e0d** [comment]
@volodymyr-chekyrta can you ask Peter to post to this ticket to confirm you are contributing the new repo.

**Comment by Vvoous** [comment]
Confirm

**Comment by ormsbee** [comment]
Moving these now...

**Comment by volodymyr-chekyrta** [comment]
Thank you! 🙌
