### ISSUE TITLE
[GH Request] Onboard KristinAoki

### ISSUE THREAD

**Issue by KristinAoki** [openedx/axim-engineering#1280]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Kristin Aoki, KristinAoki

### User Squad

Aurora

### Start Date

21 October 2024

### Urgency

Low (2 weeks)

### Special Requests

Kristin needs to be removed from the TNL group and added to the Aurora group.

**Comment by ormsbee** [comment]
@KristinAoki:

* Added you to [2u-aurora](https://github.com/orgs/openedx/teams/2u-aurora/)
* Removed you from [2u-tnl](https://github.com/orgs/openedx/teams/2u-tnl)
* Removed you from [teaching-and-learning](https://github.com/orgs/openedx/teams/teaching-and-learning/members)
