### ISSUE TITLE
[GH Request] How-to pull in issues from repos to the BTR project board

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/axim-engineering#1282]
### Firm Name

edunext

### Urgency

Low (2 weeks)

### Problem/Request

Currently, we manually pull in issues labeled as ``release testing`` from any repo in the openedx organization to the BTR project.

### Reasoning

We need to find a way to automate this process so we don't miss any potential release blocker during the release testing process.

**Comment by sarina** [comment]
I think this would involve adding a workflow to .github repo that all openedx repos would inherit from, that would watch for a label event and add to board. I don't see a way to add such a workflow via the github board UI. I think this is a task that any community member could do - make the workflow in a personal repo, test it, and open a PR to the `openedx/.github` repo.

**Comment by mariajgrimaldi** [comment]
Oh yes. I was following your recommendation [here](https://openedx.slack.com/archives/C049JQZFR5E/p1715277642270559?thread_ts=1715274100.786799&cid=C049JQZFR5E), thinking this was already solved somehow. I'll get to work then. Thank you.

**Comment by sarina** [comment]
I'm happy to review it, but I don't think I'll have time to get to it for this release cycle. IIRC, routing things to boards requires using the GitHub GraphQL library which two years ago (when I used it, before there was basic board automation) wasn't 100% straightforward.
