### ISSUE TITLE
[GH Request] Create "enterprise-integrated-channels" repo 

### ISSUE THREAD

**Issue by sameenfatima78** [openedx/axim-engineering#1284]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Problem/Request

We’d like to request a new repository where we can migrate the [integrated_channels Django app](https://github.com/openedx/edx-enterprise/tree/master/integrated_channels) as a separately installable plugin.

### Reasoning

Iris is currently working on extracting the enterprise specific Integrated Channels functionality from `openedx` to convert it into an installable plugin. To support this, we’d like to request a new repository where we can migrate the [integrated_channels Django app](https://github.com/openedx/edx-enterprise/tree/master/integrated_channels).

Maintainers of this new repo would be: @openedx/2u-iris

**Comment by saraburns1** [comment]
Hi @sameenfatima78 - can you please confirm the team (github group) that will be responsible for maintaining this repo?

**Comment by sameenfatima78** [comment]
@openedx/2u-iris will be responsible for maintaining it.

**Comment by saraburns1** [comment]
All set @sameenfatima78 - https://github.com/openedx/enterprise-integrated-channels

I've added 2u-iris as a maintainer. Let me know if you need anything else

**Comment by saraburns1** [comment]
I've added the AGPLv3 license. If there is any issue with this, please let me know
