### ISSUE TITLE
[GH Request] remove branch protection on frontend-app-learner-dashboard 2u/main

### ISSUE THREAD

**Issue by deborahgu** [openedx/axim-engineering#1286]
### Repository

frontend-app-learner-dashboard

### Urgency

High (< 3 days)

### Requested Change

Hi, you created the branch protections on https://github.com/openedx/frontend-app-learner-dashboard/tree/2u/main at our request. In the end, it's created more problems for us than solutions. Could you remove the protections, so we can force push to the branch?

### Reasoning

I'd rather not have to 

1. fork 
2. ask for your help every time someone clicks the wrong button

😭

**Comment by saraburns1** [comment]
All set @deborahgu
