### ISSUE TITLE
[GH Request] Transfer Firebase Mobile Plugins into the OpenEdX organization

### ISSUE THREAD

**Issue by volodymyr-chekyrta** [openedx/axim-engineering#1287]
### Firm Name

RaccoonGang

### Urgency

Medium (< 2 weeks)

### Requested Change

Transfer the [openedx-app-firebase-analytics-ios](https://github.com/raccoongang/openedx-app-firebase-analytics-ios) and [openedx-app-firebase-analytics-android](https://github.com/raccoongang/openedx-app-firebase-analytics-android) plugins into the openedx organization.

### Reasoning

Follow up on https://github.com/openedx/axim-engineering/issues/1279.

These two repositories were created as part of the migration process for mobile projects to the plugin architecture (FC-0072).
These plugins were developed and are available on the Raccoon Gang organization's GitHub account to facilitate development.
Since the code base of the [mobile apps](https://github.com/openedx/openedx-app-ios/) and [foundation plugins](https://github.com/openedx/openedx-app-foundation-ios) is in the openedx organization, we also want to move the analytics plugins there.
After the transfer, we will configure CI and finalize the publishing process.

**Comment by saraburns1** [comment]
Hi @volodymyr-chekyrta - can you please make me an admin on those repos and tag Peter to approve?

Also please confirm that [rg-mobile team](https://github.com/orgs/openedx/teams/rg-mobile) should have write access

**Comment by volodymyr-chekyrta** [comment]
Hi @saraburns1,  
I've granted you admin permissions for these repositories.  

Yes, please provide write permissions to the [rg-mobile team](https://github.com/orgs/openedx/teams/rg-mobile); we will maintain these repositories.

I'll ask Peter to post here for confirmation our intention to move repos.

**Comment by Vvoous** [comment]
Approved

**Comment by saraburns1** [comment]
@volodymyr-chekyrta - https://github.com/openedx/openedx-app-firebase-analytics-ios is all set, i've removed individual access and added rg-mobile as admin

it looks like i only have push access to openedx-app-firebase-analytics-android - can you check that please?

**Comment by volodymyr-chekyrta** [comment]
@saraburns1, My mistake, I changed it to admin.
Thank you!

**Comment by saraburns1** [comment]
https://github.com/openedx/openedx-app-firebase-analytics-android is all set as well!

**Comment by volodymyr-chekyrta** [comment]
Thank you!
