### ISSUE TITLE
[Miscellaneous Request] Re create the Large instances WG meeting using the new meetings@openedx.org account

### ISSUE THREAD

**Issue by felipemontoya** [openedx/axim-engineering#1289]
### Firm Name

edunext

### Urgency

Low (2 weeks)

### Problem/Request

We have a recurring meeting for the [Large Instances WG](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3655008783/Large+Instances+-+DevOps+Sub-Working+Group). The current calendar event is: https://calendar.google.com/calendar/u/0/event?eid=NjBtb2w4cnA5NzQ1N2cwaDc5OGtwZjliZTJfMjAyNDEwMDFUMTcwMDAwWiBjX3Y4NnNocm5lZ3Noc3FncDRmajJrOTR1N2JjQGc

We are still using the deprecated zoom link and the meetings are being recorded in Xavier's account I think. We'd like to get up to standard.

Co-host should be @bradenmacdonald and @felipemontoya as chairs of that group.

### Reasoning

Streamlined approach to record WG meetings, based on https://discuss.openedx.org/t/input-needed-proposed-change-to-working-group-meeting-hosting/13845/5

**Comment by saraburns1** [comment]
@felipemontoya - can you please transfer the meeting to meetings@openedx.org ? @e0d is going to help with this

**Comment by felipemontoya** [comment]
The current meeting is an old meeting created by @antoviaque. Perhaps he could help us transfering it.

**Comment by antoviaque** [comment]
@felipemontoya @saraburns1 I have tried changing the ownership to meetings@openedx.org - see if that worked?

**Comment by saraburns1** [comment]
@felipemontoya - The changes have been made. You should be able to see it in the WG calendar and it's been updated from Zoom to Meet.  Braden and Felipe are co-hosts.

Let me know if you need anything else!

**Comment by felipemontoya** [comment]
@saraburns1 thanks a lot. I now see the google meet link. I don't see the cohost permissions which I tried to use to delete the old zoom call link from the details. If it is not how the cohost permissions work then could I ask you to please remove them? Right now both link are showing and that could lead to some people trying to attend the old zoom.

**Comment by saraburns1** [comment]
@felipemontoya this should be all set not, let me know if it's not!

**Comment by felipemontoya** [comment]
Yes, the meeting link is now very clear. Thank you @saraburns1
