### ISSUE TITLE
[GH Request] Remove required checks from commerce-coordinator Repo

### ISSUE THREAD

**Issue by huniafatima-arbi** [openedx/axim-engineering#1290]
### Repository

commerce-coordinator

### Urgency

Medium (< 2 weeks)

### Requested Change

Need to remove required checks of py38 from course-discovery repo in order to merge Python 3.12 upgrade https://github.com/edx/commerce-coordinator/pull/284.

### Reasoning

We are dropping the support of Python 3.8 as Python 3.8 end of life is Oct 2024. We need to upgrade to Python 3.12 before that to avoid breaking anything.

**Comment by saraburns1** [comment]
Hi @huniafatima-arbi - Axim does not manage any repos in the edx org so you'll need to talk with your IT team about this request.
