### ISSUE TITLE
[GH Request] add secrets to the "enterprise-integrated-channels" repo

### ISSUE THREAD

**Issue by sameeramin** [openedx/axim-engineering#1293]
### Repository

enterprise-integrated-channels

### Urgency

Medium (< 2 weeks)

### Requested Change

We'd need some Github secrets added to the [enterprise-integrated-channels](https://github.com/openedx/enterprise-integrated-channels) repo which are required by Github Workflow.

### Reasoning

The Iris team has recently requested to create [this](https://github.com/openedx/enterprise-integrated-channels) repo for separating the enterprise specific Integrated Channels functionality. After pushing the boilerplate to the repo, we now need to add secrets to GitHub settings that Github Workflows require.

**Comment by feanil** [comment]
@sameeramin you should have all workflow related secrets available already is there a specific workflow that's failing?

**Comment by sameeramin** [comment]
My bad, I thought we needed to set up secrets ourselves.
