### ISSUE TITLE
[GH Request] Add renovate bot PAT to the harmony repository

### ISSUE THREAD

**Issue by Ian2012** [openedx/axim-engineering#1295]
### Repository

openedx-k8s-harmony

### Urgency

Medium (< 2 weeks)

### Requested Change

Add a Github's Personal Access Token with write access to the openedx-k8s-harmony repository on a secret called `RENOVATE_PATH` to enable the renovate bot to open PR to the same repository.

A similar mechanism has already been implemented as part of frontend-app-authoring repository.

### Reasoning

Renovate bot will help us maintaining the Helm Chart dependencies up-to-date on the Harmony project

**Comment by saraburns1** [comment]
@Ian2012 - I've added this repo to the list of active Renovate repos. We use the github integration so i don't think you need the renovate yaml you created but you can see if it causes problems before deleting it.

**Comment by Ian2012** [comment]
Thanks, it worked correctly. I will remove the action
