### ISSUE TITLE
[GH Request] Onboard <AntonellaPerrupato>

### ISSUE THREAD

**Issue by AntonellaPerrupato** [openedx/axim-engineering#1296]
### Firm Name

Aulasneo

### User List (case sensitive!) - Please also include in ticket title

Antonella Perrupato, @AntonellaPerrupato

### Start Date

6/11/2024

### Urgency

High (< 3 days)

### Special Requests

It would be ideal to have the permissions to be able to assign issues and modify tags on the [btr board](https://github.com/orgs/openedx/projects/28/views/16?sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=111811488) and thus fulfill the bug triager tasks during the redwood release without depending on other colleagues

**Comment by saraburns1** [comment]
@AntonellaPerrupato this is all set!

**Comment by AntonellaPerrupato** [comment]
Thanks!!
