### ISSUE TITLE
[GH Request] Permissions to create documents, edit and comment in Confluence

### ISSUE THREAD

**Issue by SantiagoSuHe** [openedx/axim-engineering#1297]
### Firm Name

Santiago Independent Contributor

### Urgency

Low (2 weeks)

### Requested Change

I what permissions over my personal user to create, edit, and comment documents in Confluence.
Right now I am receiving this message
![IMG_EB9D729394C1-1](https://github.com/user-attachments/assets/163aa5cf-6641-41f3-b6fd-0f8b8cef905e)

### Reasoning

I need this permissions to contribute in projects

**Comment by saraburns1** [comment]
@SantiagoSuHe - i've just sent an invite to your gmail which should give you access. Let me know if this doesn't work

**Comment by sarina** [comment]
@SantiagoSuHe are you good here?

**Comment by SantiagoSuHe** [comment]
Hi Sarina, thanks for following up on this.
I still can't assign myself a card on github

**Comment by sarina** [comment]
Hi Santiago, please accept the invite to the organization.

**Comment by SantiagoSuHe** [comment]
I had already accepted the invitation.
But in any case I did it again.

**Comment by sarina** [comment]
@SantiagoSuHe I am able to assign you to issues now. See this issue!

**Comment by SantiagoSuHe** [comment]
It works thanks!
