### ISSUE TITLE
[GH Request] Onboard magajh

### ISSUE THREAD

**Issue by magajh** [openedx/axim-engineering#1299]
### Firm Name

edunext

### User List (case sensitive!) - Please also include in ticket title

Maga Giorgianni, @magajh

### User Squad

BTR - bug triager

### Start Date

24 October 2024

### Urgency

High (< 3 days)

### Special Requests

It would be ideal to have permissions to assign issues, modify tags, and update issue names and descriptions on the [BTR board](https://github.com/orgs/openedx/projects/28/views/16?sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=111811488), enabling me to carry out the bug triager tasks during the Redwood release without depending on colleagues.
Thanks in advance!

**Comment by sarina** [comment]
Hi @magajh - you're already a part of the `openedx-triage` team:: https://github.com/orgs/openedx/teams?query=%40magajh

Unfortunately, GH's permissions aren't fine grained, and you can't have permissions such as editing an issue's title unless you have Write access on the repository. Apologies about that.

You should be able to edit labels, if not, you can use the https://github.com/openedx/.github/blob/master/.github/workflows/add-remove-label-on-comment.yml action.

**Comment by magajh** [comment]
Got it, @sarina! I made the request because I thought I needed additional permissions to edit issue titles. Thank you!

**Comment by sarina** [comment]
Gotcha. Unfortunately you can only have Write access on repos you're a core contributor to.
