### ISSUE TITLE
[GH Request] Grant access to the mobile android repo

### ISSUE THREAD

**Issue by volodymyr-chekyrta** [openedx/axim-engineering#1304]
### Firm Name

RaccoonGang

### Urgency

High (< 3 days)

### Requested Change

Hello, 
I am not sure this is the right place, but I cannot request a review from @PavloNetrebchuk for https://github.com/openedx/openedx-app-android/pulls.
Is it possible to provide him the same permission/access that @IvanStepanok has for https://github.com/openedx/openedx-app-ios?
As I understand, need to add him to some group or something.

Thank you!

### Reasoning

Pull requests review issue.

**Comment by sarina** [comment]
I've added @PavloNetrebchuk to the Triage group.

**Comment by volodymyr-chekyrta** [comment]
@sarina thank you!
