### ISSUE TITLE
[GH Request] Onboard edschema

### ISSUE THREAD

**Issue by edschema** [openedx/axim-engineering#1305]
### Firm Name

Schema Education

### User List (case sensitive!) - Please also include in ticket title

Edward Byun, @edschema

### Start Date

20 November 2024

### Urgency

Medium (< 2 weeks)

### Special Requests

Open edX Mobile Roadmap read/write access
openedx-triage

**Comment by sarina** [comment]
I've invited @edschema to the Triage group, which anyone can request.

Can a core contributor vouch for the request for roadmap read/write access?

**Comment by marcotuts** [comment]
Hello! read / write access would be helpful as @edschema will be helping drive product management needs for mobile, including the mobile roadmap github project and PRs related to that.

**Comment by sarina** [comment]
Once @edschema has accepted the invite to the Open edX organization, I'll add them as a project manager to that board.

**Comment by edschema** [comment]
Thank you Sarina!

**Comment by sarina** [comment]
Done!
