### ISSUE TITLE
[GH Request] Offboard many ex-2U Folks

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#1310]
### Firm Name

Axim

### User List  (case sensitive!) - Please also include in ticket title

Based on a review by @jristau1984 the following folks are all no longer employed by 2U.  That info was based on a review of their Slack instance so it may not be completely accurate.  @georgebabey please review or connect me with someone who can confirm this list, I'm planning on dropping access for these users tomorrow if I don't hear back.

- [x] AbdouSeck
- [x] ashultz0
- [x] asifbilal786
- [x] bpedx
- [x] ccmelo
- [x] chennighan2u
- [x] colinbrash
- [x] dan1d
- [x] danielleEriksen
- [x] dixidroid
- [x] emrosarioa
- [x] eyatsenkoperpetio
- [x] farhanumar
- [x] forgotvas
- [x] germanolleunlp
- [x] giddygitau
- [x] Gregpeinke
- [x] hassan6190
- [x] ishahroz
- [x] JAAkana
- [x] jsongedx
- [x] mbrown500
- [x] MueezKhan246
- [x] mzeshanarif
- [x] nrobertson1992
- [x] praveenram2u
- [x] sameeramin
- [x] Toxicom
- [x] Zacharis278
- [x] zubair-ce07

### End Date

20 Nov 2024

### Urgency

High (< 3 days)

**Comment by jristau1984** [comment]
For comprehensiveness, jsongedx is still with 2U but had a name change.  However, openedx access is not needed for this user.

**Comment by feanil** [comment]
These folks have all been off-boarded.

**Comment by sameeramin** [comment]
Hey @feanil @jristau1984 I think there might be some misunderstanding, I'm still working with 2U and actively contributing to Openedx

**Comment by sameeramin** [comment]
@MueezKhan246 is also actively contributing to Openedx and we both are working in `2u-iris` team

**Comment by georgebabey** [comment]
@feanil Yes, confirmed. Both are still active with 2U and on `2u-iris`
