### ISSUE TITLE
Access to assign myself to github cards

### ISSUE THREAD

**Issue by SantiagoSuHe** [openedx/axim-engineering#1311]
### Firm Name

Independent 

### Urgency

Medium (< 2 weeks)

### Requested Change

I need permission to edit github cards and assign myself to them with my profile santiagosh96@gmail.com

### Reasoning

Contribute to projects

**Comment by sarina** [comment]
You've invited Santiago Suarez to Open edX! They'll be receiving an email shortly. They can also visit https://github.com/openedx to accept the invitation.

Once you click that link (in the next 7 days!), you'll be good to go.
