### ISSUE TITLE
[GH Request] Onboard NIXKnight

### ISSUE THREAD

**Issue by AmiraQuick** [openedx/axim-engineering#1312]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Saad Ali, @ NIXKnight

Arbisoft Contractor Rehire

### Start Date

22 November 2024

### Urgency

Low (2 weeks)

**Comment by lattaai16-gh** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the '.github/ISSUE_TEMPLATE/01-github-request---onboarding.yml' file to include default values based on the given criteria. Updated the firm name, user list, start date, and urgency fields.

You can review changes in this commit: https://github.com/lattaai16-gh/openedx-axim-engineering-1312/commit/c8cc28767577a9d3233c15f057f783e3d926f98a.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by sarina** [comment]
@AmiraQuick could you provide more detail? What type of onboarding/access does @NIXKnight need?

**Comment by AmiraQuick** [comment]
Hi @sarina !

Is it possible to mirror @zeeshan-maqbool 's access?

**Comment by sarina** [comment]
@zeeshan-maqbool is not in the Open edX organization

**Comment by feanil** [comment]
@AmiraQuick what team will Saad be joining?  Can you tag the relevant manager to confirm here as well?

**Comment by AmiraQuick** [comment]
Hi @feanil . So sorry for the delayed response, I've been out of the office. 

@atrepca can you confirm what team Saad will be joining? Thanks!

**Comment by feanil** [comment]
Ok, he should have access back.
