### ISSUE TITLE
[GH Request] lost rights to Open eDX organization

### ISSUE THREAD

**Issue by dixidroid** [openedx/axim-engineering#1317]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

Add dixidroid to the the "Open edX" organization

### Reasoning

Igor, a dev on 2U android team lost access to openedx. His git account is https://github.com/dixidroid

**Comment by feanil** [comment]
@dixidroid can someone at 2U confirm that you should have access?  @georgebabey?

**Comment by georgebabey** [comment]
Confirming Igor, dixidroid, is on our mobile team

**Comment by feanil** [comment]
Ok, Igor should have an invite to the `openedx` org that reinstates his access.
