### ISSUE TITLE
[GH Request] permissions to openEdx repo

### ISSUE THREAD

**Issue by rnr** [openedx/axim-engineering#1318]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

Add `rnr` to the the "Open edX" organization

### Reasoning

Anton, the Lead 2U iOS team lost access to openedx. His git account is https://github.com/rnr

**Comment by feanil** [comment]
@georgebabey can you confirm that this user should have access?  I also don't have this user as having access before to any `openedx` repos.

@rnr what repos do you believe you should have access to?

**Comment by georgebabey** [comment]
Confirmed Anton is on our mobile team.

**Comment by rnr** [comment]
> @georgebabey can you confirm that this user should have access? I also don't have this user as having access before to any `openedx` repos.
> 
> @rnr what repos do you believe you should have access to?

@feanil I think accessing https://github.com/openedx/openedx-app-ios and https://github.com/openedx/openedx-app-foundation-ios is enough for now.

Thank you

**Comment by feanil** [comment]
You should have access back now,.
