### ISSUE TITLE
[GH Request] CC onboarding for Sam Daitzman

### ISSUE THREAD

**Issue by crathbun428** [openedx/axim-engineering#1322]
### Firm Name

Axim

### Urgency

Low (2 weeks)

### Problem/Request

Requesting CC onboarding for Sam Daitzman; Sam will be a UX/UI core contributor

### Reasoning

Reason: [Link to cc nomination](https://discuss.openedx.org/t/core-contributor-nomination-sam-daitzman/14400)

Github username: sdaitzman
Sam's email address: [sam.daitzman@schema.education](mailto:sam.daitzman@schema.education)

### CC Onboarding Checklist for Axim On-Call
- [x] Invite them to the [Core Contributor Onboarding course](https://training.openedx.io/courses/course-v1:OpenedX+NewCC+2024/instructor#view-membership) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [x] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Let CC know that they may be required to take the privacy and a11y courses when they become available.
- [x] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while). Keep the ticket open with status “Blocked” until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [x] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [x] Add them to the [overall CC mailing list](https://groups.google.com/a/axim.org/g/core-contributors/members?pli=1).
- [x] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [x] Look up their record in Salesforce and grant them the Core Contributor role.
- [x] Ensure they are in the openedx GitHub organization and a member of the [openedx-triage](https://github.com/orgs/openedx/teams/openedx-triage)
- [x] Send Fox a direct message on Slack with the full name and email address of the new CC. (Fox will contact the new CC explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). 
- [x] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

**Comment by feanil** [comment]
@sdaitzman you should have an invite to the CC onboarding course, can you confirm? You will need to register at https://training.openedx.io to get access if you don't already have an account.

**Comment by sdaitzman** [comment]
Thanks @feanil, invite received and registered!

**Comment by feanil** [comment]
Please let us know here when you've completed the class.

**Comment by feanil** [comment]
You should have the listaflow invites now.  I think this ticket is all set.
