### ISSUE TITLE
[GH Request] remove email secrets from frontend-app-learner-dashboard

### ISSUE THREAD

**Issue by deborahgu** [openedx/axim-engineering#1323]
### Repository

axim-engineering

### Urgency

Low (2 weeks)

### Requested Change

 1. Reply to this letting us know that you're fine with maintainers removing `Send failure notification` from the repo CI.
 2. remove `EDX_SMTP_USERNAME` and `EDX_SMTP_PASSWORD` from the `frontend-app-learner-dashboard` secrets.

### Reasoning

The [Send failure notification](https://github.com/openedx/frontend-app-learner-dashboard/blob/604298eacac0cd3765423517146195f8f7310b5a/.github/workflows/ci.yml#L45-L60) has been intermittently failing for a very long time. We, the code maintainers, _could_ debug this. But we also have a workflow where we proactively check CI test results, and don't need the email. If Axim's okay with it, we'd rather just remove the email action here.

**Comment by feanil** [comment]
@deborahgu that sounds fine, the SMTP secrets are global to the org but you're welcome to drop this if you're checking CI regularly.  I think one of the reasons for this e-mail is that it runs the check on master as well and which you won't easily see on a PR.  However, if you still want that you can also just [get notifications directly from github](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/notifications-for-workflow-runs).
