### ISSUE TITLE
[GH Request] Onboard Muhammad Omar Sarfraz

### ISSUE THREAD

**Issue by macdiesel** [openedx/axim-engineering#1325]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Name: Muhammad Omar Sarfraz
2U Email: [osarfraz@2u.com](mailto:osarfraz@2u.com)
Github Username: omar-sarfraz ([Profile Link](https://github.com/omar-sarfraz))
Current Team: Enterprise Markhors

Thank you!

### User Squad

Enterprise Markhors

### Start Date

When Possible

### Urgency

Low (2 weeks)

**Comment by feanil** [comment]
Invitation sent.   I've added them to the markhors github team. They should be added to the CLA database tomorrow when it refreshes.
