### ISSUE TITLE
[GH Request] Onboard hinakhadim

### ISSUE THREAD

**Issue by AmiraQuick** [openedx/axim-engineering#1327]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Hina Khadim, @ hinakhadim

### Start Date

10 December 2024

### Urgency

Low (2 weeks)

**Comment by kdmccormick** [comment]
@AmiraQuick Which squad?

**Comment by AmiraQuick** [comment]
I believe Engineering but let me have @jristau1984 confirm!

**Comment by AmiraQuick** [comment]
@jristau1984 can you provide which squad Hina will be joining?

**Comment by jristau1984** [comment]
Hina is joining the T&L team (2u-tnl)

**Comment by kdmccormick** [comment]
Hina's GitHub invite has been sent to her GitHub-associated email, with memership on the openedx-triage and 2u-tnl teams.

Note for Axim: I updated Hina's entity CLA from Arbisoft to 2U.
