### ISSUE TITLE
[System Request] Cancel the Large Instances WG meeting on the 24

### ISSUE THREAD

**Issue by felipemontoya** [openedx/axim-engineering#1330]
### Firm Name

edunext

### Urgency

Low (2 weeks)

### Problem/Request

Please cancel/delete the WG meeting for the large instances WG that is scheduled for Christmas eve.  

### Reasoning

We met today and agreed that the meeting on the 24th should be cancelled as everyone will be out for holidays.

WG meetings will resume on the 7th of jan 2025.

**Comment by kdmccormick** [comment]
Thanks for thinking of this Felipe 🎄
