### ISSUE TITLE
[GH Request] Onboard  ahmad-hassan-dev

### ISSUE THREAD

**Issue by AmiraQuick** [openedx/axim-engineering#1332]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Ahmad Hassan, @  ahmad-hassan-dev

### User Squad

Arbisoft 

### Start Date

12 December 2024

### Urgency

Low (2 weeks)

**Comment by kdmccormick** [comment]
Hey @AmiraQuick ... for this request, and for every future onboarding request, we need to know the specific squad within 2U engineering which the new employee belongs to. Thanks.

**Comment by AmiraQuick** [comment]
Hi @kdmccormick !

So sorry, I'll start looping in the user's managers for these requests since I am unsure of specific squads the user needs access to.

@sameenfatima78 can you assist? What specific Squad does Ahmad need access to?

**Comment by sameenfatima78** [comment]
@kdmccormick @AmiraQuick Hey, Ahmad belongs to @openedx/2u-iris

**Comment by kdmccormick** [comment]
Ahmad has been added under the 2U CLA and should see an openedx organization invite in his GitHub-associated email, with membership to the openedx-triage and 2u-iris teams.
