### ISSUE TITLE
[GH Request] Offboard georgebabey

### ISSUE THREAD

**Issue by AmiraQuick** [openedx/axim-engineering#1335]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

George Babey, @ georgebabey

### End Date

13 December 2024

### Urgency

Low (2 weeks)

**Comment by kdmccormick** [comment]
Removed from 2U CLA, removed from openedx github org

**Comment by kdmccormick** [comment]
TO DO: Ask Ed about other salesforce fields

**Comment by kdmccormick** [comment]
George's Salesforce record is cleaned up.
