### ISSUE TITLE
Tidy up the wiki

### ISSUE THREAD

**Issue by kdmccormick** [openedx/axim-engineering#352]
## Problem

Browsing through https://openedx.atlassian.net/wiki/, it's tough to distinguish between what's:
* actively used
* inactive but maybe useful
* way out-of-date and misleading

For example:
* [OEPM](https://openedx.atlassian.net/wiki/spaces/OEPM) is new and actively used
* [OpenOPS](https://openedx.atlassian.net/wiki/spaces/OpenOPS) has fallen out of use and out of date (it's mostly Ansible-era stuff).

That's easy enough for me to tell, but as a community contributor, how would I know that one of those spaces should be trusted and the other shouldn't?

## Proposed Solution

* In order to see what the average community member sees: Create a new openedx.atlassian.net user with no special permissions.
* Browse through the spaces: https://openedx.atlassian.net/wiki/spaces
* For each space:
  * Is it actively being used?
    * If so:
      * Make sure the space has an appropriate title, icon, and description. This will help folks recognize that the space is worth paying attention to and help focus the pages that are created there.
      * Do a cursory tidy-up of the top level folders in the space. Feel free move old pages into an "Archive" top-level folder.
    * If not: Does it contain enough useful information that it's worth keeping public?
      * If so: Archive the space, manually append ` (Archive)` to the space title, change the icon to the default blue folder, and add a warning message to the front page.
      * If so: Archive the space, restrict its visibility to tCRIL employees, and manually append ` (Private Archive)` to the space title.

**Comment by kdmccormick** [comment]
cc @sarina since we were just talking about this, and @feanil since it relates to documentation.

If you guys like the sound of my proposal, then I am happy to do this when I have spare time on some Friday afternoon. I would just need admin rights on Confluence.

**Comment by feanil** [comment]
It's not a bad proposal, I think it would be worth having at-least a few people go through it as different people may have different context on the info presented.  Does it make sense to do this as a pair maybe?

**Comment by kdmccormick** [comment]
Good idea. What if we just set up an optional team meeting and do this synchronously with whoever is interested?

**Comment by sarina** [comment]
I'm interested in participating! I already have a no-permissions user.

It'd be good to have some structure so we don't spend a long time on one item. Perhaps we could pull a spreadsheet, divide it up, make recommendations on the sheet, and then come together synchronously to present/discuss?

**Comment by sarina** [comment]
What ever happened with this? I feel it should be considered as part of a whole with the overarching documentation philosophy.

This feels pretty low-importance to me - I periodically move pages into an Archived section when I find them outdated and not useful (rather than pushing the actual "Archive" button - I only recently got this permission). I'd rather focus on building out quality documentation, if I had to focus my efforts somewhere.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/1985317/188182916-4d2c098d-fc40-4188-b87e-cd842cba9d25.png">

**Comment by kdmccormick** [comment]
> What ever happened with this?

Pulling together a spreadsheet ended up being more work than I was willing to do without "officially" prioritizing this ticket through Jenna. I should have said that earlier but I didn't realize it until after this had fallen off my radar.

> This feels pretty low-importance to me

A lot of people look at the wiki. A lot of work happens on it. There's a lot of outdated & misleading info on it. We could leave it an organizational disaster zone, or we could use our prerogative to clean it up from the top down. I really think that when set the tone of "the wiki is an organized place", folks will treat it as such and do their part to help keep it that way.

> I feel it should be considered as part of a whole with the overarching documentation philosophy.

Yes, it could be. Alternatively, we could see it as part of the "clean up from decoupling" long tail (along with https://github.com/openedx/tcril-engineering/issues/29 and https://github.com/openedx/codejail/issues/121), with the aim of just getting it out of the way whenever we have time.

I don't think this needs to take long. When a suggested I meeting, I really meant that a couple of us could get in a call and do this in an hour or two. I feel like this is a long-standing, low-hanging-fruit quality-of-life thing that was always behind red tape when we were at edX, but now is totally doable since we own the wiki.

**Comment by sarina** [comment]
@kdmccormick want to make some time to work on this together as a team during our in-person week? Perhaps we could set up 90 m - 2h on one of the mornings, and bring in donuts or something.

**Comment by kdmccormick** [comment]
This was done back in 2023
