### ISSUE TITLE
Cleanup references to oscm@edx.org and other misc. remaining edx references

### ISSUE THREAD

**Issue by e0d** [openedx/axim-engineering#386]
There are references to oscm@edx.org sprinkled throughout the org, we should update them to oscm@openedx.org

https://github.com/search?q=org%3Aopenedx+oscm%40edx.orgoscm@edx.org&tyoscm@edx.orgpe=code

Also there are a few items leftover from #42 : 

### easier:

- [ ] `oscm@edx.org` -> `oscm@openedx.org`
- [ ] `uses: edx/.github` string should, in most cases (but not all) be `uses: openedx/.github`
- [ ] another: `http://code.edx.org/individual-contributor-agreement.pdf` -> `https://openedx.org/cla`
- [ ] any instances of `openedx/testeng-ci` that I missed (that repo still in /edx/ org)

### harder:
a switch/replace will fix 80% or so, but every PR will require manual checking to make sure they didn't hit things that stayed in the `edx` org. Potentially, these repo names can be obtained, and the strings parsed. Unclear which is more work.

- [ ] potentially (probably) there are other `uses: edx:` strings; should evaluate need for that switch
- [ ] `github.com/repos/edx/` (for API strings) - again will be ok in most, but not all, places
- [ ] `git clone git@github.com:edx/`  -- already fixed paragon

**Comment by sarina** [comment]
What would you think about holding on this until we have maintainers, and then asking maintainers to update appropriately? I don't think, for example, the references on the configuration repo should go to us - what would we do with them?
