### ISSUE TITLE
Integrate newly converted MFEs into the comprehensive theming system

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/axim-engineering#438]
Contingent on completing https://github.com/openedx/wg-frontend/issues/156

**Comment by davidjoy** [comment]
Just a quick note, and I'd love to talk about this more - I strongly suggest we don't do this.  Rather, we should create more well-supported and well-documented customization methods that don't rely on a blanket 'overlay' of code.  The comp theming system is akin to forking the repository in terms of maintainability, which is to say, it makes maintaining the theme code very difficult.  We have other options available to us that are almost equally powerful and far more documentable/maintainable/supportable.

**Comment by arbrandes** [comment]
Yeah, this is an old ticket.  We've moved on from this idea since it was first proposed.
