### ISSUE TITLE
Three Heroku Projects running deprecated stack version

### ISSUE THREAD

**Issue by e0d** [openedx/axim-engineering#454]
> The Heroku-18 stack is deprecated
> You have 4 apps in this team that are using the Heroku-18 stack, which is deprecated. From April 30th, 2023, Heroku-18 will be end-of-life and no longer receive security updates. From May 1st, 2023, builds will be disabled. Please upgrade your apps to a newer Heroku stack. [ Visit here to learn more](https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq)

The projects are:
- openedx-pr-watcher-notifier
- ~~openedx-webhooks~~ - Done along with some other maintenance.
- openedxstats

Some helpful links

https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq
https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack

**Comment by feanil** [comment]
The last two have been updated:
* https://github.com/openedx/pr_watcher_notifier/pull/7
* https://github.com/openedx/openedxstats/pull/197

Both have been deployed and working, just waiting for the PRs to land.

**Comment by feanil** [comment]
All app updates have been merged and deployed to heroku.
