### ISSUE TITLE
Discovery: What is the process to get a new language supported on an MFE?

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/axim-engineering#479]
Put simply, find out how add a language (say, Esperanto) to MFEs.  This includes:

* The learner being able to select it from _somewhere_ (find out where)
* The deployer should be able to select it for inclusion in their instance
* The translator should be able to select that language for translation
* It should be possible to pull the translated strings back into the several components of the platform

Document this via https://github.com/openedx/docs.openedx.org/issues/154

**Comment by brian-smith-tcril** [comment]
document current process:
seems it's just (basing this on https://github.com/openedx/frontend-app-learning/blob/master/Makefile)
for each MFE
* `make extract_translations`
* `make push_translations`
* `make pull_translations`

automate extract process
* follow example of python from https://github.com/openedx/openedx-translations/blob/main/.github/workflows/extract-translation-source-files.yml
* clone MFE repo in `openedx-translations` gh action
* run `extract_translations`
* copy translated files to the correct place in `openedx-translations` repo
* commit

**Comment by brian-smith-tcril** [comment]
## adding a new language

using https://github.com/openedx/frontend-app-library-authoring as an example:

update https://github.com/openedx/frontend-app-library-authoring/blob/88a4502b12269bbb4cb548eb6ce9bb840ba6b975/Makefile#L2 to have the new lang

??? do something in transifex ???

## extract translation files

`make extract_translations`

## get source strings into transifex

install transifex cli https://developers.transifex.com/docs/cli

??? do something with `detect_changed_source_translations` ???

`make push_translations`

## get translations back into repo

`make pull_translations`

## how much of this is automated?

not sure yet

**Comment by brian-smith-tcril** [comment]
based on the commit message on https://github.com/openedx/openedx-translations/commit/33b6cd20509e3abdc1702c4bbbeaa3bb00978230

going forward we'll want to use https://github.com/openedx/openedx-translations/blob/main/transifex.yml instead of the transifex cli

**Comment by brian-smith-tcril** [comment]
looks like pulling down updated translations is automated (see https://github.com/openedx/frontend-app-account/pull/655), i'm not sure where this is being run from or where the code for it lives, my assumption is it's just running `make pull_translations` on each MFE but without seeing the code i cannot confirm

**Comment by arbrandes** [comment]
Atlas migration is in full swing, so we can close this!
