### ISSUE TITLE
[GH Request] Allow outside collaborators to create and triage issues

### ISSUE THREAD

**Issue by e0d** [openedx/axim-engineering#506]
### Firm Name

tCRIL

### Urgency

Low Urgency

### Requested Change

I, @e0d , am managing this request, but creating a ticket to record the work.

We'd like RG staff working on the Credentials project to be able to create, edit, issues on the Credentials board as they begin development of the VC feature.

### Reasoning

Allow folks working on a domain to create and triage issues, ideally without giving them write access to the repo unless there's an additional requirement for taking that step.

**Comment by e0d** [comment]
>An outside collaborator is a person who is not a member of your organization, but has access to one or more of your organization's repositories. You can choose the level of access to grant for each outside collaborator. When you add an outside collaborator to a repository, you'll also need to add them to any forks of the repository you'd like them to access.

https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization#:~:text=An%20outside%20collaborator%20is,like%20them%20to%20access.

**Comment by feanil** [comment]
@e0d what's the state of this ticket? Is it still in progress?

**Comment by e0d** [comment]
Not done, back burner.  Could move to TODO.

**Comment by sarina** [comment]
@e0d just noticing this. Nell & I have reviewed and giving Triage access to anyone in the community to any repo is totally fine. Is Triage access sufficient for this team?
