### ISSUE TITLE
BrowserStack Team Subscription

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/axim-engineering#514]
It would be great to have access to a tool like [BrowserStack](https://www.browserstack.com/) for interactive testing of MFEs across multiple browsers.

It seems they offer free subscriptions of some sort for open source projects https://www.browserstack.com/open-source

If we don't qualify for that for one reason or another, it seems their team plan for 5 users (the minimum listed) is $125 a month https://www.browserstack.com/pricing

**Comment by e0d** [comment]
I've made the initial inquiry/request to be accepted into their program.

**Comment by e0d** [comment]
I never heard back from them, but have resubmitted my request today.  Let's see.

**Comment by e0d** [comment]
@brian-smith-tcril I just hear back.  We should discuss how/where we want to enable this.

> Thank you for writing back!
> 
> If you require an Open Source Sponsorship, please create a free trial account with BrowserStack.
> 
> You are a couple of steps away from activating your subscription: a valid open source license, being one of them.
> 
> I looked through your project page and was not able to find it. Please point me in the right direction, if I missed something. If you don’t have a license yet, take the time to choose the right license and add it to your project page.
> 
> [Here is a guide on how to do it on GitHub.](https://email.browserstack.com/c/eJxFTstyhSAM_Rrd4YgQ1AWLu-lvdJBEpZcLCtiZ9uuL7aIzmTzOOUkOaa7UKISaetWihgVwbJ1WQvHJKAWTleadL3ZY-KIAQJDtuRQ9SE5jlx3S051sTXReFApbkR0Rr0wmF85exgXBFn8Rg2lVgHaUiq0f3-fYyJ4q7bu6mnek_OxsfLW7NmIYJZoZRf05z5IAkANMKMRsxWRar_dSjtyIRzO81djJH93myn4t94mKUKjpD6mNTWSKCxuzPoa7moDMJLu7z3tKdMTsSkyOclV7ZynkX9k_9dUmTVgtF5uq5Zi2HzjhZVE)
> 
> Additionally, to proceed with your sponsorship, please help us verify your ownership of the open-source project you would like to test. To do this:
>  
> 1. Your project on GitHub has to be at least 3 months old.
>  
> 2. You must submit and merge a PR to the project. The PR has to add the following text to your readme.md file: “This project is tested with BrowserStack.”
>  
> 3. The PR has to be dated post the date of your sponsorship request.
>  
> Please send us the link to your PR after all the steps are completed. We will verify the approval points and activate your sponsorship accordingly.
>  
> Thank you for your understanding, and we look forward to getting you started on BrowserStack soon.

**Comment by e0d** [comment]
@brian-smith-tcril I never did hear from them.  Is this still useful or a priority?

**Comment by e0d** [comment]
Will close for now, we can reopen if it becomes a priority.
