### ISSUE TITLE
Import FeedbackXBlock into the openedx org

### ISSUE THREAD

**Issue by e0d** [openedx/axim-engineering#547]
The RateXBlock has been deprecated and will be replace by the [FeedbackXBlock](https://github.com/pmitros/FeedbackXBlock).  This was created while Piotr was an employee of edX.  This initial substantive commit was on Oct 7, 2015.  We will:

- fork this repository
- disconnect it from the upstream
- add the standard license for XBlocks, Apache 2
- bring it up to our maintenance standards
- update reference to use this version

**Comment by jmbowman** [comment]
Will tCRIL be the maintainer for this one?  (It just showed up in our ownership spreadsheet reconciliation tooling.)

**Comment by e0d** [comment]
Yes, it's a replacement for the deprecated RateXBlock.

**Comment by kdmccormick** [comment]
@e0d I see you forked the repo to https://github.com/openedx/FeedbackXBlock.

I think it still needs to be published to PyPI and installed into edx-platform.

**Comment by kdmccormick** [comment]
Related: https://github.com/openedx/FeedbackXBlock/pull/2

**Comment by feanil** [comment]
Looks like this move was completed a while ago so closing this ticket.
