### ISSUE TITLE
Setup and tear down a Demo Machine for Olive

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#584]
Adolfo and Jenna need a machine to demo Olive to OER Commons, create an ec2 instance with ingress on 22, 80, 443 and full egress.

Make sure Adolfo has ssh access.

**Comment by feanil** [comment]
https://github.com/openedx/terraform-internal/pull/29 and https://github.com/openedx/terraform-internal/pull/30 created this machine and the olive-demo.tf file can be removed when this is ready to be cleaned up.

**Comment by arbrandes** [comment]
One release later (😅) I finally created [some docs on the process](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3793485852/How+to+deploy+Tutor+Palm+with+the+Learner+Dashboard+MFE), so I figure we can close this.
