### ISSUE TITLE
Write post about how to deal with GH notifications

### ISSUE THREAD

**Issue by arbrandes** [openedx/axim-engineering#627]
It seems I was not the only one affected by the deluge of GH notifications, and the subsequent failure to react to the important ones.  I should write a forum post about what I did to ameliorate the problem.

Notify Kelly B about it in particular, so she can share with 2U.

**Comment by nedbat** [comment]
I'll be interested to read this one :)

**Comment by arbrandes** [comment]
Repo as been repurposed - closing personal issues.
