### ISSUE TITLE
Investigate frontend-platform build process

### ISSUE THREAD

**Issue by arbrandes** [openedx/axim-engineering#629]
The way frontend-platform is built makes it impossible to npm-install directly from git.  Investigate why this is the case and report back [in the forum thread](https://discuss.openedx.org/t/problems-applying-customised-mfe-libraries-eg-frontend-platform-to-a-production-open-edx-platform-using-tutor-local/8691).

**Comment by davidjoy** [comment]
I'd be happy to help provide context/clarity on the frontend-platform build process - it looks like the forum thread author found a solution to their localization issues, if I read the thread right?  But also that folks may be confused how the libraries are packaged for npm, how they work with module.config.js, etc.

**Comment by arbrandes** [comment]
I met Dimitris at the conference, and he brought the localization issue up.  He managed a workaround, but the true fix is going to come out not of the npm-installability issue, but of us revamping how i18n is done for MFEs.  I.e., out of scope here.

As for the issue described here, me and Pedro are working on how to port frontend-platform over to MFE Domains Land, and a possibly suitable alternative might come out of _that_.

**Comment by arbrandes** [comment]
Stale.
