### ISSUE TITLE
[GH Request] Offboard <moconnell1453>

### ISSUE THREAD

**Issue by kmedina2u** [openedx/axim-engineering#703]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Mike O'Connell, @moconnell1453

### End Date

15 March 2023

### Urgency

Medium (< 2 weeks)

### Retained Permissions & Special Requests

Mike O'Connell's last day with 2U was March 15, 2023

**Comment by sarina** [comment]
Disassociated Salesforce record

**Comment by brian-smith-tcril** [comment]
moconnell1453 is not a member of the openedx GH org.
