### ISSUE TITLE
[GH Request] Shut down edx Opsgenie instance

### ISSUE THREAD

**Issue by timmc-edx** [openedx/axim-engineering#706]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

The `edx` Opsgenie instance is still running, but is now confirmed as unused by 2U. It can be shut down at tCRIL's convenience.

### Reasoning

(filing ticket on behalf of Ed)

**Comment by kdmccormick** [comment]
Great! Currently asking around internally on which buttons we need to push / who we need to contact in order to make this happen.

**Comment by kdmccormick** [comment]
It's not obvious how to disable OpsGenie, as it's not listed a "product" alongside Jira and Confluence. I reached out to Atlassian support: https://support.atlassian.com/requests/CA-2303947/ (private link, just sharing here for Axim reference)

**Comment by kdmccormick** [comment]
Support got back to us explaining how to turn off OpsGenie (it's called "Jira Service Management" in the admin settings 🙄). I'm running a Jira & Confluence backup now, and then I should be all set to delete OpsGenie.

**Comment by kdmccormick** [comment]
I deleted our instance of Jira Service Management, which includes OpsGenie. I am no longer able to log into app.opsgenie.com with my work email, which makes me think it worked.

@timmc-edx , @matthugs , if you see any traces of the edx OpsGenie instance hanging around, just open this ticket back up!
