### ISSUE TITLE
[GH Request] Onboard emrosarioa

### ISSUE THREAD

**Issue by macdiesel** [openedx/axim-engineering#708]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

emrosarioa

### Start Date

03 April 2023

### Urgency

Medium (< 2 weeks)

**Comment by brian-smith-tcril** [comment]
Hi @macdiesel! In order to complete this request we'll need to know an email address for https://github.com/emrosarioa

Also, is there a reason they haven't been added to the [edx](https://github.com/edx) GitHub org yet?

Thanks!

**Comment by sarina** [comment]
Added to salesforce

**Comment by brian-smith-tcril** [comment]
Added to openedx org and push-pull-all
