### ISSUE TITLE
[GH Request] Onboard @stroccoli, @alekst23, @openback, @ChrisMeyer7088

### ISSUE THREAD

**Issue by ashleybeam** [openedx/axim-engineering#709]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Sebastian Troccoli, @stroccoli
* Aleksandr Titeranko, @alekst23
* Tim Caraballo, @openback
* Chris Meyer, @ChrisMeyer7088

### Start Date

3/30/2023

### Urgency

Medium (< 2 weeks)

**Comment by sarina** [comment]
@georgebabey is @ashleybeam authorized on behalf of 2U to issue onboarding requests?

**Comment by brian-smith-tcril** [comment]
added stroccoli, alekst23, openback, and ChrisMeyer7088 to the openedx GH org and push-pull-all
