### ISSUE TITLE
[GH Request] Onboard thomty

### ISSUE THREAD

**Issue by adzuci** [openedx/axim-engineering#710]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Tyler Thompson @thomty

### Start Date

December 2021

### Urgency

High (< 3 days)

**Comment by adzuci** [comment]
Bumping this request.

**Comment by sarina** [comment]
Added to Salesforce

**Comment by brian-smith-tcril** [comment]
added thomty to the openedx org and push-pull-all
