### ISSUE TITLE
[GH Request] Onboard <ADD USERNAMES HERE>

### ISSUE THREAD

**Issue by HacDmv** [openedx/axim-engineering#712]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Emily Aquin, @emrosarioa, eaquin@2u.com

### Start Date

04/03/23

### Urgency

High (< 3 days)

**Comment by sarina** [comment]
@georgebabey is @HacDmv authorized on behalf of 2U to issue onboarding requests?

**Comment by brian-smith-tcril** [comment]
closing as a dupe of https://github.com/openedx/axim-engineering/issues/708
