### ISSUE TITLE
[GH Request] Review Repo Health Workflow followup PR

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/axim-engineering#714]
### Firm Name

2U

### Urgency

High (< 3 days)

### Problem/Request

https://github.com/edx/edx-arch-experiments/issues/66 moved the `repo health workflow` from Jenkins to GitHub Actions. After the reusable workflow was [merged](https://github.com/openedx/.github/pull/52) in the `openedx/.github` repo, it was tested using a trigger workflow from `edx/repo-health-data` which [failed](https://github.com/edx/repo-health-data/actions/runs/4607361958) because the secrets were not properly categorised in the reusable workflow.

### Reasoning

The follow up PR https://github.com/openedx/.github/pull/72 needs to be merged to fix the secrets issue in the reusable workflow. `2U arbi-bom` team's progress on the task will be on halt till this PR has been merged.

**Comment by kdmccormick** [comment]
All set!
