### ISSUE TITLE
[GH Request] New Github action secret

### ISSUE THREAD

**Issue by ahtesham-quraish** [openedx/axim-engineering#715]
### Firm Name

tCRIL

### Urgency

High (< 3 days)

### Requested Change

We need new GITHUB_TOKEN which has read and write permissions which we can use in Github actions and this action will trigger on master push or PR label change. Link of workflow is given below.

https://github.com/openedx/frontend-app-authn/blob/master/.github/workflows/autoupdate.yml

### Reasoning

Auto update workflow needs GITHUB_TOKEN  (read and write permissions) which would rebase the PR branch whenever changes would be landed on destination branch. We have added this workflow in frontend-app-authn repo in openedx. We have tried to use the CC_GITHUB_TOKEN which is already created but it does have full rights. Please create GH token with proper rights so we can use the workflow.

"https://github.com/openedx/frontend-app-authn"

**Comment by ormsbee** [comment]
@ahtesham-quraish: GITHUB_TOKEN is [generated automatically](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret) by GitHub. You should have access to it in your workflow and not need to use CC_GITHUB_TOKEN.

**Comment by ormsbee** [comment]
I'm closing this ticket now. Please re-open if needed. Thank you.
