### ISSUE TITLE
Code Core Contributor Permissions for Glib

### ISSUE THREAD

**Issue by e0d** [openedx/axim-engineering#718]
Pending approval by the maintainer, grant permissions to commit to:

- openedx/credentials
- openedx/frontend-app-learner-record

**Comment by hurtstotouchfire** [comment]
This is approved, I will follow up with Glib via slack. We don't have a deployment plan set up yet so we will need to sort that out.

**Comment by ormsbee** [comment]
Granted those (along with credentials-themes) in this ticket: https://github.com/openedx/axim-engineering/issues/722
