### ISSUE TITLE
[GH Request] Onboard <jwenerd> <DonLang>

### ISSUE THREAD

**Issue by iobrien2u** [openedx/axim-engineering#721]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Jared Wenerd,jwenerd@2u.com, @jwenerd
Don Lang,dlang@2u.com, @DonLang

### Start Date

11 April 2023

### Urgency

Medium (< 2 weeks)

### Special Requests

push-pull-all team

**Comment by ormsbee** [comment]
@jwenerd and @DonLang have been invited to the openedx GitHub org and added to push-pull-all.

**Comment by iobrien2u** [comment]
Hi @ormsbee, thank for your help on this! There has been some miscommunication in the request we received and these users no longer need openedx GitHub access. Can you please remove these users when you have a chance? I apologize for the inconvenience!

**Comment by ormsbee** [comment]
@iobrien2u: I've removed @jwenerd and @DonLang from the openedx GitHub org. I have also removed their 2U entity CLA entries in Salesforce for consistency. Please open a new ticket if they need to be added to the openedx at some later date.

Thank you.
