### ISSUE TITLE
[GH Request] Onboard @GlugovGrGlib

### ISSUE THREAD

**Issue by GlugovGrGlib** [openedx/axim-engineering#722]
### Firm Name

Raccoon Gang

### User List (case sensitive!) - Please also include in ticket title

@GlugovGrGlib

### Start Date

11 April 2023

### Urgency

Medium (< 2 weeks)

### Special Requests

Requesting CC access for Glib Glugovskiy with gh username @GlugovGrGlib to repos
[openedx/credentials: Service hosting course and program certificates](https://github.com/openedx/credentials)
[openedx/frontend-app-learner-record: Open edX micro-frontend application for viewing learner records](https://github.com/openedx/frontend-app-learner-record)
[openedx/credentials-themes: Themes for the edX Credentials Service](https://github.com/openedx/credentials-themes)

Reason: https://discuss.openedx.org/t/core-contributor-nomination-glib-glugovskiy/9598

Instructions: Please give access to [openedx/credentials: Service hosting course and program certificates](https://github.com/openedx/credentials)
[openedx/frontend-app-learner-record: Open edX micro-frontend application for viewing learner records](https://github.com/openedx/frontend-app-learner-record)
[openedx/credentials-themes: Themes for the edX Credentials Service](https://github.com/openedx/credentials-themes)

**Comment by ormsbee** [comment]
@GlugovGrGlib: Please let me know when you've completed the onboarding course and I'll add you to the appropriate groups.

**Comment by GlugovGrGlib** [comment]
Hi @ormsbee, thanks I've completed the onboarding course and signed CC agreement.

**Comment by ormsbee** [comment]
* You have been added to the `@core-contributor-committers` Slack user group
* You were already in the #core-contributors Slack room
* You have been added to the Google group: https://groups.google.com/a/axim.org/g/core-contributors-dev
* You have been added to the [Core Contributors](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Core+Contributors+to+the+Open+edX+Project) wiki page.
* You have been marked as a Core Contributor in Salesforce
* The "Core Contributor" badge has been added to your [forum profile](https://discuss.openedx.org/u/glib_glugovskiy/badges).

----

Please add yourself to any [repo-specific rooms](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit?usp=sharing) of interest to you.

> These rooms are where to coordinate timing on merging breaking or major changes. Keep in mind that 2U runs CI/CD off the tip of master branches, so major changes will impact their site first. It's generally OK to announce in these rooms that you are merging a pr with 24 hour or more notice (eg, I'm merging this tomorrow at 1500 UTC), and engage in discussion with anyone who expresses concern. These rooms are also a good place to ask for a 2U review on critical/breaking change PRs before you get to the merging state.

**Comment by ormsbee** [comment]
@GlugovGrGlib 

* You have been added to the `@core-contributor-committers` Slack user group
* You were already in the #core-contributors Slack room
* You have been added to the Google group: https://groups.google.com/a/axim.org/g/core-contributors-dev
* You have been added to the [Core Contributors](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Core+Contributors+to+the+Open+edX+Project) wiki page.
* You have been marked as a Core Contributor in Salesforce
* The "Core Contributor" badge has been added to your [forum profile](https://discuss.openedx.org/u/glib_glugovskiy/badges).
* A new GitHub group has been created for you: [CCP Committer: GlugovGrGlib](https://github.com/orgs/openedx/teams/ccp-committer-glugovgrglib) and you have been invited to it. This makes it easier to manage permissions. That team has been granted Write access to the following repos:
 * https://github.com/openedx/credentials
 * https://github.com/openedx/credentials-themes
 * https://github.com/openedx/frontend-app-learner-record

----

Please add yourself to any [repo-specific rooms](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit?usp=sharing) of interest to you.

> These rooms are where to coordinate timing on merging breaking or major changes. Keep in mind that 2U runs CI/CD off the tip of master branches, so major changes will impact their site first. It's generally OK to announce in these rooms that you are merging a pr with 24 hour or more notice (eg, I'm merging this tomorrow at 1500 UTC), and engage in discussion with anyone who expresses concern. These rooms are also a good place to ask for a 2U review on critical/breaking change PRs before you get to the merging state.

**Comment by ormsbee** [comment]
@GlugovGrGlib: If you encounter any issues, please re-open this ticket.
