### ISSUE TITLE
[GH Request] Onboard <ayesha-waris>

### ISSUE THREAD

**Issue by billyhho** [openedx/axim-engineering#730]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Ayesha Waris, ayesha-waris

### Start Date

04/20/2023

### Urgency

High (< 3 days)

**Comment by sarina** [comment]
This user is already a part of our github organization: https://github.com/orgs/openedx/people?query=ayesha

<img width="994" alt="image" src="https://user-images.githubusercontent.com/1985317/233481908-7370f7d7-6de4-4e90-b0c6-13665d742f57.png">

What is the request?

**Comment by sarina** [comment]
cc @ayesha-waris

**Comment by billyhho** [comment]
Ayesha recently updated their GitHub ID (formerly ayesoali) and is unable to pass tests to merge any PR -- CLA is not working according to her

**Comment by sarina** [comment]
OK, in this case the CLA had to be updated, yes.

Could we please advise people to not change their Github username? Thank you.

**Comment by sarina** [comment]
Oh, it will take 24 hours for the changes to take effect.
