### ISSUE TITLE
[GH Request] Onboard <rebke2u>< jprodma2u><bfigueroa95><ochavarria2u><reyesU2><jandino2u><fhembecker><amatta2u>

### ISSUE THREAD

**Issue by iobrien2u** [openedx/axim-engineering#732]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Ryan Ebke, rebke@2u.com, @rebke2u
Jose Pablo Rodriguez, jrodriguez4@2u.com, @jprodma2u
Bernardo Figueroa, bfigueroa@2u.com, @bfigueroa95
Oscar Chavarria, ochavarria@2u.com, @ochavarria2u
Alexander Reyes, areyes1@2u.com, @reyesU2
Jonathan Andino, jandino@2u.com, @jandino2u
Fernanda Hembecker, fhembecker@2u.com, @fhembecker
Alejandro Matta, amatta@2u.com, @amatta2u

### Start Date

28 April 2023

### Urgency

Low (2 weeks)

### Special Requests

Please grant access to push-pull-all team. Request is from Helpdesk ticket 01455252 and includes manager approval from Jasper Valero, Sr Manager Software Engineering. Let me know if additional info is needed for the request.
![Screenshot 2023-04-26 at 4 53 11 PM](https://user-images.githubusercontent.com/101654433/234699798-61344e48-32c2-49bc-8b2e-f5075e563e4d.png)
![Screenshot 2023-04-26 at 4 53 30 PM](https://user-images.githubusercontent.com/101654433/234699843-c07f7f07-64f5-4e8e-8262-eb0363eebc06.png)

**Comment by sarina** [comment]
@georgebabey is @iobrien2u authorized to make these requests? 

If so, @iobrien2u what is your name?

**Comment by iobrien2u** [comment]
Hi @sarina I'm Ian O'Brien and I'm an IT Helpdesk Analyst.

**Comment by georgebabey** [comment]
Approved

**Comment by sarina** [comment]
Invitations have been sent. Users have 7 days to accept their invite, @iobrien2u please make sure everyone accepts their invite in the next 7 days. If they do not, they will need to file another ticket to re-request access.

Invites will go to the primary email address on their GitHub accounts.
