### ISSUE TITLE
[GH Request] Add Maintainers Access for 2U Employees

### ISSUE THREAD

**Issue by colinbrash** [openedx/axim-engineering#735]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

Please add the following users:
* Mushtaq Rossier @MushtaqRossier
* Jade Olivier @JadeyOlivier

to the following teams:
* @openedx/ecommerce-maintainers
* @openedx/frontend-app-ecommerce-maintainers 
* @openedx/ecommerce-worker-maintainers 
* @openedx/frontend-app-payment-maintainers 

### Reasoning

Jade and Mushtaq are doing work for the 2U Purchase Squad and require write access to the associated repos.

Thanks!

**Comment by e0d** [comment]
@colinbrash they've been invited to the teams.

**Comment by e0d** [comment]
Please confirm things look good and I'll close this out.

**Comment by e0d** [comment]
Moving to done.
