### ISSUE TITLE
[GH Request] Onboard <jszewczulak>

### ISSUE THREAD

**Issue by jsoto2u** [openedx/axim-engineering#736]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Jakub Szewczulak, @jszewczulak

### Start Date

05/02/2023

### Urgency

High (< 3 days)

### Special Requests

Email: jszewczulak@2u.com
User is requesting same access their manager @mattcarter has incase they have additional access given besides the default push-pull-all

**Comment by e0d** [comment]
An invite has been sent.

**Comment by e0d** [comment]
Moving to done, please let us know if there are any issues.
