### ISSUE TITLE
[GH Request] Create a new repo for wg-translations

### ISSUE THREAD

**Issue by ghassanmas** [openedx/axim-engineering#737]
### Firm Name

Zaatdev/Axim

### Urgency

Medium (< 2 weeks)

### Requested Change

Creating a github repo for translation working group, named `wg-translations`

### Reasoning

Reason why to create translations-wg
- We would want to follow the typical WGs process of tracking issues/tickets. 
- Having TWG issues/tickets inside github would make easier for other folks to check them/reference them as instead of having them in trello.

CC: @ehuthmacher

**Comment by kdmccormick** [comment]
To follow the pattern of the other WG repos, I recommend `wg-translations`.

**Comment by ghassanmas** [comment]
@kdmccormick Yup what you think is best, when writing this issue, I wasn't sure which should come first, so I just followed the link https://github.com/openedx/frontend-wg but I didn't notice that the link redireted to `wg-frontend` 😅  I will edit the request accordingly

**Comment by e0d** [comment]
I've created the repo and an associated team with Triage rights.  Ghassan and Eden are currently the only folks in that team.  Please let me know who will need access and what their GitHub user names are.

**Comment by ehuthmacher** [comment]
@e0d Can we set this up as a public board, so anyone with a GH account can create issues and respond to issues? That way, I do not have to collect the list.

**Comment by e0d** [comment]
@ehuthmacher the project is already public and anyone with a GitHub account can create issues.  Triage is for folks who need additional permissions for managing issues.

> Triage: Recommended for contributors who need to proactively manage issues, discussions, and pull requests without write access

More details: https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role

**Comment by ehuthmacher** [comment]
Got it. I have shared a spreadsheet in the Translation WG Slack channel to obtain the missing user info.

**Comment by ghassanmas** [comment]
@e0d, thank you for creating the repo, we still though need a project board be linked to the issues craeted in the repo, for example I just created a test issue https://github.com/openedx/wg-translations/issues/1, but I can't see it linked to any project nor can I create a project

**Comment by e0d** [comment]
Board has been created.  Closing.  Also have been working with @ehuthmacher to make folks assignable, but will handle that separately.
