### ISSUE TITLE
[GH Request] CC onboarding @gabor-boros

### ISSUE THREAD

**Issue by gabor-boros** [openedx/axim-engineering#739]
### Firm Name

OpenCraft

### Urgency

Low (2 weeks)

### Problem/Request

Requesting access to CC onboarding for Gábor Boros <gabor@opencraft.com>, @gabor-boros

### Reasoning

https://discuss.openedx.org/t/core-contributor-nomination-gabor-boros/9886

- [x] Verify with @Sarina Canelake/Legal that the Committer successfully completed the required legal documents. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while.)

- [x] Invite the Committer to the Open edX #core-contributors Slack channel and the @core-contributor-committers Slack user group

- [x] Remind them to add themselves to the relevant [shared Slack channel(s)](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit?usp=sharing) corresponding to their merge accesses (read more about this change [here](https://docs.google.com/document/d/1-G-v3nrP8RN_j0P8gEsdI0ahdOoJFePiDHFOuPlUjlk/edit#heading=h.wsc5ai1lrvb6)). 

- [x] Add them to the Google group: https://groups.google.com/a/axim.org/g/core-contributors-dev - this is very low traffic, meant primarily for announcements we want to be sure get to all developers. Also add them to the overall CC group: https://groups.google.com/a/axim.org/g/core-contributors/members?pli=1

- [x] Add them to the Core contributors directory page

- [x] Look up their record in Salesforce and grant them the Core Contributor role.

- [x] Create a new GitHub team with the name: “CCP Committer: {Contributor’s GitHub user}”

        Send an invite to add this user to this group
        Add the appropriate repos to the team and make sure to check that they have the appropriate access (e.g. Write, Triage, etc.)

- [x] Send @Dean Jay Mathew a direct message on Slack with the full name and email address of the new CC so they can be added to listaflow.

- [x] Ask a Forum Moderator to [award the “Core Contributor” badg](https://discuss.openedx.org/admin/users/list/active)e to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

**Comment by e0d** [comment]
requested access is to [k8s-harmony](https://github.com/openedx/openedx-k8s-harmony)

**Comment by e0d** [comment]
@gabor-boros you should have received an invitation to the on-boarding course.

**Comment by e0d** [comment]
Blocked by completion of the course and required agreements.

**Comment by e0d** [comment]
@gabor-boros yes please.

**Comment by gabor-boros** [comment]
@e0d I just completed the course. Does this issue have a corresponding tcril ticket to get onboarded -- I couldn't find it?

**Comment by feanil** [comment]
@gabor-boros We've completed everything we need to do on our side for the on-boarding, I think you should now be all set along with an invite for the org with write access to openedx-k8s-harmony.

Thank you for your patience through the process!
