### ISSUE TITLE
[GH Request] Offboard <alfredoguillem>

### ISSUE THREAD

**Issue by kmedina2u** [openedx/axim-engineering#742]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Alfredo Guillem, @alfredoguillem

### End Date

05 May 2023

### Urgency

Low (2 weeks)

### Retained Permissions & Special Requests

Past due termination

**Comment by e0d** [comment]
The change has been made to Salesforce and will flow through to the CLA bot later this afternoon.

**Comment by e0d** [comment]
The user has also been removed from the GitHub organization.
