### ISSUE TITLE
[GH Request] Onboard santiagosuarezedunext

### ISSUE THREAD

**Issue by santiagosuarezedunext** [openedx/axim-engineering#744]
### Firm Name

eduNEXT

### User List (case sensitive!) - Please also include in ticket title

santiagosuarezedunext

### Start Date

8 May 2023

### Urgency

Low (2 weeks)

**Comment by e0d** [comment]
@santiagosuarezedunext can you provide some more context, is this for CC or on-boarding to the eduNEXT entity CLA?

**Comment by santiagosuarezedunext** [comment]
Hi @e0d of course I had a successful nomination for core contributor https://discuss.openedx.org/t/core-contributor-nomination-santiago-suarez/9846

**Comment by sarina** [comment]
@santiagosuarezedunext I've invited you to the Core Contributor onboarding course to your eduNEXT email address.

**Comment by sarina** [comment]
@santiagosuarezedunext we can't move forward until you've taken the onboarding course and followed the instructions in there. Please let me know if you didn't receive the course invite.

**Comment by sarina** [comment]
### Coding CC Onboarding Checklist for Axim On-Call
- [ ] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [ ] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Set up access for CC in privacy & a11y courses (can skip for now, but let CC know that they may be upcoming).
- [ ] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while). Keep the ticket open with status “Blocked” until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [ ] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [ ] Add the CC to the `@core-contributor-committers` Slack user group
- [ ] Remind them to add themselves to the relevant shared Slack channel(s) corresponding to their merge accesses (some [additional context](https://docs.google.com/document/d/1-G-v3nrP8RN_j0P8gEsdI0ahdOoJFePiDHFOuPlUjlk/edit#heading=h.wsc5ai1lrvb6) if you’re curious). Here’s a DM you can copy and use: “For the repositories you have merge access to, [please join the Slack room(s) that correspond to your repositories](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit#gid=0). These rooms are where to coordinate timing on merging breaking or major changes. Keep in mind that 2U runs CI/CD off the tip of master branches, so major changes will impact their site first. It's generally OK to announce in these rooms that you are merging a pr with 24 hour or more notice (eg, I'm merging this tomorrow at 1500 UTC), and engage in discussion with anyone who expresses concern. These rooms are also a good place to ask for a 2U review on critical/breaking change PRs before you get to the merging state.”
- [ ] Add them to the [Google group](https://groups.google.com/a/axim.org/g/core-contributors-dev). This is very low traffic, meant primarily for announcements we want to be sure get to all developers. Also add them to the [overall CC group](https://groups.google.com/a/axim.org/g/core-contributors/members?pli=1).
- [ ] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [ ] Look up their record in Salesforce and grant them the Core Contributor role.
- [ ] Create a new GitHub team with the name: `CCP Committer: {Contributor's GitHub user}`. Add repositories to the team at the appropriate access levels, as specified by the CC vote.
- [ ] Is this user in the GitHub org?
  * If so: Add them to the teams `CCP Committer: {Contributor's GitHub user}`` and `openedx-triage`.
  * If not: invite them to the GitHub org, including those two teams in the invite. They will need to confirm their invite via email.
- [ ] Send Dean a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)
- [ ] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://github.com/wiki/spaces/COMM/pages/3156344833)).

**Comment by sarina** [comment]
@santiagosuarezedunext you are onboarded as a Core Contributor! You will receive access to Listaflow in a week or two. Congrats, and welcome!
