### ISSUE TITLE
[GH Request] Write access to openedx-k8s-harmony

### ISSUE THREAD

**Issue by gabor-boros** [openedx/axim-engineering#745]
### Firm Name

OpenCraft

### Urgency

Low (2 weeks)

### Requested Change

I would like to request write access to https://github.com/openedx/openedx-k8s-harmony

### Reasoning

nomination thread: https://discuss.openedx.org/t/core-contributor-nomination-gabor-boros/9886

**Comment by e0d** [comment]
@bradenmacdonald should @gabor-boros be added to the maintainers group or do we need a new group for this repo?

**Comment by feanil** [comment]
@e0d we're still waiting for the CC Agreement to be fully executed on our side, so you should hold off until that's completed at least.

**Comment by bradenmacdonald** [comment]
@e0d Please add him to https://github.com/orgs/openedx/teams/openedx-k8s-harmony-maintainers once the CC agreement is in place.

**Comment by gabor-boros** [comment]
@feanil The CLA was signed. May I have an access? 😇

**Comment by feanil** [comment]
Yep, I'm working through the next steps on our side now,  I'll let you know once they're done and you have access!
