### ISSUE TITLE
[GH Request] Push event-bus-kafka docs to readthedocs

### ISSUE THREAD

**Issue by rgraber** [openedx/axim-engineering#749]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

Create a readthedocs site for https://github.com/openedx/event-bus-kafka. It already has a docs folder and .readthedocs.yaml so it should just be a matter of having an upload token, I think.

### Reasoning

We'd like to have the documentation there for easier discovery and consistency with other openedx repos.

**Comment by feanil** [comment]
The docs are now published here: https://docs.openedx.org/projects/event-bus-kafka/en/latest/ and you should also have test builds running on new PRs.
