### ISSUE TITLE
CC Onboarding: cassiezamparini

### ISSUE THREAD

**Issue by cassiezamparini** [openedx/axim-engineering#750]
### Firm Name

OpenCraft

### Urgency

Low (2 weeks)

### Problem/Request

Hi there, as per [this post](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3359113457/Core+Contributor+Non-Committer+Onboarding), could access to the Core Contributor onboarding course be granted to me? My email address is: cassie@opencraft.com. 

### Reasoning

Discourse CC nomination thread: https://discuss.openedx.org/t/core-contributor-nomination-cassie-zamparini/9778/18

**Comment by cassiezamparini** [comment]
@feanil Just got it! And I've logged in successfully :) Thank you!

**Comment by feanil** [comment]
Great, I think you'll have some e-mails that you send as a part of the CC on-boarding for further steps but I'm gonna close this ticket for now.

**Comment by sarina** [comment]
@feanil there's a pile of things to do once the legal documents are received: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3359866883/Administering+a+CC+non-committer+Onboarding+Runbook

How can we make sure these items are done? I think this ticket ought to have stayed open so that the remainder of the tasks were completed.

**Comment by sarina** [comment]
I updated the docs to make it clearer that you need to do the post-legal-documents steps as part of onboarding. @feanil can you see if that makes things clearer, and then follow the remaining steps?

**Comment by feanil** [comment]
The extra words are good @sarina , I think my understanding was that as a part of completing the course they would make another ticket once they have completed all the per-requisite work on their end and then we would on-board them.  It felt a little weird to have the ticket for requesting access to the course stay open for a long time(until we get an e-mail from Legal or pull for that info at a later time).

**Comment by cassiezamparini** [comment]
@feanil I've done everything I can on my side so far 👍 

I've also completed the following in reference to [this list:](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3359866883/Administering+a+CC+non-committer+Onboarding+Runbook)

- I'm already part of the CC Slack Channel 
- I've been added to the list of [CC's on the Wiki ](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Core+Contributors+to+the+Open+edX+Project)
- Fox has added me to the correct Listaflow list

:)

**Comment by kdmccormick** [comment]
Thanks @cassiezamparini !

@sarina Are Cassie's legal docs all set?

for myself:

### Non-Coding CC Onboarding Checklist for Axim On-Call
- [x] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [x] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Set up access for CC in privacy & a11y courses (can skip for now, but let CC know that they may be upcoming)
- [ ] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while).  Keep the ticket open with status “Blocked”, until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [x] Invite the CC to the Open edX `#core-contributors` Slack channel and the `@core-contributor-committers` Slack user group
- [ ] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [ ] Look up their record in Salesforce and grant them the Core Contributor role.
- [ ] Send Dean a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). ~Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)~
- [ ] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://github.com/wiki/spaces/COMM/pages/3156344833)).

**Comment by sarina** [comment]
Yes, both parties have signed Cassie's agreement!

**Comment by sarina** [comment]
Oh anyway, Cassie emailed us and has access to Listaflow already.
