### ISSUE TITLE
[GH Request] Onboard hsinkoff

### ISSUE THREAD

**Issue by davidjoy** [openedx/axim-engineering#753]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

hsinkoff

### Start Date

15 May 2023

### Urgency

Medium (< 2 weeks)

**Comment by davidjoy** [comment]
I just put in today as the start date.  The sooner the better, as she's trying to dig in on user access/roles work, but it's not urgent.  Thanks!

**Comment by feanil** [comment]
Invitation sent!  Also, unrelatedly I'm interested in access/roles related work, so I'd love to get an intro and learn more about your goals @hsinkoff @davidjoy .
