### ISSUE TITLE
[GH Request] Review new how to doc

### ISSUE THREAD

**Issue by dianakhuang** [openedx/axim-engineering#754]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

I would love to get a review/merge of a PR I made against the docs site to add a new How To: https://github.com/openedx/docs.openedx.org/pull/330

This is some documentation on how to use a non-CodeCov GitHub action to track coverage in a Python repo.

### Reasoning

We wanted to make this documentation public so anyone in the community could make use of it if they were dissatisfied with CodeCov for any reason. The reason why 2U is interested is because we don't have a CodeCov license for our private repositories and are not planning on getting a license anytime soon.

**Comment by sarina** [comment]
Hey @dianakhuang - this isn't an appropriate use of an Axim on-call request. For review requests, you should reach out to the maintainer(s) of the repository, or directly contact potential reviewers.
