### ISSUE TITLE
Add team arbi-bom in repos

### ISSUE THREAD

**Issue by zubairshakoorarbisoft** [openedx/axim-engineering#755]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Add team `arbi-bom` in the following repositories:

1. xblock-qualtrics-survey
2. staff_graded-xblock
3. DoneXBlock
4. crowdsourcehinter
5. ccx-keys
6. schoolyourself-xblock
7. xblock-submit-and-compare
8. acid-block
9. xblock-free-text-response
10. xblock-image-modal
11. xblock-in-video-quiz

### Reasoning

To enable the reviewers in some repositories, which were disabled before. But currently, due to the in sufficient permission, team `arbi-bom` is not able to tag. For having more context on reason https://github.com/edx/upgrades/issues/111

**Comment by feanil** [comment]
This should be all set.
