### ISSUE TITLE
Set up mail for training.openedx.org

### ISSUE THREAD

**Issue by sarina** [openedx/axim-engineering#762]
See #666 - need to set this up for axim.org

@feanil we're planning to announce the training course next Tuesday. Do you think you can get on this ASAP, so that I can get eduNEXT to configure things properly?

**Comment by feanil** [comment]
This can be updated via the eduNext control center.  I've shared the link with you in a different channel.

**Comment by sarina** [comment]
@feanil I can't change this setting. Do I need to contact support?

![image](https://github.com/openedx/axim-engineering/assets/1985317/2c3acb2d-c045-48b5-b8f6-aa9f55fa36a7)

**Comment by sarina** [comment]
@feanil OK, could you explain the steps to move to openedx.org? Or - since you have access to the edunext control center - would it make more sense for you to do this rather than me be a go-between?

**Comment by feanil** [comment]
Depends on urgency, I can take a look at this late next week if it is not urgent.  The steps for moving would be the same as the steps for moving to the axim.org domain.  Just update any from email addersses to use the `@openedx.org` email addresses and in your support ticket for the Email host user, ask them that you want to move to the `openedx.org` domain for the Email host user.  Let me know if you'd like me to take it on next Thursday or Friday.

**Comment by sarina** [comment]
Things are working right now (emails are not caught by spam), and we're announcing the course on Tuesday, so I'd like to be in the middle of doing a change right now since I don't fully understand the host user stuff and not sure I can do it without your help.

If you could get to it in the next few weeks I think that would be best.

**Comment by feanil** [comment]
Ok, I'll put it on my todo list and try to get it going next week.

**Comment by feanil** [comment]
@sarina this should be all set now.  The e-mail will all come from the `@training.openedx.org` subdomain.  I went with this instead of having the mail come from `openedx.org` or `axim.org` because I felt it would be safer to give Mailgun access to only send for a subdomain rather than send verifiable e-mails as any email address in either of those two top level domains.

**Comment by sarina** [comment]
thanks!!
