### ISSUE TITLE
[GH Request] Remove outside collaborators

### ISSUE THREAD

**Issue by sarina** [openedx/axim-engineering#765]
### Firm Name

Axib

### Urgency

Low (2 weeks)

### Problem/Request

Two people have been added as outside collaborators:

![image](https://github.com/openedx/axim-engineering/assets/1985317/9765c092-5ce4-47e2-8922-83584d384489)

https://github.com/orgs/openedx/outside-collaborators

Need to remove them as outside collaborators, find out who did it, and create a proper Access ticket for these individuals

### Reasoning

We don't allow outside collaborators on the openedx GitHub. All users must be part of the org and access must be requested via one of these GitHub request tickets

**Comment by sarina** [comment]
@kelketex or @navinkarkera do you know who added you as an outside collaborator?

**Comment by sarina** [comment]
@kelketek

**Comment by Kelketek** [comment]
@sarina , the explanation @bmtcril just gave sounds right to me.

**Comment by bmtcril** [comment]
They've been removed an no longer show up as outside collaborators. I don't think either of them need specific permissions on those repos at this time, but I was already in the process of writing a CC nomination for Navin to a few repos so this is good timing. 

I think we can close this?

**Comment by sarina** [comment]
thanks Brian!
