### ISSUE TITLE
[GH Request] Add Brian Smith to the Heroku `openedx` team

### ISSUE THREAD

**Issue by arbrandes** [openedx/axim-engineering#767]
### Firm Name

Axim

### Urgency

High (< 3 days)

### Requested Change

Can we please add @brian-smith-tcril to the Heroku `openedx` team?  

### Reasoning

This will allow Brian to manage the backend API instances for the take-home exercises that are being sent out next Tuesday, May 30.

**Comment by arbrandes** [comment]
CC @brian-smith-tcril, @feanil.

**Comment by feanil** [comment]
I sent Brian an Invite, this should be all set!

**Comment by arbrandes** [comment]
Thank you, @feanil!
