### ISSUE TITLE
tCRIL is shown in the description of the Open edX projects in GH.

### ISSUE THREAD

**Issue by ehuthmacher** [openedx/axim-engineering#768]
The wording of tCRIL needs to be replaced with Axim Collaborative in the Open edX Projects in GH.

**Comment by kdmccormick** [comment]
Hi @ehuthmacher , I went through [these projects](https://github.com/orgs/openedx/projects) and update tCRIL->Axim in a few places. Just in case I missed it, was there a specific page that needed updating?

**Comment by ehuthmacher** [comment]
Great, thank you @kdmccormick ! I just noticed it on the GH project boards for the Translation & Marketing WGs. I'll notify you, if I see more.

**Comment by kdmccormick** [comment]
No problem 👍🏻
