### ISSUE TITLE
[GH Request] Add Katrina Nguyen to push-pull-all

### ISSUE THREAD

**Issue by bcitro** [openedx/axim-engineering#770]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

Please add Katrina Nguyen (@katrinan029) to the openedx/push-pull-all github team (https://github.com/orgs/openedx/teams/push-pull-all/members).

Reason for high urgency: Katrina is currently blocked on merging code for a project due to missing this permission.

### Reasoning

As part of her role responsibilities, Katrina will need permissions to push to repos which are managed by push-pull-all.

**Comment by feanil** [comment]
@bcitro can you provide more context on what teams Katrina is working on and what repos she'll need access to as a result of that?  While we are resolving access, Katrina should still be able to make personal forks for the repos that they need to work in and make PRs that other teammates(those who are reviewing the changes) can merge so I don't think this is actually high urgency.

**Comment by georgebabey** [comment]
@feanil Katrina is on our enterprise team (quokkas) so you can copy permissions from @alex-sheehan-edx. Thanks!

**Comment by feanil** [comment]
@georgebabey @bcitro Katrina is already on the `quokkas` team, so this should be all set, are there specific repos that Katrina needs for her daily work that she does not have access to?

**Comment by georgebabey** [comment]
@feanil I'll preface this by saying I know there is a desire to move away from push-pull-all, which is a follow up step after we clean up the groups (working with @kdmccormick on that now). 

Until that new structure is in place, and enterprise particularly is working across many repos, may we continue to get new hires into that group?

**Comment by feanil** [comment]
@georgebabey I've added Katrina to push-pull-all, but it would be useful to understand what was missing from the Quokkas github team that needs to be added so that we can start moving towards more granular teams.

**Comment by feanil** [comment]
@georgebabey I spoke with Kyle, we were a bit mis-aligned, apologies for that, it sounds like we're circling back to this in earnest in a few weeks(post Jun 15th) so I'm happy to just have this cleanup happen as a part of that.
