### ISSUE TITLE
[GH Request] <Need to be able to add community members to the GH Project Boards for the Marketing & Translation WGs>

### ISSUE THREAD

**Issue by ehuthmacher** [openedx/axim-engineering#771]
### Firm Name

Eden

### Urgency

High (< 3 days)

### Requested Change

I am the organizer of both the Marketing & Translation WG and need to be able to add new members to each of the GH project boards. I currently do not have such permissions. 

### Reasoning

I need to be able to add members of the WGs, so that I can assign individual tickets to them.

**Comment by kdmccormick** [comment]
@ehuthmacher , I have made you admin on both projects: https://github.com/orgs/openedx/projects/49 and https://github.com/orgs/openedx/projects/34. You should be able to add collaborators by going to the dot menu in the top-right corner -> Settings -> Manage Access.

Furthermore I've made you a maintainers of these teams: https://github.com/orgs/openedx/teams/marketing-wg-triage and https://github.com/orgs/openedx/teams/wg-translations-triage. You can now add and remove folks from those teams, which grant the ability to manage issues in the Marketing WG and Translations WG repositories, respectively.

Unfortunately, GitHub requires that all project collaborators and team members be members of the openedx GitHub organization, for which I cannot grant you admin access. If you find WG collaborators who are not a member of the openedx GitHub organization ([the list is here](https://github.com/orgs/openedx/people))  then open up a a followup request and we will make sure they get added. Thanks!

**Comment by ehuthmacher** [comment]
@kdmccormick I believe that Ed and Sarina already made me admins for each board. The "manage access" function to invite collaborators is not working for me. Ed mentioned that I may need the overall admin access for the Open edX GH org. What are your concerns for making me an admin?

**Comment by kdmccormick** [comment]
@ehuthmacher Got it. I'm fairly certain that the "manage access" function isn't working because the people you want to add aren't members of the openedx organization in GitHub. Could you confirm whether [they are members](https://github.com/orgs/openedx/people)?

> What are your concerns for making me an admin?

The same concerns we would have for anyone 🙂  GH admin rights grant the ability to change actively-deployed production code, so we adhere to the [principle of least privilege](https://csrc.nist.gov/glossary/term/least_privilege). Any changes of them also require a Core Contributor vote.

@e0d @sarina How would you recommend Eden invite folks from the Marketing and Translation WG to the GH org? Should she just ping on-call whenever it comes up?

**Comment by sarina** [comment]
@kdmccormick Our policy on adding people to the org or changing access permissions is that a GH Request ticket needs to be filed, as an audit log of what access changes were made. So, when there are new marketing team members, please file an access ticket to get them access. Thanks!

**Comment by ehuthmacher** [comment]
@kdmccormick Thank you for your feedback. The people that I was trying to add are already members of the Open edX GH org (e.g.  ayazquraishi, anapgarciag. Please advise.

**Comment by kdmccormick** [comment]
@ehuthmacher these accounts are not in the openedx GitHub org:

* @anapgarciag 
*  @ayazquraishi

Are those the right accounts? If so, would you like me to invite them to the org now (and is there anyone else you'd like me to add now)?

**Comment by ehuthmacher** [comment]
@kdmccormick Was  https://github.com/TanahaRG in the Open edX GH org. I also could not add her. The "manage attendees" button in the settings menu is disabled for me, even though I am the admin of the work boards. Not sure how we can fix this. Please advise.

**Comment by ehuthmacher** [comment]
@kdmccormick I was also not able to add Pierre Mailhot and Dean Matthew to the Translation WG board, who I know are part of the Open edX GH org

**Comment by kdmccormick** [comment]
@ehuthmacher hmm, is this page available to you? 

https://github.com/orgs/openedx/projects/49/settings/access

Here is what I see on that page:

![image](https://github.com/openedx/axim-engineering/assets/3628148/71bbeb77-d713-4775-8511-90c0d4027390)

**Comment by kdmccormick** [comment]
@ehuthmacher TanahaRG is in the organization.

These three accounts all have pending organization invites (sent to their email):

![image](https://github.com/openedx/axim-engineering/assets/3628148/4e0059ff-c908-4f33-bacf-26eac722221b)

**Comment by ehuthmacher** [comment]
Yes, thank you @kdmccormick It's working now.

**Comment by ehuthmacher** [comment]
@kdmccormick Can you please add jesgreco to the TX WG board?
