### ISSUE TITLE
[GH Request] Onboard <chimsara, yuanyuan-git-tech>

### ISSUE THREAD

**Issue by kmedina2u** [openedx/axim-engineering#772]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Erica Nwoga, @chimsara
* Yuanyuan Zhao, @yuanyuan-git-tech

### Start Date

12 June 2023

### Urgency

Low (2 weeks)

### Special Requests

Emails:

Erica Nwoga - enwoga@2u.com
Yuanyuan Zhao - yzhao@2u.com

Erica and Yuanyuan are part of the incoming 2U intern group

**Comment by kdmccormick** [comment]
Thanks for the heads up. I'll take care of this next week.

**Comment by kdmccormick** [comment]
Welcome @chimsara and @yuanyuan-git-tech ! CLA database has been updated, and GH invites have been sent to your 2U emails.
