### ISSUE TITLE
Establish a structure for teams & permissions

### ISSUE THREAD

**Issue by kdmccormick** [openedx/axim-engineering#773]
Design notes are in https://github.com/openedx/decoupling/issues/60 (yes, that's a restricted issue--if you are reading this ticket and want to know more, let me know and I'll copy some context into this public issue)

It is worth noting that this ticket does **not** encompass cleaning up the existing teams and users. That will be handled in https://github.com/openedx/tcril-engineering/issues/26, either before, after, or before&after we implement the GH access control scheme. While we are in the midst of implementing the access control scheme, we don't want to be messing with the actual set of teams, users, and permissions.

**Comment by kdmccormick** [comment]
[axim-internal proposal](https://docs.google.com/document/d/1Sbnm-2cnasVOC4KIemoL-QxPibhKTRdml4s1pN-X8cM/edit#heading=h.jh53n6rqqg57)

**Comment by feanil** [comment]
There is a public naming convention doc that is related to this: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3555852316/GitHub+Team+Structure

**Comment by kdmccormick** [comment]
Going forward, Axim will use that document ^ when creating new teams.

We still want to rename existing teams [using this plan](https://docs.google.com/spreadsheets/d/1nDWMTbmDHyrwWJsSsyr6d6Bx97IKAoKpm5mSVjRj108/edit#gid=188213499), but I'm putting that on the backburner in order to focus on Content Libraries V2 instead. I expect to be able to work on it again in ~Oct 2023.

**Comment by kdmccormick** [comment]
Update:

* @e0d renamed push-pull-all to 2u-edx-legacy. 
* Remaining the other teams is still back-burnered until October.
* I noted this in [the master plan](https://docs.google.com/spreadsheets/d/1nDWMTbmDHyrwWJsSsyr6d6Bx97IKAoKpm5mSVjRj108/edit#gid=188213499).

**Comment by kdmccormick** [comment]
Done: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3555852316/GitHub+Access+Team+Structure

There are still some holdover old teams; we'll clean those up incrementally over time.
