### ISSUE TITLE
[GH Request] Create GitHub team openedx/2u-security-working-group

### ISSUE THREAD

**Issue by pshiu** [openedx/axim-engineering#774]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

Create a GitHub team named like `openedx/2u-security-working-group` with:

- @alangsto (Alison Langston)
- @timmc-edx (Tim McCormack)
- @ohnickmoy (Nick Moy)
- @alex-sheehan-edx (Alex Sheehan)
- @pshiu (Phil Shiu)
- @rayzhou-bit (Ray Zhou)

### Reasoning

Make sharing GitHub Security Advisories between the 2U SWG and the open source Security WG easier.

**Comment by pshiu** [comment]
Side question: Would we be able to manage the group membership ourselves? Or should we submit a request for every onboard/offboard?

**Comment by kdmccormick** [comment]
Can do. Does the team need any access, or is just for mentioning / organizing folks?

> Side question: Would we be able to manage the group membership ourselves? Or should we submit a request for every onboard/offboard?

Great question, let me talk to the team about that today.

**Comment by kdmccormick** [comment]
If the team grants no repository access, you manage its membership yourselves. Otherwise, changes to it will need to go through Axim requests.

**Comment by pshiu** [comment]
Thanks, Kyle!

> Does the team need any access, or is just for mentioning / organizing folks?

Honestly, I don't think the group will ever require repository access. Right now, this group is just for [adding folks to GitHub Security Advisories](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/adding-a-collaborator-to-a-repository-security-advisory).

**Comment by kdmccormick** [comment]
Sounds good 👍🏻

Here's the new team: https://github.com/orgs/openedx/teams/2u-security-working-group

@pshiu , I marked you and @alangsto are marked as team "maintainers", which means that you can add and remove members and promote other members to maintainers as you please.
