### ISSUE TITLE
[GH Request] Onboard <Fayyaz_Ahmed>

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/axim-engineering#775]
### Firm Name

Edly

### User List (case sensitive!) - Please also include in ticket title

* Fayyaz Ahmed, Fayyaz_Ahmed 
* Gituser = fayyazahmed66
* Nomination link = https://discuss.openedx.org/t/new-core-contributor-nomination-fayyaz-ahmed-from-edly-by-arbisoft/10071

### Start Date

29 February 2022

### Urgency

Low (2 weeks)

**Comment by kdmccormick** [comment]
Congrats Fayyaz! I'll have you onboarded this week.

**Comment by kdmccormick** [comment]
### Coding CC Onboarding Checklist for Axim On-Call

- [ ] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info)

- [ ] Confirm with them that they received the course invitation and have successfully accessed the training course

- [x] Set up access for Committer in privacy & a11y courses (can skip for now, but let CC know that they may be upcoming)

- [ ] Send them the relevant Legal Documents. As a part of the training course, the CC will send an e-mail to the CC admins asking for us to send them the CC Program agreement to sign.

  - [ ] Go to [DocuSign](https://app.docusign.com/).

  - [ ] Create a new document from a template.  The Open edX Core Contributor Agreement template should be shared with you.  Use that template.

  - [ ] Send them the CC Agreement to sign: “Hello <New CC>, Please sign this Open edX CC Agreement, also if you have not done so already, please also sign the [Individual CLA](https://tcril.tfaforms.net/f/individual-cla) with you personal contact information.”

- [ ] Verify with  or Axim Legal that the new Core Contributor successfully completed the required legal documents. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while).  Mark the ticket as “Blocked” until this is done. Once complete, follow the remaining steps.

Upon receipt of legal documents, proceed. They’ll be walked through these steps in the onboarding course, too.

- [ ] Invite the Committer to the Open edX #core-contributors Slack channel and the @core-contributor-committers Slack user group

- [ ] Remind them to add themselves to the relevant shared Slack channel(s) corresponding to their merge accesses (some [additional context](https://docs.google.com/document/d/1-G-v3nrP8RN_j0P8gEsdI0ahdOoJFePiDHFOuPlUjlk/edit#heading=h.wsc5ai1lrvb6) if you’re curious). Here’s a DM you can copy and use: “For the repositories you have merge access to, [please join the Slack room(s) that correspond to your repositories](https://docs.google.com/spreadsheets/d/1ryqbaxMp4x-8Apwss2Br2IOU2UA7zXEI-VDo8dJPb9U/edit#gid=0). These rooms are where to coordinate timing on merging breaking or major changes. Keep in mind that 2U runs CI/CD off the tip of master branches, so major changes will impact their site first. It's generally OK to announce in these rooms that you are merging a pr with 24 hour or more notice (eg, I'm merging this tomorrow at 1500 UTC), and engage in discussion with anyone who expresses concern. These rooms are also a good place to ask for a 2U review on critical/breaking change PRs before you get to the merging state.”

- [ ] Add them to the [Google group](https://groups.google.com/a/axim.org/g/core-contributors-dev). This is very low traffic, meant primarily for announcements we want to be sure get to all developers. Also add them to the [overall CC group](https://groups.google.com/a/axim.org/g/core-contributors/members?pli=1).

- [ ] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).

- [ ] Look up their record in Salesforce and grant them the Core Contributor role.

- [ ] Ensure they have the appropriate GitHub access

  - [ ] Create a new GitHub team with the name: CCP Committer: {Contributor's GitHub user}

  - [ ] Add the appropriate repos to the team and make sure to check that they have the appropriate access (Generally Write or Maintain, occasionally Admin. Whatever is specified in the CC vote).

  - [ ] If the user is in the openedx GitHub org: add them to both CCP Committer: {Contributor's GitHub user} and openedx-triage

  - [ ] If not: invite them to the GitHub org, including those two teams in the invite. They will need to confirm their invite via email.

- [ ] Send  a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact  to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)

- [ ] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://github.com/wiki/spaces/COMM/pages/3156344833)).

**Comment by kdmccormick** [comment]
@fayyazahmed66 could you send me your preferred email address, either here or in a Slack DM, so I could invite you to the CC onboarding course?

**Comment by kdmccormick** [comment]
```[tasklist]
### Non-Coding CC Onboarding Checklist for Axim On-Call
- [ ] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [ ] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Set up access for CC in privacy & a11y courses (can skip for now, but let CC know that they may be upcoming)
- [ ] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while).  Keep the ticket open with status “Blocked”, until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [ ] Invite the CC to the Open edX `#core-contributors` Slack channel and the `@core-contributor-committers` Slack user group
- [ ] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [ ] Look up their record in Salesforce and grant them the Core Contributor role.
- [ ] Send Dean a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)
- [ ] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://github.com/wiki/spaces/COMM/pages/3156344833)).
```

**Comment by fayyazahmed66** [comment]
@kdmccormick  Personal email = fayyazahmedcs@gmail.com
Professional = fayyaz.ahmed@arbisoft.com

**Comment by fayyazahmed66** [comment]
@kdmccormick  I can access CC course. Thanks. 
<img width="1679" alt="Screenshot at Jun 09 10-48-28" src="https://github.com/openedx/axim-engineering/assets/55684124/1da85600-1baa-43ac-b7df-74f44e52bd44">

**Comment by brian-smith-tcril** [comment]
Complete!

**Comment by fayyazahmed66** [comment]
@brian-smith-tcril  I am just waiting for the second last checklist point to complete. 

"Send Dean a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)" 

It's still pending. 
CC: @sarina

**Comment by sarina** [comment]
It will take 1-2 weeks for listaflow, please be patient.
