### ISSUE TITLE
[GH Request] Onboard <swayamrana>

### ISSUE THREAD

**Issue by kmedina2u** [openedx/axim-engineering#778]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Swayam Rana, @swayamrana

### Start Date

12 June 2023

### Urgency

Low (2 weeks)

### Special Requests

Email: srana1@2u.com

Swayam is one of the 2U interns starting on June 12. They will be reporting to Jeremy Bowman

**Comment by kdmccormick** [comment]
Welcome @swayamrana! You're added to the CLA database and an openedx org invite has been sent to your 2U email.
