### ISSUE TITLE
[GH Request] Requesting new repo (@openedx/react-unit-test-utils

### ISSUE THREAD

**Issue by muselesscreator** [openedx/axim-engineering#779]
### Firm Name

2U

### Urgency

High (< 3 days)

### Problem/Request

Request a new openedx repo, under ownership of the 2u Aurora squad, for react unit test utils

### Reasoning

Providing a shared set of unit testing utils for react/MFE environments, specifically that will allow snapshot/unit testing after enzyme deprecation

**Comment by muselesscreator** [comment]
No issues.

**Comment by muselesscreator** [comment]
could I get an update on this? @arbrandes

**Comment by brian-smith-tcril** [comment]
I've created https://github.com/openedx/react-unit-test-utils and given @openedx/content-aurora write access. The repo currently has zero commits, so some of the things from https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html (such as making a well formed README) haven't been done yet.

I'm going to go ahead and close this out now. Please reach out and let me know if there's anything else you need from me!
