### ISSUE TITLE
[GH Request] Onboard <navinkarkera> as CC

### ISSUE THREAD

**Issue by bmtcril** [openedx/axim-engineering#780]
### Firm Name

OpenCraft

### User List (case sensitive!) - Please also include in ticket title

* Navin Karkera, @navinkarkera

Asking for write access to repos: 

- edx-platform
- openedx-events
- event-bus-redis

Nomination: https://discuss.openedx.org/t/core-contributor-nomination-navin-karkera/10193

### Start Date

2023-06-12

### Urgency

Low (2 weeks)

**Comment by brian-smith-tcril** [comment]
@navinkarkera Congrats on CC! Would you like me to send the onboarding course link to your opencraft email or do you have a different email address you'd rather I use? (Feel free to respond here or in a slack DM)

**Comment by navinkarkera** [comment]
@brian-smith-tcril Thank you! Please use my opencraft email.

**Comment by bmtcril** [comment]
@sarina I think this is done, can we confirm that last checkbox that all the legal docs are in order?

**Comment by sarina** [comment]
Yes they are!

**Comment by bmtcril** [comment]
🎉
