### ISSUE TITLE
[GH Request] OmarIthawi rights expansion

### ISSUE THREAD

**Issue by sarina** [openedx/axim-engineering#781]
### Firm Name

Axim

### Urgency

Low (2 weeks)

### Requested Change

Add write access to 

openedx-translations
openedx-atlas

(in a new Translations access group)

for @OmarIthawi

### Reasoning

https://discuss.openedx.org/t/coding-cc-rights-expansion-omar-al-ithawi/10307

**Comment by brian-smith-tcril** [comment]
Done!
