### ISSUE TITLE
[GH Request] Onboard Ian2012

### ISSUE THREAD

**Issue by Ian2012** [openedx/axim-engineering#782]
### Firm Name

eduNEXT

### User List (case sensitive!) - Please also include in ticket title

* Cristhian Garcia, @Ian2012

### Start Date

13 June 2023

### Urgency

Low (2 weeks)

### Special Requests

Requesting CC access for Cristhian Garcia with gh username @Ian2012 to repos:

* [openedx/openedx-event-sink-clickhouse](https://github.com/openedx/openedx-event-sink-clickhouse)
* [openedx/openedx-oars](https://github.com/openedx/openedx-oars)
* [openedx/tutor-contrib-clickhouse](https://github.com/openedx/tutor-contrib-clickhouse)
* [openedx/tutor-contrib-oars](https://github.com/openedx/tutor-contrib-oars)
* [openedx/tutor-contrib-ralph](https://github.com/openedx/tutor-contrib-ralph)
* [openedx/tutor-contrib-superset](https://github.com/openedx/tutor-contrib-superset)
* [openedx/wg-data](https://github.com/openedx/wg-data)
* [openedx/xapi-db-load 1](https://github.com/openedx/xapi-db-load)

Reason: https://discuss.openedx.org/t/core-contributor-nomination-cristhian-garcia/10231

Instructions: Please give access to the repos listed above

**Comment by Ian2012** [comment]
@brian-smith-tcril cristhian.garcia@edunext.co would be the best email. Thanks

**Comment by sarina** [comment]
@brian-smith-tcril Cristian's paperwork has been processed.

**Comment by brian-smith-tcril** [comment]
Checklist complete!
