### ISSUE TITLE
[GH Request] Onboard Noble Grant

### ISSUE THREAD

**Issue by aheykamp2u** [openedx/axim-engineering#783]
### Firm Name

2U / edX

### User List (case sensitive!) - Please also include in ticket title

Noble Grant, @NGRANT2U

### Start Date

June 12, 2023

### Urgency

High (< 3 days)

### Special Requests

Noble is a new intern at 2u. It's possible another account was added instead, but this is the account he would like to use for his work at 2u.

**Comment by kdmccormick** [comment]
FYI @openedx/axim-oncall (re-pinging you Brian since I'd forgotten to add you to the oncall group before)

**Comment by brian-smith-tcril** [comment]
@georgebabey, after checking in salesforce it seems @aheykamp2u doesn't have the CLA Approver role. Is this request approved?

**Comment by ashley3** [comment]
Am I able to approve this request as Andrew's manager? If so, I approve :)

**Comment by brian-smith-tcril** [comment]
@ashley3 it looks like you don't have the CLA Approver role in salesforce. @georgebabey is that something I should add to @ashley3's contact entry?

**Comment by georgebabey** [comment]
Yikes - sorry for the delay here. This is approved for Noble

**Comment by brian-smith-tcril** [comment]
Added to CLA database. Invited to the Open edX GitHub org, as well as the `openedx-triage` and `push-pull-all` teams.
