### ISSUE TITLE
[GH Request] Update Read the Docs for Palm

### ISSUE THREAD

**Issue by mtyaka** [openedx/axim-engineering#785]
### Firm Name

BTR WG

### Urgency

High (< 3 days)

### Problem/Request

We just cut the `open-release/palm.1` tag and need someone from Axim to perform [Step 4a from the "Process to create an Open edX Release" page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#4a.-Ask-Axim-to-un-hide-the-release-versions-of-each-book) (pointing Read the Docs to the new version).

### Reasoning

Following documented steps at the https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release after cutting a new release tag.

**Comment by brian-smith-tcril** [comment]
It looks like this was addressed by https://github.com/openedx/docs.openedx.org/pull/341, is there anything else needed or can I close this?
