### ISSUE TITLE
[GH Request] Add names as maintainers of xblock-skill-tagging

### ISSUE THREAD

**Issue by sameenfatima78** [openedx/axim-engineering#788]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

Request to add me and Irfan as maintainers of https://github.com/openedx/xblock-skill-tagging.

Usernames: `sameenfatima78`, `irfanuddinahmad`

### Reasoning

The repo xblock-skills-tagging was created by OpenCraft team as part of a blended project with our 2U/edX team (Enterprise-Markhors). 

We have read the maintainership responsibilities as outlined in https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html and agree to it.

**Comment by brian-smith-tcril** [comment]
To be listed in backstage you should be able to just add names to `catalog-info.yaml` as described here https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html

Is there something else you needed?
