### ISSUE TITLE
[GH Request] Create a new team on Github

### ISSUE THREAD

**Issue by sameenfatima78** [openedx/axim-engineering#790]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

Request to create a new team on Github and add me and Irfan there. 

Usernames: `sameenfatima78`, `irfanuddinahmad`

### Reasoning

We want to add ourselves as maintainers of xblock-skills-tagging in catalog-info.yml file but the template suggests that only group names can be added under "owners". 

https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0001-use-backstage-to-support-maintainers.html#references

**Comment by brian-smith-tcril** [comment]
What would you like the team name to be? Since this is a 2U team it should follow the naming convention of `2U-*`

**Comment by sameenfatima78** [comment]
@brian-smith-tcril No strict preferences but how does `2U-xblockskilltagging-maintainers` sound?

**Comment by brian-smith-tcril** [comment]
Team created, members added! https://github.com/orgs/openedx/teams/2u-xblockskilltagging-maintainers
