### ISSUE TITLE
[GH Request] Onboard tasneem-titus

### ISSUE THREAD

**Issue by mmnxumalo** [openedx/axim-engineering#792]
### Firm Name

EdX & Getsmarter

### User List (case sensitive!) - Please also include in ticket title

Tasneem Titus,tasneem-titus

### Start Date

19 June 2023

### Urgency

High (< 3 days)

### Special Requests

push-pull-all

**Comment by brian-smith-tcril** [comment]
@mmnxumalo I don't see a record for you in salesforce. @georgebabey is this request approved?

**Comment by mmnxumalo** [comment]
@brian-smith-tcril  this request is for @tasneem-titus and there's a case on salesforce

**Comment by georgebabey** [comment]
This is approved, but is a dupe of https://github.com/openedx/axim-engineering/issues/805

**Comment by brian-smith-tcril** [comment]
Added to CLA database. Invited to the Open edX GitHub org, as well as the `openedx-triage` and `push-pull-all` teams.
