### ISSUE TITLE
[GH Request] Help cleaning up @edx/react-unit-test-utils npm package

### ISSUE THREAD

**Issue by muselesscreator** [openedx/axim-engineering#803]
### Firm Name

2U

### Urgency

High (< 3 days)

### Problem/Request

Help fix the permissions on the @openedx/react-unit-test-utils repo to closer match frontend-platform's, so that its release jobs succeed, and help fix the release config so that the npm package points correctly to the dist folder.

### Reasoning

@openedx/react-unit-test-utils repo is failing to create releases in its actions due to permissions (https://github.com/openedx/react-unit-test-utils/actions/runs/5338320373/jobs/9675530701)

Also, the published npm package does not point to the dist folder, despite the .releaserc file attempting to force it to do so.

**Comment by arbrandes** [comment]
I'll take this one: I want to figure out how to make semantic releases work.

**Comment by arbrandes** [comment]
Done.  What was missing (from a permissions point of view) was for the [edx-semantic-release](https://github.com/orgs/openedx/people/edx-semantic-release) user to have write access to the react-unit-test-utils repository.
