### ISSUE TITLE
[GH Request] Onboard tasneem-titus

### ISSUE THREAD

**Issue by GEksteen** [openedx/axim-engineering#805]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Full name = Tasneem Titus
Username =  tasneem-titus

### Start Date

15 May 2023

### Urgency

High (< 3 days)

### Special Requests

This is currently preventing Tasneem from pushing work done and completing
her tickets. Please let me know if you need any further details.

**Comment by brian-smith-tcril** [comment]
@GEksteen I don't see you in salesforce, @georgebabey is this request approved?

**Comment by GEksteen** [comment]
Good morning Brian, 

Hope you are doing well. 

Is there any info I can provide that would assist in completing this request? 
This request was logged to our Helpdesk queue, I then logged this on behalf of the user. 

Kind regards,

Gerard

**Comment by georgebabey** [comment]
Apologies for the slow reply - this is approved and Gerard (@GEksteen) is from our IT dept.
