### ISSUE TITLE
Allow @openedx-namespaced NPM packages to be built

### ISSUE THREAD

**Issue by arbrandes** [openedx/axim-engineering#806]
### Description

As a first step in the direction of renaming all relevant `@edx` NPM packages to `@openedx`, allow new NPM packages in the org to be built in the `@openedx` namespace.

We should also take the opportunity to start investigating how to make the future renaming process more palatable (such as by using some form of aliasing).

### Further info

* https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

**Comment by feanil** [comment]
@arbrandes do you have a package in mind that we can start publishing to the new org today?  Are there defaults we need to change somewhere in our templates?

**Comment by arbrandes** [comment]
I'm not aware of an openedx cookiecutter or template for JS libraries, so I don't think we have to worry about a default.  I just checked for related developer documentation, but couldn't find any, either.

That said, it wouldn't hurt to open a PR to frontend-template-application that changes the namespace accordingly, even if it doesn't get published anywhere. 🤷🏼‍♂️ 

As for a package we could rename today, I think the recently-added [react-unit-test-utils](https://github.com/openedx/react-unit-test-utils) would be the best candidate.  Not sure if it's even used by any MFEs, yet.  We'll just have to coordinate with @muselesscreator.  (Hey Ben! 😉 )

**Comment by feanil** [comment]
I'm gonna try this with the https://github.com/openedx/brand-openedx package to figure out the details since that package is presumably fully under our purview and probably touches many other packages.

**Comment by feanil** [comment]
Copying from the main ticket to keep track of here.

- [ ] Do a final publish of the package into the edx org if the latest code hasn't already been published.
- [ ] Update the code to scope the package to the `openedx` NPM org.
- [ ] Publish to the `openedx` org at the same version as in the `edx` org.
    * *Outstanding Question*: Will Semantic release let us do that?  Might need to do a minor version bump.
- [ ] Update all projects in the `openedx` org that use this package to use the new `openedx` scoped one.
- [ ] Notify community of the change and newly available package so they can update any code they have.

**Comment by feanil** [comment]
The announcement was made over here: https://discuss.openedx.org/t/npm-scope-change-for-open-edx-packages/11481

We can now easily build and publish to the `openedx` NPM scope from the openedx org.  The [npm-publish workflow template](https://github.com/openedx/.github/blob/master/workflow-templates/npm-publish.yml) has the correct settings to use.
