### ISSUE TITLE
[GH Request] Enable Renovate for my repo

### ISSUE THREAD

**Issue by leangseu-edx** [openedx/axim-engineering#810]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

enable renovate for https://github.com/openedx/frontend-app-ora-grading

### Reasoning

Maintaining dependency for the project.

**Comment by bmtcril** [comment]
@leangseu-edx it looks like you've got a valid json file already, so I've turned it on. Let us know if you run into any issues!

**Comment by leangseu-edx** [comment]
@bmtcril , thank you so much. I would like to know what is the automation schedule? I just want to verify it work as intended.

**Comment by bmtcril** [comment]
According to your config it's `"schedule:weekly",` which extends `"schedule:earlyMondays"`, which is `"before 4am on Monday"`. I assume that's all on the `"America/New_York"` timezone in your config.

https://docs.renovatebot.com/presets-schedule/#scheduleearlymondays

**Comment by bmtcril** [comment]
Today's job is still in a pending state, but it does seem like it found that update on previous days. There doesn't seem to be a status page for the Mend Renovate GitHub app, so I'll keep an eye on it. There are literally no actions we can take for this.

**Comment by bmtcril** [comment]
FWIW I've opened a discussion here: https://github.com/renovatebot/renovate/discussions/23281

**Comment by bmtcril** [comment]
According to that discussion, the job can run any time of the day until we merge one of their PRs into that repo. Then it will happen within a 3hr window on subsequent weeks.

**Comment by bmtcril** [comment]
So this eventually ran, but it looks like no PR was created. Looking at the logs it seems like it's finding things to upgrade, but not doing it because it's not falling within the schedule. I think you probably want to change your renovate.json to daily until we can get one merged, just to work around this silliness.

**Comment by leangseu-edx** [comment]
I just change that to daily. I will keep an eye on it.

**Comment by leangseu-edx** [comment]
It doesn't seems to create pr at all.

**Comment by bmtcril** [comment]
It's always skipping it because it's never running before 4am:

```
DEBUG: Checking schedule(before 4am, America/New_York) (branch="renovate/major-react-router-monorepo")
DEBUG: Found timezone: America/New_York (branch="renovate/major-react-router-monorepo")
DEBUG: Adjusting now for timezone (branch="renovate/major-react-router-monorepo")
DEBUG: Checking 1 schedule(s) (branch="renovate/major-react-router-monorepo")
DEBUG: Checking schedule "before 4am" (branch="renovate/major-react-router-monorepo")
{
  "parsedSchedule": {
    "schedules": [
      {
        "t_b": [
          14400
        ]
      }
    ],
    "exceptions": [],
    "error": -1
  }
}

DEBUG: Package not scheduled (branch="renovate/major-react-router-monorepo")
DEBUG: Skipping branch creation as not within schedule (branch="renovate/major-react-router-monorepo")
```

I think the next suggestion is to just widen the window:

```
{
  "schedule": ["before 11pm"]
}
```

**Comment by leangseu-edx** [comment]
The jobs run as soon as I add that. https://github.com/openedx/frontend-app-ora-grading/commits/master. Maybe I should add that with weekly now?

**Comment by bmtcril** [comment]
Ay there we go, I think it should work if you change it back to weekly it should run as expected 🤞
