### ISSUE TITLE
[GH Request] Offboard ansabgillani

### ISSUE THREAD

**Issue by kashifch** [openedx/axim-engineering#816]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Syed Ansab Waqar Gillani, ansabgillani

### End Date

10 July 2023

### Urgency

High (< 3 days)

**Comment by arbrandes** [comment]
Removed from GH org, and disassociated with entity CLA.  However, I do not have enough Salesforce permissions to change the contact owner.  Is that something you can help me with, @e0d?

**Comment by e0d** [comment]
Done, and removed their Org association so they now have a Household account.
