### ISSUE TITLE
[GH Request] Onboard <Toxicom>

### ISSUE THREAD

**Issue by kmedina2u** [openedx/axim-engineering#817]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Tomas Leonavicius, @Toxicom

### Start Date

10 July 2023

### Urgency

Low (2 weeks)

### Special Requests

Email: [tleonavicius@2u.com](mailto:tleonavicius@2u.com)

Mirror access of Darius Zivertas, @zzzarius if possible. Business context from Tomas:

"I am an Adapt Agency contractor that's assigned to work with the SEO
 Attract team on Prospectus ([edx.com](https://edx.com/)).
 I have been onboarded as a replacement for Darius Zivertas who is on
 holiday and as such, the access I'm asking should ideally mirror Darius'
 access so that I can continue working without any blockers."

**Comment by arbrandes** [comment]
Done!
