### ISSUE TITLE
[GH Request] Associate Bitergia contributions to eduNEXT

### ISSUE THREAD

**Issue by Ian2012** [openedx/axim-engineering#818]
### Firm Name

eduNEXT

### Urgency

Low (2 weeks)

### Problem/Request

Contributions for the username [**Ian2012**](https://openedx.biterg.io/app/kibana#/dashboard/Overview?_g=()&_a=(description:'Overview%20Panel%20by%20Bitergia',filters:!(('$state':(store:appState),meta:(alias:'Empty%20Commits',disabled:!f,index:git,key:files,negate:!t,params:(query:'0',type:phrase),type:phrase,value:'0'),query:(match:(files:(query:'0',type:phrase)))),('$state':(store:appState),meta:(alias:Bots,disabled:!f,index:git,key:author_bot,negate:!t,params:(query:!t,type:phrase),type:phrase,value:true),query:(match:(author_bot:(query:!t,type:phrase))))),fullScreenMode:!f,options:(darkTheme:!f,useMargins:!t),panels:!((embeddableConfig:(title:Git),gridData:(h:8,i:'1',w:16,x:0,y:20),id:git_main_numbers,panelIndex:'1',title:Git,type:visualization,version:'6.8.6'),(embeddableConfig:(title:Commits,vis:(legendOpen:!f)),gridData:(h:8,i:'2',w:16,x:0,y:28),id:git_evolution_commits,panelIndex:'2',title:'Git%20Commits',type:visualization,version:'6.8.6'),(embeddableConfig:(title:Authors,vis:(legendOpen:!f)),gridData:(h:8,i:'3',w:16,x:0,y:36),id:git_evolution_authors,panelIndex:'3',title:'Git%20Authors',type:visualization,version:'6.8.6'),(embeddableConfig:(title:Organizations),gridData:(h:20,i:'5',w:16,x:16,y:0),id:git_commits_organizations,panelIndex:'5',title:Organizations,type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Github%20Issues'),gridData:(h:8,i:'31',w:16,x:32,y:20),id:github_issues_main_metrics,panelIndex:'31',title:'Github%20Issues',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'GitHub%20Issues'),gridData:(h:8,i:'32',w:16,x:32,y:28),id:github_issues_evolutionary,panelIndex:'32',title:'GitHub%20Issues',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'GitHub%20Issues%20Submitters'),gridData:(h:8,i:'33',w:16,x:32,y:36),id:github_issues_evolutionary_submitters,panelIndex:'33',title:'GitHub%20Issues%20Submitters',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'GitHub%20Pull%20Requests'),gridData:(h:8,i:'34',w:16,x:16,y:20),id:github_pullrequests_main_metrics,panelIndex:'34',title:'GitHub%20Pull%20Requests',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Pull%20Requests'),gridData:(h:8,i:'35',w:16,x:16,y:28),id:github_pullrequests_pullrequests,panelIndex:'35',title:'GitHub%20Pull%20Requests',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Pull%20Request%20Submitters',vis:(legendOpen:!f)),gridData:(h:8,i:'36',w:16,x:16,y:36),id:github_pullrequests_submitters_evolutionary,panelIndex:'36',title:'GitHub%20Pull%20Request%20Submitters',type:visualization,version:'6.8.6'),(embeddableConfig:(title:Discourse),gridData:(h:8,i:'55',w:16,x:0,y:44),id:discourse_main_metrics,panelIndex:'55',title:Discourse,type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Questions%20and%20Answers'),gridData:(h:8,i:'56',w:16,x:0,y:52),id:discourse_qa_evolutionary,panelIndex:'56',title:'Discourse%20Questions%20and%20Answers',type:visualization,version:'6.8.6'),(embeddableConfig:(title:Participants),gridData:(h:8,i:'57',w:16,x:0,y:60),id:discourse_qa_evolutionary_submitters,panelIndex:'57',title:'Discourse%20Participants',type:visualization,version:'6.8.6'),(embeddableConfig:(title:Slack),gridData:(h:8,i:'65',w:16,x:16,y:44),id:slack_main_numbers,panelIndex:'65',title:Slack,type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Slack%20Messages'),gridData:(h:8,i:'66',w:16,x:16,y:52),id:slack_messages_evolutionary,panelIndex:'66',title:'Slack%20Messages',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Slack%20Participants'),gridData:(h:8,i:'67',w:16,x:16,y:60),id:slack_participants_evolutionary,panelIndex:'67',title:'Slack%20Participants',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Git%20Top%20Authors',vis:(params:(config:(searchKeyword:Ian201),sort:(columnIndex:!n,direction:!n)))),gridData:(h:20,i:'111',w:16,x:0,y:0),id:git_overview_top_authors,panelIndex:'111',title:'Git%20Top%20Authors',type:visualization,version:'6.8.6'),(embeddableConfig:(title:'Git%20Top%20Projects',vis:(params:(config:(searchKeyword:''),sort:(columnIndex:!n,direction:!n)))),gridData:(h:20,i:'112',w:16,x:32,y:0),id:git_overview_top_projects,panelIndex:'112',title:'Git%20Top%20Projects',type:visualization,version:'6.8.6')),query:(language:lucene,query:Ian2012),timeRestore:!f,title:Overview,viewMode:view)) appears without an organization.

I need to be correctly associated with the organization eduNEXT.

Thanks

### Reasoning

Doesn't apply

**Comment by arbrandes** [comment]
@e0d, I'm told I should send this one your way.  Is that ok?

**Comment by e0d** [comment]
I've merged two profiles with that GH username and confirmed the merged profile is associated with eduNEXT.  There's some eventual consistency time, but this should be corrected in a bit.

**Comment by Ian2012** [comment]
@e0d thanks for your help
