### ISSUE TITLE
[GH Request] Onboard 2U>Pod1 team members

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#819]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

This is a 2U employee:
- Brandon Bodine, username: BrandonHBodine

These are 2U contractors, please grant standard 2U employee access:
- Daniel Dominguez, username: dan1d
- Maria Guillermina Vescovo, username: Guilleves
- Rodrigo Martin, username: Rodra
- Jorg Are, username: hajorg

### Start Date

July 10, 2023

### Urgency

Medium (< 2 weeks)

**Comment by arbrandes** [comment]
Done!
