### ISSUE TITLE
[GH Request]  create frontend-app-ora repository

### ISSUE THREAD

**Issue by leangseu-edx** [openedx/axim-engineering#821]
### Firm Name

2U

### Urgency

High (< 3 days)

### Problem/Request

- Name: frontend-app-ora
- Visibility: Private
- Summary: Open Response Assessment MFE - Allows graders to easily review, evaluate and grade ORAs
- Organization: openedx
- Permissions:
  - Push: Anyone
  - Pull: Anyone
- Default branch name: Master
- Protected Branch: Yes
- License:  Ask for the AGPL license as per Open Source's policy. Specifically ask for GNU Affero General Public License v3.0. 
- Description: Open Response Assessment MFE - Allows graders to easily review, evaluate and grade ORAs

Can you make you also add admin permission to https://github.com/orgs/edx/teams/content-aurora

### Reasoning

we are making a new project for ora frontend

**Comment by arbrandes** [comment]
Created: https://github.com/openedx/frontend-app-ora-grading.  @openedx/content-aurora has write-access.

Note: we're no longer adding new repos to @openedx/push-pull-all.  People that need write access need to be added to appropriately specific teams.

**Comment by arbrandes** [comment]
@leangseu-edx, I've been told (and double-checked) not to give out admin access for new repositories, apologies.

I also checked on `master` vs `main`, and new repositories are supposed to use `main`.

Let me know what other settings you need changed, though, and I'll be happy to modify them for you!

**Comment by leangseu-edx** [comment]
Here a few things I would like to have:
- add https://github.com/orgs/openedx/teams/edx-transifex-translations to contributor with permission to write
- make `master` default branch because some of the edx script still doesn't work with `main` and I do not want to deal with that.
- add branches protection rule for `master`
<img width="885" alt="image" src="https://github.com/openedx/axim-engineering/assets/83240113/a8059f33-4b35-4d58-b762-cd7be2c3086b">

That is it. Thank you.

**Comment by davidjoy** [comment]
FYI @arbrandes, if you tag `https://github.com/orgs/openedx/teams/push-pull-all` then everyone in that group gets a mention and gets notified.  I couldn't figure out why I was seeing this show up in my inbox. 😅

**Comment by leangseu-edx** [comment]
> Here a few things I would like to have:
> 
> * add https://github.com/orgs/openedx/teams/edx-transifex-translations to contributor with permission to write
> * make `master` default branch because some of the edx script still doesn't work with `main` and I do not want to deal with that.
> * add branches protection rule for `master`
> 
> <img alt="image" width="885" src="https://user-images.githubusercontent.com/83240113/253583686-a8059f33-4b35-4d58-b762-cd7be2c3086b.png">
> That is it. Thank you.

@arbrandes can you complete these request?

**Comment by leangseu-edx** [comment]
Looking good. Thank you.

**Comment by arbrandes** [comment]
And @davidjoy (and everybody else!), apologies for that inadvertent mass ping! 😅
