### ISSUE TITLE
[GH Request] Onboard wasmussen2u

### ISSUE THREAD

**Issue by HacDmv** [openedx/axim-engineering#823]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Bill Asmussen, wasmussen2u, wasmussen@2u.com

### Start Date

7/10/2023

### Urgency

High (< 3 days)

**Comment by ormsbee** [comment]
@georgebabey: Is it okay to proceed with this ticket?

**Comment by georgebabey** [comment]
@ormsbee Approved

**Comment by ormsbee** [comment]
Added to openedx-triage and push-pull-all groups, as well as CLA database. Please note that the CLA database is updated via daily export, so it might take a day for the bot to get the update.
