### ISSUE TITLE
[GH Request] Change openedx-events library license

### ISSUE THREAD

**Issue by felipemontoya** [openedx/axim-engineering#826]
### Firm Name

eduNEXT

### Urgency

Low (2 weeks)

### Problem/Request

Change the license of `openedx-events` from AGLP V3 to Apache 2.0.

### Reasoning

2 different members of 2U have requested that we change the AGPL V3 license of the `openedx-events` repository to something that allows having private repos with a dependency on `openedx-events`.

The issue were the conversation is happening: https://github.com/openedx/openedx-events/issues/184.

Drawing from previous experience in this project the xblock library was licensed as Apache 2.0 I believe for this same reason.

I believe this decision should apply to openedx-filters as well, but I understand if they need to be made separately.

Finally, as co-author of the library, I should state my personal opinion on the matter. I think given that openedx-events are the gateway to event bus which already separates different pieces of running code neatly, there is already a hard API there that could be leveraged through many workarounds to keep code private and not have a dependency on `openedx-events`. It is not a matter of the license not allowing developers to use events this way, but more like officially validating this option.
I'd would like to see more organizations collaborating on the core and having more and better defined events. I don't mind that implementations of what is done after the event propagates can remain private. History on this project has shown that is is not the publication of the code, but the documentation, maintenance and ongoing on-boarding of new comers what makes a package valuable.

**Comment by bmtcril** [comment]
@arbrandes I can take this one if you like, since I've been on it for a bit. It's just waiting on legal to get back from PTO to get an official resolution.

**Comment by arbrandes** [comment]
Alright, thank you @bmtcril!  I'm reassigning it to you.

**Comment by bmtcril** [comment]
This should be resolved with https://github.com/openedx/openedx-events/pull/258 . I'll close this when that merges.
