### ISSUE TITLE
[GH Request] Need write access on discoery repo to create a PR

### ISSUE THREAD

**Issue by jawad-khan** [openedx/axim-engineering#827]
### Firm Name

2U

### Urgency

High (< 3 days)

### Problem/Request

I need to create a pull request on discovery [repo](https://github.com/openedx/course-discovery) for some changes related to mobile work. I need write access for pushing my code on the repo. 

### Reasoning

We are having errors in logs for ecommerce api requests and some course authors are unable to update their courses.

**Comment by arbrandes** [comment]
@jawad-khan, I see you're already in ecommerce-maintainers, but I need confirmation from an approver other than yourself.  Maybe somebody in @openedx/course-discovery-maintainers can give a thumbs up?

**Comment by zawan-ila** [comment]
Hi @jawad-khan @arbrandes, the recommended way to contribute to discovery, at least since I've been around, has been to fork the repo and push to your fork. That should not require write access.

**Comment by arbrandes** [comment]
@zawan-ila, that's what's supposed to happen usually, yeah.  @jawad-khan, is there any reason why the workflow @zawan-ila describes wouldn't work for you?

**Comment by arbrandes** [comment]
Excellent, thank you for confirming!
