### ISSUE TITLE
[GH Request] add more members to 2u-digital-learning-experience and add one repo

### ISSUE THREAD

**Issue by ashultz0** [openedx/axim-engineering#828]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

I need to have some more 2U developers added to https://github.com/orgs/openedx/teams/2u-digital-learning-experience as we onboard them or otherwise reorg

name/email/github

David Nuon / dnuon@2u.com / davidnuon
German Olle / golle@2u.com / germanolleunlp
Simon Chen / schen2@2u.com / schenedx
Alexander Telischak / atelischak@2u.com / aethant

some of these are repeats from the earlier ticket, I'm unclear what happened to their invites but they weren't working in the repos yet so it was easy for them to lose the invite. This time I will persecute them about it and they need it.

Would is be possible to make me and/or simon group membership admins so we can handle this sort of invite ourselves?

In addition to that we're working in **frontend-app-course-authoring** which turns out to be where studio is so we need access to that repo as well. I wouldn't expect to be able to handle that ourselves :)

### Reasoning

getting more 2u devs working in the edx codebase

expanding a bit what the team is working on

**Comment by arbrandes** [comment]
Here's what was done so far:

* gave `openedx/2u-digital-learning-experience` write access to `frontend-app-course-authoring`
* Invited @davidnuon, @germanolleunlp, @schenedx, and @aethant to that team

> Would is be possible to make me and/or simon group membership admins so we can handle this sort of invite ourselves?

I'll have to get back to you on this one!  Let me check with the team.

**Comment by arbrandes** [comment]
@ashultz0, unfortunately we can't allow teams that grant write access to repositories to self-manage.  See [this page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3555852316/GitHub+Team+Structure#Making-Changes) for more information.

**Comment by schenedx** [comment]
@arbrandes I didn't see @germanolleunlp added to the `openedx/2u-digital-learning-experience` team. Can you please double check?

**Comment by arbrandes** [comment]
That's because they did not accept the invitation, yet:

![image](https://github.com/openedx/axim-engineering/assets/759355/6a737285-8a48-4773-a02a-1c7476aba5e6)
