### ISSUE TITLE
[GH Request] <Add Abdul Rafey to axims allowed contributors database><abdulrafey38>

### ISSUE THREAD

**Issue by mbeljoi** [openedx/axim-engineering#832]
### Firm Name

Abdul Rafey (2u)(abdulrafey38)

### Urgency

High (< 3 days)

### Requested Change

Hello,

Please add Abdul Rafey to Axim's (openedx) list of allowed contributors so
that he can contribute to edX repositories.

Github Username: abdulrafey38
2u Email Address: arafey@2u.com

### Reasoning

User needs to contribute to edx repo's

**Comment by arbrandes** [comment]
@georgebabey, do you mind confirming this request?

**Comment by arbrandes** [comment]
Also, @mbeljoi, is there any particular set of repositories this user needs write access to?

**Comment by mbeljoi** [comment]
Hi Bob, please advise if there are any particular sets of repositories
Abdul needs write access to?

On Thu, Jul 20, 2023 at 1:53 PM Adolfo R. Brandes
***@***.***> wrote:
>
> Also, @mbeljoi, is there any particular set of repositories this user needs write access to?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 


Michael Beljoi
Intermediate Support Engineer.

Deneb House, 368 Browning Rd, Woodstock, Cape Town, 7925
Office: +27-21-447-7565
www.2u.com | #NOBACKROW

We’re a purpose-driven business looking for talented people who care
about what they do. Join us at 2u.com/careers/ct/.

This message contains confidential information and is intended only
for the individual named. If you are not the named addressee you
should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system.

**Comment by mbeljoi** [comment]
Hi Michael,

Rafey should have access to write to all repositories within the
edX,edx-ops and openedX org, but most specifically edx/warehouse-transforms
and edx/terraform will be the most frequent repositories where he will need
to write. Thanks

**Comment by arbrandes** [comment]
Alright: now I just need confirmation from a CLA approver at 2U via a comment in this PR.

**Comment by georgebabey** [comment]
Approved!

**Comment by abdulrafey38** [comment]
Hi @arbrandes ,
it still says the same thing, please have a look here https://github.com/edx/snowflake_timetravel_table/pull/10
