### ISSUE TITLE
[GH Request] Onboard Marco Morales as PM Core Contributor

### ISSUE THREAD

**Issue by sarina** [openedx/axim-engineering#833]
### Firm Name

Axim

### Urgency

Low (2 weeks)

### Problem/Request

Add @marcotuts as PM CC

https://openedx.atlassian.net/wiki/spaces/COMM/pages/3359866883/Administering+a+CC+Onboarding+Non-Coding+roles

### Reasoning

https://discuss.openedx.org/t/core-contributor-nomination-marco-morales/9847/11

## Non-Coding CC Onboarding Checklist for Axim On-Call

- [x] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [x] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Set up access for CC in privacy & a11y courses (can skip for now, but let CC know that they may be upcoming)
- [x] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while).  Keep the ticket open with status “Blocked”, until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [x] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [x] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [x] Look up their record in Salesforce and grant them the Core Contributor role.
- [ ] Send Dean a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)
- [x] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

**Comment by arbrandes** [comment]
@marcotuts, I've invited you to the CC course using the personal email we have on file.  Let me know if you have trouble accessing it!

**Comment by e0d** [comment]
@marcotuts did you receive the invite?

**Comment by e0d** [comment]
Connected with @marcotuts in Slack and he confirmed that he has access to the course, but hasn't completed the course yet.  I've marked that as completed.  We're awaiting confirmation of course completion.

**Comment by feanil** [comment]
Update: Spoke with Marco, there were issues with his access to the course that are now resolved and he's going through the course now.   We're still awaiting confirmation of course completion before moving on to the next steps.

**Comment by brian-smith-tcril** [comment]
As of writing the progress page shows the course as incomplete.

**Comment by kdmccormick** [comment]
Looking at https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/progress with username "Marcofromschema", @marcotuts it looks like you have a few more sections complete.

**Comment by marcotuts** [comment]
I think I am blocked in the course on a checklist problem right now that requires listaflow access being resolved. that is moving again as of yesterday. I'll review to see what else is missing today

**Comment by marcotuts** [comment]
Yup that process was done a while ago all set there

**Comment by kdmccormick** [comment]
Great, I see the message from June now, which confirmed that you're signed onto an individual (not company) CLA.

@marcotuts Did you ever get listaflow access?

**Comment by kdmccormick** [comment]
Oh wait, we also need the CC agreement from you, separate from the CLA. We'll send you something to sign, keep an eye on your email.

**Comment by marcotuts** [comment]
Signed and submitted :D

**Comment by kdmccormick** [comment]
@marcotuts , are you getting Listaflow emails yet? If not, would you like to use your Schema email or personal gmail for that?

**Comment by sarina** [comment]
Bump @marcotuts - can you confirm re: Listaflow access?

**Comment by kdmccormick** [comment]
Marco confirmed that he has access 👍🏻
