### ISSUE TITLE
[GH Request] Onboard mobeenali12

### ISSUE THREAD

**Issue by alexrswan01** [openedx/axim-engineering#835]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Mobeen Ali, @mobeenali12

### Start Date

24 July 2023

### Urgency

High (< 3 days)

### Special Requests

Need to be added to https://github.com/orgs/openedx/teams/ecommerce-maintainers).

**Comment by ormsbee** [comment]
@georgebabey: May I please get your approval for this one as well?

**Comment by georgebabey** [comment]
@ormsbee Approved

**Comment by ormsbee** [comment]
Added to ecommerce-maintainers and Salesforce as an Entity Contributor for 2U/edX. Please note that this gets exported on a daily basis, so you may not see the proper behavior in GitHub requests until tomorrow. Thank you.
