### ISSUE TITLE
[GH Request] Onboard httpsmenahassan

### ISSUE THREAD

**Issue by httpsmenahassan** [openedx/axim-engineering#841]
### Firm Name

Axim

### User List (case sensitive!) - Please also include in ticket title

Mena Hassan, httpsmenahassan

**Problem/Request**
Requesting to be added to CLA

**Reasoning**
Need to be added to contribute

### Start Date

17 July 2023

### Urgency

Medium (< 2 weeks)

**Comment by ormsbee** [comment]
@httpsmenahassan: I added you Axim's CLA last week. Do your pull requests still say that you don't have a CLA?

**Comment by httpsmenahassan** [comment]
Closing the loop here -- I'm all set now. Thanks, Dave!

**Comment by brian-smith-tcril** [comment]
Sounds like we're all good here, closing this!
