### ISSUE TITLE
[GH Request] Rotate openedx-github-action-ecr-user key 

### ISSUE THREAD

**Issue by katebygrace** [openedx/axim-engineering#842]
### Firm Name

2u

### Urgency

Medium (< 2 weeks)

### Problem/Request

I'd like to rotate the AWS access key for the openedx ECR user. I have the new value (and it's attached to the same user); let me know how to transmit this. It should be an easy swap for anyone with access to the "secrets" section in github settings. 

### Reasoning

Security :) (feel free to message me @knachbar on slack for details!)

**Comment by ormsbee** [comment]
@katebygrace: Do you have access to the Keeper folder shared between 2U and Axim/tCRIL named "edx-platform GitHub Move"? That's where we shared the credential the last time–could you please add a new entry for this one?

Thank you.

**Comment by katebygrace** [comment]
@ormsbee I don't, for some reason; can you add me? knachbar@2u.com

**Comment by ormsbee** [comment]
I'd added you. FWIW, @adzuci is the owner of that folder.

**Comment by brian-smith-tcril** [comment]
@katebygrace do you have the access you need now? Is there something more that needs to happen or can I close this issue out?

**Comment by katebygrace** [comment]
Hmm, I still don't see it, @matthugs doesnt have access either

**Comment by katebygrace** [comment]
finally got permissions, or added a new record in there called 2023-openedx-github-action-ecr-user 

let me know when thats rotated so i can decommision the old one @brian-smith-tcril / @ormsbee

**Comment by brian-smith-tcril** [comment]
Worked through this with @katebygrace in DMs and everything should be all good now!
