### ISSUE TITLE
[GH Request] Make repo

### ISSUE THREAD

**Issue by KristinAoki** [openedx/axim-engineering#844]
### Firm Name

2U

### Urgency

High (< 3 days)

### New repository
Name:  frontend-components-tinymce-advanced-plugins
Maintainer: @openedx/teaching-and-learning 
Default branch name: main
Protected Branch: main

### Reasoning

Maintainer @openedx/teaching-and-learning

**Comment by ormsbee** [comment]
@KristinAoki: Empty repo [created](https://github.com/openedx/frontend-components-tinymce-advanced-plugins), and @openedx/teaching-and-learning has write access.

FYI @arbrandes, @brian-smith-tcril
