### ISSUE TITLE
[GH Request] Onboard pjdvmalan

### ISSUE THREAD

**Issue by pjdvmalan** [openedx/axim-engineering#845]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Pieter Malan, pjdvmalan

### Start Date

10 August 2023

### Urgency

Medium (< 2 weeks)

### Special Requests

I only require read-only access.

**Comment by ormsbee** [comment]
@georgebabey: Please verify that it's okay to onboard @pjdvmalan. Thank you.

**Comment by georgebabey** [comment]
Approved

**Comment by brian-smith-tcril** [comment]
- [x] Added to CLA Database
- [x] Added to Open edX GitHub organization
- [x] Added to `2u-edx-legacy` and `openedx-triage` GitHub teams

@pjdvmalan if you check the email associated with your GitHub account you should see the invites to the org/teams.
