### ISSUE TITLE
[GH Request] Please change repo-tools-data-schema default branch to main

### ISSUE THREAD

**Issue by nedbat** [openedx/axim-engineering#846]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Please change the default branch in repo-tools-data-schema to main to keep it in sync with openedx-webhooks-data.

Thanks!

### Reasoning

The repo-tools-data-schema repo is used by the (private) openedx-webhooks-data repo's tests.  To make this possible, the tests try to check out the corresponding branch from repo-tools-data-schema.  But openedx-webhooks-data has a default branch of main, while repo-tools-data-schema has a default of master.  As a result, the openedx-webhooks-data tests don't run properly from main.

**Comment by feanil** [comment]
This should now be all set.
