### ISSUE TITLE
[GH Request] Write access to e-r-b for @Ian2012

### ISSUE THREAD

**Issue by bmtcril** [openedx/axim-engineering#847]
### Firm Name

Axim

### Urgency

Low (2 weeks)

### Requested Change

Add CC write access to @Ian2012 to event-routing-backends.

### Reasoning

Per this thread, his CC rights have been expanded to include this repo: https://discuss.openedx.org/t/coding-cc-rights-expansion-cristhian-andres-garcia/10888

**Comment by brian-smith-tcril** [comment]
As per https://openedx.atlassian.net/wiki/spaces/COMM/pages/3555852316/GitHub+Team+Structure I have created a new team (https://github.com/orgs/openedx/teams/committers-event-routing-backends) with write access to https://github.com/openedx/event-routing-backends. I have added Cristhian to that team, so the rights should be in place now!
