### ISSUE TITLE
[GH Request] Onboard hsinkoff

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#848]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Hilary Sinkoff, hsinkoff

### Start Date

Aug 1, 2023

### Urgency

High (< 3 days)

### Special Requests

Hilary is a principal engineer that already works for 2U and is starting to work on edx related features.

**Comment by timmc-edx** [comment]
@brian-smith-tcril FYI, @-mentioning a GitHub team emails everyone on the team. :-)
