### ISSUE TITLE
Review Existing edx-platform API Docs

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#851]
* Review https://github.com/openedx/edx-platform/pull/32971 and the docs that were written for it.
* Setup to build these docs locally.
* Provide feedback on the PR or as a new PR with additions and improvements over what's already there.

**Comment by farhan** [comment]
Progress updates:
1. I have done the local setup of tutor-nightly. I have mounted the edx-platform from its repo.
2. I have successfully built the docs locally.

Next:
1. I am currently doing the code review of mentioned PR
2. I will provide feedback on the changes.

**Comment by farhan** [comment]
PR: https://github.com/openedx/edx-platform/pull/33152
