### ISSUE TITLE
[GH Request] Offboard swayamrana yuanyuan-git-tech

### ISSUE THREAD

**Issue by dkim2u** [openedx/axim-engineering#854]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Yuanyuan Zhao yuanyuan-git-tech
Swayam Rana swayamrana

### End Date

19 August 2023

### Urgency

Low (2 weeks)

**Comment by e0d** [comment]
@dkim2u can you let me know their email addresses and which teams they will be joining?

**Comment by e0d** [comment]
@dkim2u never mind, realized this is an off-boarding request.
