### ISSUE TITLE
[GH Request] Onboard julianpalmerio

### ISSUE THREAD

**Issue by dkim2u** [openedx/axim-engineering#855]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Julian Palmerio julianpalmerio jpalmerio@2u.com

### Start Date

21 August 2023

### Urgency

Low (2 weeks)

**Comment by e0d** [comment]
Julian has been added to the CLA list.  That will be updated in production this afternoon. 

Which team will they be joing?

**Comment by e0d** [comment]
Invitation sent, waiting for them to accept.
