### ISSUE TITLE
[GH Request] Push openedx-filters docs to readthedocs

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/axim-engineering#859]
### Firm Name

eduNEXT

### Urgency

Low (2 weeks)

### Problem/Request

Create a docs site for https://github.com/openedx/openedx-filters, it already has a docs/ and a readthedocs.yml file (with defaults from the cookie-cutter though)

### Reasoning

We'd like to have centralized documentation for contributors to follow

**Comment by e0d** [comment]
I've configured things on the RTD end.  It looks like the webhook was already created and configured on the GitHub end.

https://docs.openedx.org/projects/openedx-filters/en/latest/

**Comment by e0d** [comment]
@mariajgrimaldi let me know if all looks good on your end.

**Comment by mariajgrimaldi** [comment]
It looks great! Thanks
