### ISSUE TITLE
Slack Invitation Error For External Users

### ISSUE THREAD

**Issue by ehuthmacher** [openedx/axim-engineering#861]
Users are having challenges signing up to join our Slack space on this page: https://openedx.org/community/connect/, preventing them from joining our Slack forum.

**Comment by e0d** [comment]
@nedbat I've heard some 2U folks have have run into this, heard anything about it?

**Comment by nedbat** [comment]
I have not heard about this.

**Comment by ehuthmacher** [comment]
Kaleb Davenport reported it to me and other 2U employees have complained to him directly, so he can provide you with additional contacts.

**Comment by kdmccormick** [comment]
@e0d I'm going to close this as it doesn't seem reproducible, feel free to reopen if you disagree.
