### ISSUE TITLE
[GH Request] Onboard hamzawaleed-arbisoft

### ISSUE THREAD

**Issue by dkim2u** [openedx/axim-engineering#866]
### Firm Name

2u

### User List (case sensitive!) - Please also include in ticket title

Hamza Waleed hamzawaleed-arbisoft

### Start Date

4 September 2023

### Urgency

Low (2 weeks)

### Special Requests

They will be joining George Babey's team

**Comment by e0d** [comment]
Added to CLA list, added to groups.
