### ISSUE TITLE
[GH Request] FED-BOM owned repos settings access request

### ISSUE THREAD

**Issue by abdullahwaheed** [openedx/axim-engineering#875]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

@openedx/fed-bom need github repository settings access for our owning repos in openedx:

- https://github.com/openedx/edx-bootstrap
- https://github.com/openedx/edx-ui-toolkit
- https://github.com/openedx/eslint-config
- https://github.com/openedx/frontend-app-account
- https://github.com/openedx/frontend-component-footer
- https://github.com/openedx/frontend-component-header
- https://github.com/openedx/frontend-platform
- https://github.com/openedx/sample-themes
- https://github.com/openedx/stylelint-config-edx
- https://github.com/openedx/frontend-build
- https://github.com/openedx/typescript-config

### Reasoning

currently, we need this access to add/update branch protection rules for CI checks

**Comment by feanil** [comment]
@abdullahwaheed we are not currently granting any teams new admin access, can you provide the details of what branch protection settings you need and we can update them for you.

**Comment by abdullahwaheed** [comment]
Hi @feanil. In our owned MFEs, please add/update `Branch protection rule` on branch `master`. Enable check `Require status checks to pass before merging` and add status check `tests` in it to enable required CI check.

**Comment by feanil** [comment]
@abdullahwaheed I've added the `test` check to the following repos:

* eslint-config
* frontend-component-footer
* frontend-component-header
* frontend-platform
* frontend-build

The following repos did not have a `tests` check that had been run in the last week so I was unable to add it as a required check, can you let me know once you've added those checks and they've been run on master?

* edx-bootstrap
* edx-ui-toolkit
* sample-themes
* stylint-config-edx
* typescript-config

The `frontend-app-account` repo is also different, it has multiple `tests` checks:

* tests (i18n_extract)
* tests (lint)
* tests (test)
Let me know if you'd like me to add those or if you want to update how that repo is organized.

**Comment by brian-smith-tcril** [comment]
I've updated the following repos to have required status checks
- [x] `edx-bootstrap` (`tests`)
- [ ] `edx-ui-toolkit` (this one has 2 required checks: `build` and the CLA. The only non-required check is `commitlint`)
- [ ] `sample-themes` (this one only has 2 checks: CLA and `commitlint`)
- [x] `stylelint-config-edx` (`tests`)
- [x] `typescript-config` (`tests`)
- [ ] `frontend-app-account` (not sure which check(s) to require)

@abdullahwaheed if you could let me know what you'd like to do about `edx-ui-toolkit`, `sample-themes`, and `frontend-app-account` that'd be very helpful!

**Comment by abdullahwaheed** [comment]
Hi Brian, `sample-themes` is deprecated and not actively maintained, so we can ignore it. 
For `edx-ui-toolkit`, `build` is the main workflow, so if its already marked as required, it would serve the purpose.
For frontend-app-account, please mark `tests (test)` as required workflow

**Comment by brian-smith-tcril** [comment]
These should be all set now. Thanks for the clarification!
