### ISSUE TITLE
[GH Request] Onboard bpedx

### ISSUE THREAD

**Issue by nedbat** [openedx/axim-engineering#877]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

* Ben Piscopo, username bpedx

### Start Date

November 22, 2016

### Urgency

Medium (< 2 weeks)

### Special Requests

Ben is now Product Manager, updating docs.

**Comment by feanil** [comment]
I've sent him an invite and added him to the `Open edX Product Managers` team.
