### ISSUE TITLE
[GH Request] Onboard CC volodymyr.chekyrta

### ISSUE THREAD

**Issue by e0d** [openedx/axim-engineering#880]
### Firm Name

Axim

### User List (case sensitive!) - Please also include in ticket title

Requesting CC access for Volodymyr Chekyrta with gh username volodymyr.chekyrta.  

Note that Volodymyr will be granted access to the following repos *once they are transferred to the Open edX organization*:
* GitHub - raccoongang/educationx-app-ios: The mobile app for iOS for the Open EdX Platform. 1
* GitHub - raccoongang/educationx-app-android: The mobile app for Android for the Open EdX Platform. 1

Reason: [<link to nomination thread>](https://discuss.openedx.org/t/core-contributor-nomination-volodymyr-chekyrta/10715)

Instructions: Please give access to <list of repos> and/or <grouping of repos>

### Start Date

1 August 2023

### Urgency

Low (2 weeks)

_________________________________________

### Non-Coding CC Onboarding Checklist for Axim On-Call
- [x] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [x] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Set up access for CC in privacy & a11y courses (can skip for now, but let CC know that they may be upcoming)
- [x] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while).  Keep the ticket open with status “Blocked”, until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [x] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [x] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [x] Look up their record in Salesforce and grant them the Core Contributor role.
- [x] Send Dean a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)
- [x] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

**Comment by e0d** [comment]
I've sent the onboarding course invitation.

**Comment by kdmccormick** [comment]
Looking at https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/progress with username "vchekyrta", looks like Volodymyr has a few more sections complete.

**Comment by kdmccormick** [comment]
@bmtcril I just confirmed that Volodymyr has completed the onboarding course, so you should be good to pick up at "legal documents" step.

**Comment by bmtcril** [comment]
Pinged Axim legal about the status of the documents.

**Comment by bmtcril** [comment]
We need Volodymyr's personal email to send the docs over for signing. I've asked him on Slack.

**Comment by bmtcril** [comment]
Email has been received, updated in Salesforce, and sent on to legal

**Comment by bmtcril** [comment]
Paperwork is done and the rest of the checklist is complete.
