### ISSUE TITLE
[GH Request] Add REQUIRED check on Ruby 3.0 CI pipeline for cs_comments_service

### ISSUE THREAD

**Issue by saadyousafarbi** [openedx/axim-engineering#884]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Team Infinity need to update the repo settings for [cs_comments_service](https://github.com/openedx/cs_comments_service), and make the Ruby 3.0 CI test pipeline a `required` check on every PR.

### Reasoning

Team Infinity recently updated the Ruby version of `cs_comment_service` from version 2 to 3.
This was done as Ruby 2 was EOL. We now need to enforce the Ruby 3 test build pipeline to be required for all new PRs, to be compatible with the upgraded version.
This is currently blocking ready to merge PRs, as we are waiting for this check to be required on every PR.

**Comment by brian-smith-tcril** [comment]
@saadyousafarbi the build matrix does not currently include Ruby 3.1. https://github.com/openedx/cs_comments_service/blob/acc9b2f154324b02291b5b500a7f2660dec5aaa8/.github/workflows/ci.yml#L16 only has `'2.5.7'` and `'3.0.4'`

The [open PR for removing ruby 2](https://github.com/openedx/cs_comments_service/pull/417/files) also doesn't mention 3.1.

If you'd like I can add the `3.0.4` build as a required status check, but the workflow file will need to be updated to include `3.1` for me to add that as a required check.

**Comment by saadyousafarbi** [comment]
Sorry @brian-smith-tcril i mistyped.
We are looking to add the required check for Ruby 3.0.4.
The one that is present in the build matrix you shared.

**Comment by brian-smith-tcril** [comment]
![image](https://github.com/openedx/axim-engineering/assets/112954497/700376eb-f4a9-4900-aecc-63fccf9895c7)

It should be good to go now! If you have any issues let me know and I'll be happy to reopen this.
