### ISSUE TITLE
[GH Request] Offboard llewenstein

### ISSUE THREAD

**Issue by dkim2u** [openedx/axim-engineering#888]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Lena Lewenstein llewenstein

### End Date

20 September 2023

### Urgency

Low (2 weeks)

**Comment by brian-smith-tcril** [comment]
Checked CLA db, not covered under any entity. Checked the openedx org, no record of llewenstein. It seems this is complete.
