### ISSUE TITLE
[GH Request] Onboard hamzawaleed01, justEhmadSaeed, MueezKhan246

### ISSUE THREAD

**Issue by sameenfatima78** [openedx/axim-engineering#892]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Hamza Waleed, @hamzawaleed01 
Ehmad Saeed, @justEhmadSaeed 
Mueez Khan, @MueezKhan246 

### Start Date

26 September 2023

### Urgency

High (< 3 days)

**Comment by brian-smith-tcril** [comment]
@georgebabey - @sameenfatima78 is not listed as CLA approver in salesforce. Can you verify these requests?

**Comment by georgebabey** [comment]
Requests are valid (they all work directly with me) but they should come from our Helpdesk, rather than the manager.  I will reach out internally to see what the holdup on the helpdesk onboarding tickets was.

**Comment by georgebabey** [comment]
And Mueez as well: https://github.com/openedx/axim-engineering/issues/856

@sameenfatima78 can you confirm access is still needed? It seems to already be addressed.

**Comment by sameenfatima78** [comment]
@georgebabey I see what the issue here is. Looks like the username of Hamza was changed after onboarding. He's the one who's been facing permission issues. We reached out to Helpdesk first but they inquired whether an onboarding request was sent to tCRIL. That's the reason I initiated this request. 

Would it be okay to provide access to Hamza on his new username? (hamzawaleed01)

**Comment by georgebabey** [comment]
This came up in the user audit with @feanil as well.

Username changes don't happen often but should go through our 2U Helpdesk, so they can submit a ticket for Axim to update the CLA as well as Salesforce tracking.

**Comment by feanil** [comment]
Yea, Hamza never lost access to the org but was failing CLA checks because the usernames did not match.  I corrected Hamza's github username in our system so he should be all set.  I haven't done anything for the other 2 @brian-smith-tcril

**Comment by brian-smith-tcril** [comment]
* I checked the GH org and the CLA database, everything seems to be in order for @MueezKhan246
* @justEhmadSaeed's entry in the CLA database had an error. I've resolved it.
* The changes needed for @hamzawaleed01 have already been addressed.

I'm going to close this out. Please let me know if you encounter any issues and I can take another look.
