### ISSUE TITLE
[GH Request] Please remove django 3.2 test gating in license-manager

### ISSUE THREAD

**Issue by macdiesel** [openedx/axim-engineering#897]
### Firm Name

2u

### Urgency

Medium (< 2 weeks)

### Requested Change

Currently in the process of upgrading Django to 4.2. 

Could you please remove django 3.2 test gating in license-manager.

There will be a subsequent ask to turn this on for 4.2 once https://github.com/openedx/license-manager/pull/525 is merged. 

### Reasoning

Upgrading Django.

**Comment by brian-smith-tcril** [comment]
I'm not sure what test gating you're referring to, I only see 2 required checks on that repo

![image](https://github.com/openedx/axim-engineering/assets/112954497/b7d48e4f-7c02-4417-96e9-f4ec620f2d63)

Am I not looking in the right spot?

**Comment by brian-smith-tcril** [comment]
@macdiesel I didn't ping you in my previous response so I figured I'd follow up.

**Comment by macdiesel** [comment]
Had a few emergencies pop up. It's not on now, let's just keep it this way.
Can't inspect this stuff myself so I don't know how it's configured.

**Comment by brian-smith-tcril** [comment]
GitHub shows which checks will block merging any given PR by noting them as "Required"

![image](https://github.com/openedx/axim-engineering/assets/112954497/1348d0b5-5241-43e1-bb31-e36919f3f8d3)

Since it's not on I'm going to go close this.
