### ISSUE TITLE
[GH Request] Onboard Ian2012

### ISSUE THREAD

**Issue by Ian2012** [openedx/axim-engineering#899]
### Firm Name

eduNEXT

### User List (case sensitive!) - Please also include in ticket title

@Ian2012 

### Start Date

1 October 2023

### Urgency

Medium (< 2 weeks)

### Special Requests

Requesting CC access for Cristhian Garcia with gh username @Ian2012 to repos the analytics repo list.

Reason: https://discuss.openedx.org/t/coding-cc-rights-expansion-cristhian-andres-garcia/11054

Instructions: Please give access to https://github.com/openedx/aspects-dbt and/or any analytics related repository

**Comment by brian-smith-tcril** [comment]
@Ian2012 I have added you to @openedx/committers-analytics. @bmtcril said he will ensure that team has access to all the appropriate repositories.

**Comment by Ian2012** [comment]
Thanks
