### ISSUE TITLE
[GH Request] Update the CLA and Salesforce tracking for - Hamza Waleed

### ISSUE THREAD

**Issue by GEksteen** [openedx/axim-engineering#900]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

**Hi team, 

A ticket was logged to our Helpdesk queue requesting the below.

Username - hamzawaleed01
Full names - Hamza Waleed**

"Hi,
I recently changed my github username to *hamzawaleed01*. @George Babey
<[gbabey@2u.com](mailto:gbabey@2u.com)> shared that I need to reach out to 2U Helpdesk to submit a
ticket for Axim to update the CLA as well as Salesforce tracking."

### Reasoning

User reported that their Github username has changed.

**Comment by brian-smith-tcril** [comment]
@feanil am I correct in assuming that your comment here https://github.com/openedx/axim-engineering/issues/892#issuecomment-1739103559 means this is complete?

**Comment by feanil** [comment]
Yea, this is all set.
