### ISSUE TITLE
[GH Request] Add edx-search access for 2U DLX team

### ISSUE THREAD

**Issue by ashultz0** [openedx/axim-engineering#901]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Please give the DLX team

https://github.com/orgs/openedx/teams/2u-digital-learning-experience

Write access to the edx-search repo

https://github.com/openedx/edx-search

### Reasoning

Our team is experimenting with getting edx-search running in the new MFE world and will probably need to update the edx-search library itself as well as working in the learning MFE and platform both of which we have access to.

**Comment by brian-smith-tcril** [comment]
@jristau1984 it seems you're the de-facto maintainer of this repo. Is this OK with you?

**Comment by jristau1984** [comment]
@brian-smith-tcril can you walk me thru that connection, please?

**Comment by jristau1984** [comment]
I approve.

**Comment by brian-smith-tcril** [comment]
`2u-digital-learning-experience` now has write permissions to `edx-search`
