### ISSUE TITLE
[GH Request] Enable Renovate for my repo

### ISSUE THREAD

**Issue by deborahgu** [openedx/axim-engineering#902]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

Could we have Renovate and Renovate Approve enabled for frontend-app-learner-record, please?

### Reasoning

We'd like to enable renovate in order to keep our packages up to date, per https://github.com/openedx/frontend-app-learner-record/issues/157. Thanks!

**Comment by brian-smith-tcril** [comment]
I have activated Renovate and Renovate Approve on `frontend-app-learner-record`. If you have any issues please let me know!
