### ISSUE TITLE
[GH Request] Update Confluence Access

### ISSUE THREAD

**Issue by kalebjdavenport** [openedx/axim-engineering#903]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

I recently updated my GH username from TheEarlyNerd to kalebjdavenport and a number of different changes have happened. Somehow I don't have edit/write access to the Paragon Meetings https://openedx.atlassian.net/wiki/spaces/BPL/pages/3878748161/2023-09-27+Meeting+notes

If you would be able to help me get that access I'd greatly appreciate it! Thanks. 

### Reasoning

I work with the Paragon Working group many weeks and would love to have access to add discussion topics.

**Comment by brian-smith-tcril** [comment]
@kalebjdavenport just following up on this one. Any luck or are you still having issues?

**Comment by e0d** [comment]
@kalebjdavenport I've sent you a password reset email.  See if that will help here.  Your email is currently your edx.org email, should that be updated?

Honestly, I don't see how what you've described could prevent you from editing the Paragon WG notes.  I assume that you are able to login via the SSO workflow?

**Comment by e0d** [comment]
Closing as there's been no response from requestor.
