### ISSUE TITLE
[GH Request] Onboard <ADD USERNAMES HERE>

### ISSUE THREAD

**Issue by crathbun428** [openedx/axim-engineering#907]
### Firm Name

Axim

### User List (case sensitive!) - Please also include in ticket title

Chelsea Rathbun, crathbun428

### Start Date

4 October 2023

### Urgency

Medium (< 2 weeks)

### Special Requests

Could I have the same access/permissions as Jenna Makowski? Thank you!

**Comment by jmakowski1123** [comment]
@kdmccormick - This is for Chelsea, our new PM. Is it possible to expedite so she has access during our onboarding projects this week?

**Comment by kdmccormick** [comment]
Hi @crathbun428 , I have sent an invite to your email which will add you to the openedx organization and give you triage-level access to all of our [GitHub repositories](https://github.com/orgs/openedx/repositories).

I can't see which [GitHub projects](https://github.com/orgs/openedx/projects) Jenna has a access to unfortunately. When you find that you lack access to a project, I would reach out to one of the project's admins (which often will be Jenna) and ask them to grant you access. If you can't find anyone to grant you access, just open another ticket here.

Outside of GitHub, there are several onboarding steps which Sarina would normally take care of, like wiki and forum access. I'm not sure which of those Ed and Jenna are doing. Let's talk in standup to make sure you can access everything you need to.

**Comment by kdmccormick** [comment]
This should be all set.
