### ISSUE TITLE
[GH Request] Please disable required check for py38, django32 from the enterprise-catalog repo.

### ISSUE THREAD

**Issue by macdiesel** [openedx/axim-engineering#908]
### Firm Name

2u

### Urgency

Medium (< 2 weeks)

### Requested Change

Please disable required check for py38, django32 from the enterprise-catalog repo. Here is an example PR that Is blocked on merging. https://github.com/openedx/enterprise-catalog/pull/673

### Reasoning

Django upgrade.

**Comment by kdmccormick** [comment]
Done. Feel free to reopen this same ticket if/when you want Django4.2 checks to be required.
