### ISSUE TITLE
[GH Request] Fork pinax-requirements in openedx org

### ISSUE THREAD

**Issue by iamsobanjaved** [openedx/axim-engineering#911]
### Firm Name

2U

### Urgency

High (< 3 days)

### Problem/Request

Kindly fork [pinax-announcements](https://github.com/pinax/pinax-announcements) in openedx org.

### Reasoning

We are nearing the Quince branch cut, and want to give the Django 4.2 upgrade in the Quince release. This package [pinax-announcements](https://github.com/pinax/pinax-announcements) is giving errors on Django 4.2 so kindly fork this package so we can add support for Django 4.2 in our fork and then once support arrives upstream, we can close our fork.

Choosing high priority just because the branch cut is approaching.

**Comment by kdmccormick** [comment]
Can do @iamsobanjaved . Before I fork, can I confirm that Arbi-BOM is OK with being listed as maintainer of the forked repo?

**Comment by iamsobanjaved** [comment]
Yes you can list us as maintainer

**Comment by kdmccormick** [comment]
Fork created here: https://github.com/openedx/pinax-announcements

Arbi-BOM is added with Maintain-level access.

Keeping this ticket open for now because I need to do a couple small things to make sure that Arbi-BOM are set up as maintainers.

**Comment by kdmccormick** [comment]
In review: https://github.com/openedx/pinax-announcements/pull/2

**Comment by kdmccormick** [comment]
catalog-info.yaml is merged, and I messaged #maintainer-pilot to let them know that Arbi-BOM will be maintaining the fork.
