### ISSUE TITLE
Migrate to `xblock.utils` from `xblockutils` after deprecation of repo

### ISSUE THREAD

**Issue by farhan** [openedx/axim-engineering#915]
Predecessor ticket: https://github.com/openedx/XBlock/issues/675

The [xblock-utils](https://github.com/openedx/xblock-utils/) repo has been deprecated and in this story, we have to list down all the repositories that are using the xblock-utils package and switch the usage/import from `xblock-utils` to `xblock.utils`

**Tasks:**

- [x] Go through all the repositories that install xblock-utils. For each repo that installs xblock-utils, open an issue for removing xblock-utils, [like this one](https://github.com/openedx/DoneXBlock/issues/176)

**Acceptance Criteria:**

1. All repos that use xblock-utils have an issue indicating that they need to upgrade and migrate.

**Comment by farhan** [comment]
Package `xblockutils` has been found in following 17 repositories and issue has been created in all of these repositories:

Sr No. | Git respositories Url
-- | --
1 | https://github.com/openedx/DoneXBlock
2 | https://github.com/openedx/edx-platform
3 | https://github.com/openedx/xblock-drag-and-drop-v2
4 | https://github.com/openedx/xblock-lti-consumer
5 | https://github.com/openedx/xblock-google-drive
6 | https://github.com/openedx/xblock-image-explorer
7 | https://github.com/openedx/staff_graded-xblock
8 | https://github.com/openedx/xblock-image-modal
9 | https://github.com/openedx/edx-enterprise
10 | https://github.com/openedx/xblock-qualtrics-survey
11 | https://github.com/openedx/FeedbackXBlock
12 | https://github.com/openedx/xblock-free-text-response
13 | https://github.com/openedx/edx-repo-health
14 | https://github.com/openedx/xblock-in-video-quiz
15 | https://github.com/openedx/AudioXBlock
16 | https://github.com/openedx/xblock-submit-and-compare
17 | https://github.com/openedx/xblock-sql-grader

**Comment by Agrendalath** [comment]
@farhan, it would be great to keep the old imports as a fallback instead of breaking the backward compatibility of these 17 repos with all releases older than Quince (not released yet).

cc: @feanil

**Comment by feanil** [comment]
So add a try-except clause for the new imports and then try the old imports if we don't find the new ones?

**Comment by Agrendalath** [comment]
@feanil, exactly, something like this:
```python
try:
    from xblock.utils.resources import ResourceLoader
    from xblock.utils.settings import ThemableXBlockMixin, XBlockWithSettingsMixin
except ModuleNotFoundError:  # For backward compatibility with releases older than Quince.
    from xblockutils.resources import ResourceLoader
    from xblockutils.settings import ThemableXBlockMixin, XBlockWithSettingsMixin
```
