### ISSUE TITLE
[GH Request] Add arbi-bom team as collaborators in ConceptXblock and AudioXBlock repos

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/axim-engineering#921]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

The `arbi-bom` team needs to be added as collaborators in the repo settings to be successfully tagged for review on the Python Requirements Upgrade PRs.

### Reasoning

Scheduled Python requirements upgrade jobs fail to tag the review team `arbi-bom` in the `ConceptXBlock` and `AudioXBlock` on the created PRs.

**Comment by bmtcril** [comment]
Permissions have been updated on both repos, let me know if you run into any issues!
