### ISSUE TITLE
[GH Request] Remove checks from branch protection rules in Course Discovery

### ISSUE THREAD

**Issue by iamsobanjaved** [openedx/axim-engineering#923]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Kindly remove these checks from branch protection rules, in the course-discovery repo

- pytest (py38, django32, mysql57, 1)
- pytest (py38, django32, mysql57, 2) 
- pytest (py38, django32, mysql57, 3)
- pytest (py38, django32, mysql57, 4) 
- pytest (py38, django32, mysql57, 5)
- pytest (py38, django32, mysql57, 6)

Ref PR: https://github.com/openedx/course-discovery/pull/4088

### Reasoning

We want to merge Django upgrade PR, but these checks are stopping us. We can disable these for now, and enable Django 4.2 once we merge the upgrade PR

**Comment by kdmccormick** [comment]
Django 3.2 checks are no longer required. Just ping me on this ticket again when you want the Django 4.2 checks marked as required.


Here's what the checks looked like before, for our reference:
![Image](https://github.com/openedx/axim-engineering/assets/3628148/1e8f0da9-a9e3-49ea-aea2-8004f18874ea)

**Comment by kdmccormick** [comment]
Sounds good, just let me know.

**Comment by kdmccormick** [comment]
Done!
