### ISSUE TITLE
Need Project Board for 2024 Open edX Conference

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/axim-engineering#925]
### Firm Name

Axim

### Urgency

High (< 3 days)

### Problem/Request

Looking to make a project / kanban for the 2024 Open edX Conference. Ed suggested opening a ticket to see if someone could help while he's out for a conference. I'm not sure what repo it would belong under, so maybe someone on the Eng team has a suggestion?

We would need a mix of people to see it including Axim and a few other members (e.g. Cassie and Ali from OpenCraft, and some of the Marketing WG members). 

Also, some may issues need to be private and/or shared with a smaller subset of the team.

Are these things possible?

### Reasoning

To track tasks and progress for planning the 2024 Open edX Conference.

We used to use Monday for project tracking, but are planning to use Github instead this year.

**Comment by kdmccormick** [comment]
Sorry for the delay @mphilbrick211 ! I'm trying to figure out where the best place to create the board is given that some of the issues may need to be private. I'll try to have the board created this afternoon.

**Comment by kdmccormick** [comment]
@bmtcril We talked in standup and agreed that we should make a single public board that includes issues both from a public repo and private repo (public boards can include private issues; the status of the issue will be public but its title and details will be hidden).

**Comment by kdmccormick** [comment]
@bmtcril on second thought, since this one is so close to being done, I'll wrap it up.

**Comment by kdmccormick** [comment]
Thanks for you patience @mphilbrick211 . I've made:

* One project: https://github.com/orgs/openedx/projects/61
* One repo for public issues: https://github.com/openedx/conference-planning-2024
* And one repo for private issues: https://github.com/openedx/conference-planning-2024-private

New issues in each repo will be automatically added to the board. I've made one private and one public test issue. Here's what that looks like to you and me:

![image](https://github.com/openedx/axim-engineering/assets/3628148/b22fc430-31df-45d6-979f-f6ccb63745ed)

and here's what it looks like to everyone else (the private issue says "you can't see this item", and will hide its title, contents, status, and assignees):

![image](https://github.com/openedx/axim-engineering/assets/3628148/6af9422e-3d91-44a7-bb1c-4406241d9c97)

**Comment by kdmccormick** [comment]
@mphilbrick211 You are an admin on the project, so you can give people write access to the project as you please, as long as they are in the openedx organization already. If folks need to be added to the openedx organization, open another ticket here.

Also, in order to see the private issues, the engineering team will need to grant folks access to https://github.com/openedx/conference-planning-2024-private -- open a ticket here whenever that needs to happen.

While we have this ticket open, did you want me to add anyone to the openedx organization and/or the private issue repository? I can also add an entire team to the private issue repository, if that makes sense.

**Comment by mphilbrick211** [comment]
Thanks, @kdmccormick!

@e0d - what kind of access did Ali and Cassie need? Are we also adding Eden and other marketing WG members?

**Comment by sarina** [comment]
@mphilbrick211 @kdmccormick is this issue still unresolved?

**Comment by mphilbrick211** [comment]
Nope, we're all set. Closing.
