### ISSUE TITLE
[GH Request] Onboard theinkedkraken to openedx org

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#927]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Jim Johnson, theinkedkraken

### Start Date

October 16, 2023

### Urgency

Medium (< 2 weeks)

**Comment by bmtcril** [comment]
Jim has been added to the openedx org with the default 2U teams: @openedx/openedx-triage, @openedx/2u-edx-legacy and added to Salesforce.
