### ISSUE TITLE
[GH Request] add renovate to frontend-app-course-authoring

### ISSUE THREAD

**Issue by jesperhodge** [openedx/axim-engineering#928]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Request to enable renovate on frontend-app-course-authoring

On frontend-app-course-authoring, we (TNL) would like to use renovate. There's a renovate config in the repo. However, renovate is not doing anything in the repo. I assume it is not enabled. I see very low activity even by dependabot.
Could you enable renovate-bot for frontend-app-course-authoring? I turned off auto-merge for now so that there's no rush of auto-merged updates as soon as the bot gets enabled.

### Reasoning

- we want to set up automatic and auto-merged dependency updates of the frontend-lib-content-components dependency on the repo mentioned above, because it saves us a lot of work. There's already a renovate config and this seems like the simplest path.
- we would like to improve the situation with dependency updates on the mentioned repo, because dependabot seems to be enabled but do very little, and there's also no dependabot config in the repo. Keeping dependabot seems to be the less optimal solution.

I don't have permissions to add bots or change their settings for frontend-app-course-authoring. If you prefer to provide me with the necessary permissions so I do it myself, that is also fine for me.
Thanks for the support!

**Comment by kdmccormick** [comment]
Hi Jesper. This is behind a few other Axim support tickets but we'll certainly take a look when we can, hopefully in the next week or two. Thanks!

**Comment by kdmccormick** [comment]
@jesperhodge reached out to clarify that although the urgency of this is relatively low, it is in fact high importance that we're able to resolve this within a few weeks.

**Comment by bmtcril** [comment]
@jesperhodge this is set up now, it looks like you've touched the renovate.json so you know that's where all of the settings are. :) Let me know if you run into any issues.
