### ISSUE TITLE
[GH Request] Broken link on openedx.org

### ISSUE THREAD

**Issue by jmbowman** [openedx/axim-engineering#931]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

While hunting for options for an Open edX architecture overview, I landed on https://openedx.org/the-platform/ and discovered that the link in "Learn more about the Open edX technical architecture [here](http://docs.edx.org/openedx.html)" results in a 404.

### Reasoning

If the target page moved, the URL should be fixed.  If we don't currently have a document we recommend for this, the sentence should be removed (although that would be unfortunate).

**Comment by kdmccormick** [comment]
We have this: https://docs.openedx.org/en/latest/developers/concepts/platform_overview.html

Not perfect, but it's something, and it's a page that any dev can add to.

Fixing now.

**Comment by kdmccormick** [comment]
Done, thanks!
