### ISSUE TITLE
[GH Request] Transfer repository openedx-wordpress-ecommerce from edunext to openedx

### ISSUE THREAD

**Issue by felipemontoya** [openedx/axim-engineering#935]
### Firm Name

eduNEXT

### Urgency

Low (2 weeks)

### Requested Change

1. Transfer the https://github.com/eduNEXT/openedx-wordpress-ecommerce to the openedx org.
2. Create a maintainers group for this repository where @MaferMazu and @felipemontoya take the maintainers role. This is pending the finalization of the [nomination](https://discuss.openedx.org/t/core-contributor-nomination/11409) for Mafer as CC.

### Reasoning

As part of the Axim funded contribution [FC0015](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3669098505/FC-0015+-+WooCommerce+Discovery) edunext was tasked with creating an open source plugin for the Wordpress ecosystem to be able to connect with Open edX instances.

This plugin was written at the edunext org github account for ease of development. Now that a stable feature complete package has been written and that the plugin has been requested for publication in the Wordpress plugin index it is time to transfer orgs to the rightful place.

To ease the transition @feanil has been invited as an admin of the edunext repository.

Thanks a lot :)

**Comment by feanil** [comment]
@kdmccormick I'll take care of this one.

**Comment by feanil** [comment]
@felipemontoya the repository has been transferred and I've given you access to it.  We can add @MaferMazu when their CC nomination process is completed.

**Comment by felipemontoya** [comment]
Thanks a lot!

**Comment by feanil** [comment]
This should be all set!
