### ISSUE TITLE
[GH Request] Onboard <ADD USERNAMES HERE>

### ISSUE THREAD

**Issue by khanangrauer** [openedx/axim-engineering#936]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Khanan Grauer  https://github.com/khanangrauer
Anton Yarmolenka: https://github.com/rnr
Kirill Izmaylov https://github.com/k1rill
Igor Koznin https://github.com/dixidroid
Eugene Yatsenko https://github.com/eyatsenkoperpetio
Vadim Kuznetsov https://github.com/forgotvas
Sergey Momot https://github.com/sergeymomot
Natalia Izmaylova https://github.com/nizmaylova

### Start Date

October 16, 2023

### Urgency

High (< 3 days)

### Special Requests

Hi, we would like to request our team to be added to the edX/ 2U organization. Our team is contributing to the mobile project already in the works here: 

https://github.com/openedx/openedx-app-ios/
https://github.com/openedx/openedx-app-android

Please reach out if you have any questions to kgrauer@2u.com. 

Thank you

**Comment by bmtcril** [comment]
Hi @khanangrauer , unfortunately we can't accept this request from you. We need these types of permissions requests to come from someone who has been vetted on the 2U side. @georgebabey is usually a good place to start for getting that process rolling.  Once we have the request from someone known to us we'll be happy to get this done ASAP.
