### ISSUE TITLE
[GH Request] Github Org Access for Github Project Collaboration (Mobile)

### ISSUE THREAD

**Issue by marcotuts** [openedx/axim-engineering#937]
### Firm Name

Schema

### Urgency

Medium (< 2 weeks)

### Requested Change

I'd like to be able to add edX team members as assignees and editors to the mobile roadmap project - https://github.com/orgs/openedx/projects/56/views/1

I think they need to have some sort of organization-level membership on github? I don't know if this is a pure access issue or if additional things need to be done. 

This is for product / design team members: 
phanumara, moiz994, ekangedx.

Thanks for the help / guidance on what should happen net. 

### Reasoning

Mobile roadmap community collaboration

**Comment by kdmccormick** [comment]
@marcotuts Yup, you're right that those folks need openedx organization membership, and you did the right thing by opening a ticket here.  I'll invite them to the organization now--they should get invites sent to whatever email they have with GitHub.

Once they accept, they'll have the ability to triage issues in any repo, and it'll give project admins (like you) the ability to add them to your project.

Feel free to open more tickets like this if new project members come on board that aren't in the org.

**Comment by sarina** [comment]
@marcotuts @kdmccormick do you know why @ekangedx is in a group that gives write access to mobile repos? They're not under any CLA (individual or entity) with Axim and are not a core contributor. I am going to remove them from the group until this is straightened out.

**Comment by marcotuts** [comment]
Ok to remove - I can share with them next week the issue re: CLA. Design team member at edx / 2U. Can be updated in the future as needed with separate ticket / process. 

Thanks!

**Comment by sarina** [comment]
Thanks Marco!
