### ISSUE TITLE
[GH Request] Onboard 2U/edX Mobile team [miankhalid, moiz994, saeedbashir, omerhabib26, farhan-arshad-dev, HamzaIsrar12, bilalawan321, moeez96, jawad-khan]

### ISSUE THREAD

**Issue by miankhalid** [openedx/axim-engineering#938]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

[Mian Khalid ](https://github.com/miankhalid) miankhalid
[Moiz Alam](https://github.com/moiz994) moiz994
[Muhammad Umer ](https://github.com/mumer92) mumer92
[Saeed Bashir ](https://github.com/saeedbashir)saeedbashir
[Omer Habib ](https://github.com/omerhabib26)omerhabib26
[Farhan Arshad ](https://github.com/farhan-arshad-dev)farhan-arshad-dev
[Hamza Israr ](https://github.com/HamzaIsrar12)HamzaIsrar12
[Bilal Awan ](https://github.com/bilalawan321)bilalawan321
[Moeez Zahid ](https://github.com/moeez96)moeez96
[Jawad khan ](https://github.com/jawad-khan)jawad-khan

### Start Date

16 October 2023

### Urgency

High (< 3 days)

### Special Requests

Hi, we would like to request our team to be added to the edX/2U organization. Our team is contributing to the mobile project already in the works here:

1. [Open edX Mobile Roadmap](https://github.com/orgs/openedx/projects/56/views/1)
2. [openedx/openedx-app-ios](https://github.com/openedx/openedx-app-ios/)
3. [openedx/openedx-app-android](https://github.com/openedx/openedx-app-android)

Feel free to reach out to me @ mkhalid@2u.com

**Comment by kdmccormick** [comment]
Hi @miankhalid , everybody in your list except https://github.com/moiz994 and https://github.com/moeez96 are already members of the [openedx](https://github.com/openedx) organization. Axim doesn't have any control over the [edx](https://github.com/edx) organization; 2U runs that.

Is your request that https://github.com/moiz994 and https://github.com/moeez96 are new 2U employees and should be added to the openedx org?

**Comment by bmtcril** [comment]
Thanks, Moiz Alam has been added to our Salesforce and I've double checked that all of those users are in the correct group for access to those repos. Let me know if you run into any issues!
