### ISSUE TITLE
[GH Request] Access to change settings for frontend-app-course-authoring

### ISSUE THREAD

**Issue by jesperhodge** [openedx/axim-engineering#939]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

I need access to change the settings of frontend-app-course-authoring.

### Reasoning

I am part of TNL and we are owner of this repo, and there is some misconfiguration. Apparently the "tests" pipeline checks are not required to merge into master, which means that renovate can merge PRs with failing pipelines, which is not good. I also expect I'll need to look if other settings are correct. I'd like to be able to edit the settings myself.

The high urgency is because we just enabled renovate and want this to work correctly.

**Comment by bmtcril** [comment]
Hi Jesper, we don't give admin on repos (minus a handful of legacy exceptions) for legal reasons. I'd be happy to get on a video call with you to go over the settings and make sure everything is where you'd like it. In the meantime I've added tests to the required status checks for the master branch on the repo.

**Comment by bmtcril** [comment]
@jesperhodge I'm going to close this, but feel free to grab me on Slack to set up a call to go over settings if you'd like to do that.

**Comment by jesperhodge** [comment]
Hi @bmtcril , thanks a lot! This was super helpful. Sorry I didn't see your response immediately.
The adding of tests to the pipeline checks was what I was concerned with, everything else is probably fine. I'll just have a look at whether renovate does everything else as supposed next week and may dm you on slack if there's anything else that's out of line. But this definitely solved the immediate need.
