### ISSUE TITLE
[GH Request] Onboard <ADD USERNAMES HERE>

### ISSUE THREAD

**Issue by connollymj13** [openedx/axim-engineering#942]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Khanan Grauer https://github.com/khanangrauer
Anton Yarmolenka: https://github.com/rnr
Kirill Izmaylov https://github.com/k1rill
Igor Koznin https://github.com/dixidroid
Eugene Yatsenko https://github.com/eyatsenkoperpetio
Vadim Kuznetsov https://github.com/forgotvas
Sergey Momot https://github.com/sergeymomot
Natalia Izmaylova https://github.com/nizmaylova

### Start Date

16 October 2023

### Urgency

High (< 3 days)

### Special Requests

Hi, we would like to request our team to be added to the edX/ 2U organization. Our team is contributing to the mobile project already in the works here:

https://github.com/openedx/openedx-app-ios/
https://github.com/openedx/openedx-app-android

Please reach out if you have any questions to [kgrauer@2u.com](mailto:kgrauer@2u.com).

Thank you

*This is Mike Connolly from the Help Desk. I am submitting this in reference to https://github.com/openedx/axim-engineering/issues/936 . Let me know if you have any questions for me. Thank you and I'll talk to you soon.*

**Comment by bmtcril** [comment]
Thanks @connollymj13 I think this is all set. Let me know if you run into any issues.

- @e0d confirmed this request with @georgebabey 
- I've created a new team `committers-openedx-mobile` for these two repos
- I've invited all of these users to the openedx Github org with the default 2U permissions and `committers-openedx-mobile`
- The users will need to accept the invitations before they expire!
- Users have been added to Salesforce as entity contributors

**Comment by connollymj13** [comment]
Thank you!!!

**Comment by khanangrauer** [comment]
Hello, 

Our team cannot push branches or submit PRs to projects 
https://github.com/openedx/openedx-app-ios/
https://github.com/openedx/openedx-app-android

Our team cannot create or assign issues in the Kanban board: https://github.com/orgs/openedx/projects/56/views/2 

We are blocked from moving forward. Please advise how we can help to accelerate this. Are we doing something wrong on our end?

Thank you

cc @georgebabey @marcotuts @e0d

**Comment by khanangrauer** [comment]
Update: accepted the invitation, thank you. 

However, when trying to push to a branch here for example: https://github.com/openedx/openedx-app-ios/

We get

`ERROR: Permission to openedx/openedx-app-ios.git denied to khanangrauer.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

Please advise

**Comment by e0d** [comment]
This is the standard process we are adopting.  Axim and other orgs use it
exclusively, from either organization or personal forks.

https://openedx.atlassian.net/wiki/spaces/AC/pages/3458170881/Working+with+Personal+Forks

Let me know if you have any questions.

**Comment by khanangrauer** [comment]
Thanks for sharing that info, Ed. We'll move forward with this approach.
