### ISSUE TITLE
[GH Request] Remove checks from branch protection rules in edx-notes-api

### ISSUE THREAD

**Issue by iamsobanjaved** [openedx/axim-engineering#943]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Requested Change

Kindly remove these checks from branch protection rules, in the edx-notes-api repo

- build (py38, django32, mysql57)
- build (py38, django32, mysql80)

### Reasoning

We want to merge Django upgrade PR, but these checks are stopping us. We can disable these for now, and enable Django 4.2 once we merge the upgrade PR

Django upgrade PR: https://github.com/openedx/edx-notes-api/pull/349

**Comment by bmtcril** [comment]
@iamsobanjaved these checks have been removed for now. I'm going to keep this open as a reminder to follow up, but please let me know when I can enable the new checks.

**Comment by bmtcril** [comment]
@iamsobanjaved it looks like the 4.2 PR has merged, can I enable branch protections for `build (py38, django42, mysql80)`?

**Comment by iamsobanjaved** [comment]
Its not yet deployed on production and also hit an issue on stage. I will let you know once it reaches prod successfully

**Comment by sarina** [comment]
@iamsobanjaved is this issue ready to move forward?

**Comment by feanil** [comment]
@iamsobanjaved checking back in on this, are we clear to add django 4.2 tests as required for the notes api app?

**Comment by iamsobanjaved** [comment]
Yeah, we can mark Django 4.2 tests as required now.
