### ISSUE TITLE
[GH Request] Grant access to hajorg

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#950]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

Add Jorg Are, hajorg, to the set of people who can submit pull requests to the https://github.com/openedx/frontend-component-ai-translations repo.

### Reasoning

Jorg is a 2U contractor who is actively working on this feature.  He was unable to submit a PR against this for active work.

**Comment by bmtcril** [comment]
All set, if this becomes blocking in the future folks can always send PRs from personal forks instead of direct PRs, which is the direction we're encouraging the community to go in overall.
