### ISSUE TITLE
[GH Request] Offboard dianekaplan, inventhouse, jpbeaudry

### ISSUE THREAD

**Issue by nedbat** [openedx/axim-engineering#954]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

These are names I noticed while working on other data gathering.  People who left over a year ago:

* Diane Kaplan, dianekaplan, left in Aug 2022
* Ben Holt, inventhouse, left in Aug 2022
* J.P. Beaudry, left in Nov 2021

### End Date

Aug 2022

### Urgency

Low (2 weeks)

**Comment by arbrandes** [comment]
The three were offboarded.  They weren't in the `openedx` GH org, but were still listed as being covered by the 2U CLA in Salesforce.

**Comment by nedbat** [comment]
This closed as not planned.  Does that means there was no change made?  They are listed in the .csv that the bot reads.
