### ISSUE TITLE
[GH Request] Offboard flaphq

### ISSUE THREAD

**Issue by nedbat** [openedx/axim-engineering#955]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Be careful: Adam Stankiewicz has two entries in Salesforce.  We need to *keep* the 2U entry, username adamstankiewicz.
He also has an entry for the GitHub username flaphq.  That entry should be removed.

cc @adamstankiewicz 

### End Date

never needed

### Urgency

Low (2 weeks)

**Comment by arbrandes** [comment]
Done!
