### ISSUE TITLE
[GH Request] Should the onboarding issue form have "squad" added?

### ISSUE THREAD

**Issue by nedbat** [openedx/axim-engineering#956]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

For onboarding of 2U people, we're going to want to know what squad they are on.  Can/should we add team/squad/something to the onboarding issue form to encourage providing that information? I know it won't apply for all firms, so it needs some squishy words around it.

### Reasoning

Guiding people to provide needed information reduces the possibility of missing it and having to ask for it.

**Comment by arbrandes** [comment]
@nedbat, wanna take a look?  https://github.com/openedx/axim-engineering/pull/963

**Comment by arbrandes** [comment]
Done!

![image](https://github.com/openedx/axim-engineering/assets/759355/92d26456-514e-43c5-b1ec-c89d5b513815)
