### ISSUE TITLE
[GH Request] Add an org-wide "jira:2u" label

### ISSUE THREAD

**Issue by nedbat** [openedx/axim-engineering#957]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Problem/Request

Now that the OSPR bot can make 2U Jira issues if a pull request is labelled with `jira:2u`, should we add that label to the list of org-wide labels? Use color #1475D4, thanks.

### Reasoning

It will make the labelling more consistent and remove a possible error (creating an incorrect label).  The downside is that most repos are not configured to successfully make Jira issues, but that's fine, we want to know where people are trying to make issues anyway.

**Comment by kdmccormick** [comment]
@nedbat Anyone can add a label by making a PR against [labels.yaml](https://github.com/openedx/repo-tools/blob/master/edx_repo_tools/repo_checks/labels.yaml), tagging `@openedx/axim-oncall` for review, and asking them to re-run repo_checks (@openedx/axim-oncall , just ping me if you're not sure what that means :)

**Comment by nedbat** [comment]
I went looking for how to do this before making this issue.  I found this page: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3695214629/openedx+org-wide+labels but it doesn't seem to mention this flow.

**Comment by kdmccormick** [comment]
@openedx/axim-oncall could you take a look at Ned's PR?

**Comment by arbrandes** [comment]
Merged the PR, and ran repo_checks!
