### ISSUE TITLE
[GH Request] Offboard mrazadar

### ISSUE THREAD

**Issue by AmiraQuick** [openedx/axim-engineering#959]
### Firm Name

2U

### User List  (case sensitive!) - Please also include in ticket title

Muhammad Raza Dar, mrazadar

### End Date

10/31/2023

### Urgency

Low (2 weeks)

**Comment by arbrandes** [comment]
Done.

**Comment by sarina** [comment]
@arbrandes just a note, please remove users from the GitHub org when they are offboarded.
