### ISSUE TITLE
[GH Request] make main branch the default in frontend-components-tinymce-advanced-plugins

### ISSUE THREAD

**Issue by kenclary** [openedx/axim-engineering#960]
### Repository

axim-engineering

### Urgency

Medium (< 2 weeks)

### Requested Change

The (newly created) `main` branch of `openedx/frontend-components-tinymce-advanced-plugins` should become the default branch. I don't have permissions to make that change (apparently).

### Reasoning

The default branch should be `main` not `KristinAoki/add-starter-files`. This was requested by @feanil.

**Comment by arbrandes** [comment]
Done!  Also modified branch protection to apply to `main`.
