### ISSUE TITLE
Github Group for openedx

### ISSUE THREAD

**Issue by Ali-D-Akbar** [openedx/axim-engineering#961]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

Hi there,

We want to have a Github team "Phoenix" created for review and
collaboration purposes. Can we create one for our team? Also, feel free to
add the following github usernames in it:

ali-d-akbar
uzairr
DawoudSheraz
AfaqShuaib09
zawan-ila

Regards,
Ali Akbar
2u - Phoenix

### Reasoning

To use this team in PR reviewers in automated requirement update PRs.

**Comment by arbrandes** [comment]
Done!  https://github.com/orgs/openedx/teams/2u-phoenix
