### ISSUE TITLE
Discovery: Renovate config options and consistency

### ISSUE THREAD

**Issue by feanil** [openedx/axim-engineering#966]
What are the different options for renovate config?  Can we standardize?

We use Renovate to manage JS upgrade in various repositories.  It should be standard across all JS repos but we don't know that it is.

### Questions to answer

- How many repos have a package.json file?
- How many repos have renovate config?
- How many different variations on renovate config is there?
- Can you recommend any changes to the [default renovate config](https://github.com/openedx/frontend-template-application/blob/master/renovate.json)?

### Expected Output
* Comments on this ticket that answer the above questions and any other things you learn along the way.
* Recommendation on whether or not it makes sense to standardise the renovate config.
* Discussion based on learnings.
  * This might result in the creation of tickets to go through the standardization.

**Comment by salman2013** [comment]
How many repos have a package.json file?

I found three repositories having package.json file 

1. [openedx/frontend-platform](https://github.com/openedx/frontend-platform)

> https://github.com/openedx/frontend-platform/blob/master/package.json


2. [openedx/frontend-enterprise](https://github.com/openedx/frontend-enterprise) 

> https://github.com/openedx/frontend-enterprise/blob/master/package.json
> https://github.com/openedx/frontend-enterprise/blob/master/packages/hotjar/package.json
> https://github.com/openedx/frontend-enterprise/blob/master/packages/logistration/package.json
> https://github.com/openedx/frontend-enterprise/blob/master/packages/catalog-search/package.json

3. [openedx/openedx-backstage](https://github.com/openedx/openedx-backstage)

> https://github.com/openedx/openedx-backstage/blob/main/package.json
> https://github.com/openedx/openedx-backstage/blob/main/packages/backend/package.json
>  

How many repos have renovate config?

A total of 23 repositories have a renovate.json file

1.  https://github.com/openedx/frontend-app-publisher
2.  https://github.com/openedx/frontend-app-admin-portal
3.  https://github.com/openedx/frontend-app-profile
4.  https://github.com/openedx/frontend-app-ecommerce
5.  https://github.com/openedx/frontend-app-account
6.  https://github.com/openedx/frontend-app-payment
7.  https://github.com/openedx/frontend-app-learning
8.  https://github.com/edx/prospectus
9.  https://github.com/openedx/frontend-app-learner-portal-enterprise
10.  https://github.com/openedx/frontend-app-course-authoring
11.  https://github.com/openedx/frontend-app-library-authoring
12.  https://github.com/edx/frontend-app-learner-record
13.  https://github.com/openedx/frontend-app-enterprise-public-catalog
14.  https://github.com/edx/frontend-app-communications
15.  https://github.com/openedx/paragon
16.  https://github.com/openedx/frontend-platform
17.  https://github.com/openedx/frontend-build
18.  https://github.com/openedx/frontend-component-header
19.  https://github.com/edx/frontend-component-header-edx
20.  https://github.com/openedx/frontend-component-cookie-policy-banner
21.  https://github.com/edx/frontend-component-footer-edx
22.  https://github.com/openedx/frontend-component-footer
23.  https://github.com/openedx/frontend-template-application

I found a [ticket](https://github.com/openedx/wg-frontend/issues/116) to create a common renovate config that automates @edx namespaced minor/patch version upgrades, which means there is already progress to make the renovate config standardized for all repos. 


There is also a [sheet](https://docs.google.com/spreadsheets/d/1hR7UNPu8ZQenKiZQhZXSajsAZVbiJntATXM_YB6_AlE/edit#gid=0) having information about all repos which are updated the renovate for @opendx packages

**Comment by feanil** [comment]
> I found three repositories having package.json file

This doesn't seem right, there should be one in each MFE at least along with many of the libraries and older backends.

**Comment by salman2013** [comment]
@feanil I have updated the correct count and repo names which have package.json file in them.

**Comment by feanil** [comment]
@salman2013 do all of those repos have a renovate config?

**Comment by salman2013** [comment]
@feanil I updated the list of all repos which has both package.json and renovate.json files.

**Comment by feanil** [comment]
@salman2013 let's make a ticket to ensure that the rest of the repos have a renovate.json config

**Comment by sarina** [comment]
Can this ticket be closed?
