### ISSUE TITLE
[GH Request] Give Team Aperture (2U) engineers write-access to openedx/frontend-plugin-framework

### ISSUE THREAD

**Issue by jsnwesson** [openedx/axim-engineering#967]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

I would like to request that @openedx/2u-aperture team members have write access into the [openedx/frontend-plugin-framework](https://www.github.com/openedx/frontend-plugin-framework). The team members are:
- @hurtstotouchfire 
- @deborahgu 
- @justinhynes 
- @cdeery 
- @MaxFrank13 
- and myself (@jsnwesson)

### Reasoning

So that we can extract the Frontend Plugin Framework from a PR that lives in [openedx/frontend-platform](https://www.github.com/openedx/frontend-platform).

**Comment by arbrandes** [comment]
Done!

**Comment by jsnwesson** [comment]
Thanks Adolfo!
