### ISSUE TITLE
[GH Request] Onboard hassan6190

### ISSUE THREAD

**Issue by miankhalid** [openedx/axim-engineering#974]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Hassan Nisar, @hassan6190

### User Squad

Axinite

### Start Date

16 October 2023

### Urgency

High (< 3 days)

### Special Requests

Hi, we would like to Hassan to be added to the edX/2U organization. Our team is contributing to the mobile project already in the works here:

1. [Open edX Mobile Roadmap](https://github.com/orgs/openedx/projects/56/views/1)
2. [openedx/openedx-app-ios](https://github.com/openedx/openedx-app-ios/)
3. [openedx/openedx-app-android](https://github.com/openedx/openedx-app-android)

Feel free to reach out to me @ [mkhalid@2u.com](mailto:mkhalid@2u.com)

_p.s. I forgot to add Hassan to the previous request I made: https://github.com/openedx/axim-engineering/issues/938_

**Comment by ormsbee** [comment]
@miankhalid: @e0d sent an invitation to @hassan6190 on Nov 14. Please have them accept the invitation.
