### ISSUE TITLE
'make upgrade' failing because of a platform dirs update

### ISSUE THREAD

**Issue by farhan** [openedx/axim-engineering#975]
Make upgrade github actions are failing in the following repositories because of a platform dirs update
We need to fix them in this ticket

[Slack thread](https://openedx.slack.com/archives/C05P7KQURL0/p1699891921435439)

**Repositories:**

https://github.com/openedx/xapi-db-load/actions/runs/6843954855/job/18607147186#step:5:691
https://github.com/openedx/DoneXBlock/actions/runs/6843994233/job/18607244947#step:5:776
https://github.com/openedx/FeedbackXBlock/actions/runs/6843968213/job/18607181035#step:5:942
https://github.com/openedx/openedx-learning/actions/runs/6844043767/job/18607366099#step:5:1393
https://github.com/openedx/openedx-event-sink-clickhouse/actions/runs/6843960731/job/18607162381#step:5:1185

**Comment by bmtcril** [comment]
Also happening here, is this repo not on our list? https://github.com/openedx/event-bus-redis/actions/runs/6844840517

**Comment by farhan** [comment]
@bmtcril As per the following sources, it's not on our list
https://github.com/openedx/event-bus-redis/blob/main/.github/workflows/upgrade-python-requirements.yml#L20
https://backstage.openedx.org/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all

**Comment by farhan** [comment]
The Issue has been fixed by restricting the version of the relevant package in [PR](https://github.com/openedx/edx-lint/pull/379)

Test cases are passing successfully in the following repos now(re-run the jobs):
https://github.com/openedx/DoneXBlock/actions/runs/6843994233
https://github.com/openedx/xapi-db-load/actions/runs/6843954855
https://github.com/openedx/FeedbackXBlock/actions/runs/6843968213
https://github.com/openedx/openedx-event-sink-clickhouse/actions/runs/6843960731

still failing on: 
https://github.com/openedx/openedx-learning/actions/runs/6844043767

**Comment by feanil** [comment]
I think the problem is that the `common_constraints` file is commented out: https://github.com/openedx/openedx-learning/blob/main/requirements/constraints.txt#L12

It should be uncommented and that should resolve the issue.  I didn't see any reason for it in the comments or in the commit history.

**Comment by ormsbee** [comment]
I think that was probably me when I was messing around with testing on multiple Django versions. By all means, please feel free to uncomment it to unblock. If that breaks anything in openedx-learning, please ping me. Thank you.

**Comment by farhan** [comment]
Its working fine now

**Comment by feanil** [comment]
I think this can be closed!  Thanks Farhan!
