### ISSUE TITLE
[GH Request] enterprise-quokkas permissions to enterprise-access

### ISSUE THREAD

**Issue by bcitro** [openedx/axim-engineering#976]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

Hello,

Please give the [enterprise-quokkas github team ](https://github.com/orgs/openedx/teams/enterprise-quokkas/members) write access to the [enterprise-access github repo](https://github.com/openedx/enterprise-access).

### Reasoning

Our team (quokkas) will be working extensively in this repo and we need permission to merge PRs.  Thanks!

**Comment by ormsbee** [comment]
Team @openedx/enterprise-quokkas now has write access to [enterprise-access](https://github.com/openedx/enterprise-access)
