### ISSUE TITLE
[GH Request] Re-activate renovate bot for frontend-app-library-authoring

### ISSUE THREAD

**Issue by jesperhodge** [openedx/axim-engineering#977]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

Please add the renovate bot again to frontend-app-library-authoring

### Reasoning

We had an incident a few weeks ago with some dependency updates that broke the pipeline. Adolfo removed the renovate bot from the repo for us on short notice because it kept auto-merging new dependencies and this was making the problem worse.

In the meantime the incident has been not only resolved, but I changed the renovate config file so that auto-merges are disabled from that side. So we can add the renovate bot without issue and I don't foresee any repeat of that situation.

**Comment by ormsbee** [comment]
@jesperhodge: Re-installed Renovate for frontend-app-library-authoring. If it gives you any trouble, please let me know. Thank you.
