### ISSUE TITLE
Requesting CC onboarding for Ayaz Quraishi

### ISSUE THREAD

**Issue by ayazquraishi** [openedx/axim-engineering#979]
### Firm Name

Edly

### Urgency

Low (2 weeks)

### Problem/Request

Requesting CC onboarding for Ayaz Quraishi

### Reasoning

Reason: https://discuss.openedx.org/t/core-contributor-nomination-ayaz-quraishi-edly-by-arbisoft/11570/3

**Comment by ormsbee** [comment]
### Non-Coding CC Onboarding Checklist for Axim On-Call

- [ ] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [ ] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Set up access for CC in privacy & a11y courses (can skip for now, but let CC know that they may be upcoming)
- [ ] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while).  Keep the ticket open with status “Blocked”, until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [ ] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [ ] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [ ] Look up their record in Salesforce and grant them the Core Contributor role.
- [ ] Send Dean a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)
- [ ] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin/users/list/active) to the person’s forums profile. (forum moderation rights are listed on the [Core Contributors page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833)).

**Comment by ormsbee** [comment]
@ayazquraishi: I sent you an invite to the CC Onboarding course. When you have completed the course, please add a comment in this ticket. If you have not received the invite, please let me know. Thank you!

**Comment by sarina** [comment]
@ayazquraishi - could you confirm whether you got the invite to the CC Onboarding Course? Thank you!

**Comment by bmtcril** [comment]
I got in touch with Ayaz over email and he is working on the steps now.

**Comment by arbrandes** [comment]
@bmtcril, would you like me to take this one over?

**Comment by bmtcril** [comment]
That's ok, I'll keep it and continue to poke him in email since we have a thread

**Comment by sarina** [comment]
@bmtcril or @ayazquraishi any updates?

**Comment by bmtcril** [comment]
I did not get a response to my last email

**Comment by sarina** [comment]
I pinged @ayazquraishi on the nomination post. If we don't hear any word after a few weeks, I will close the ticket (and one can always be opened again in the future).

**Comment by feanil** [comment]
Closing since we haven't heard from him in 3 weeks.

**Comment by feanil** [comment]
@sarina if we can't verify that they've completed the required training, do we need to roll back any access or notify any working groups?

**Comment by sarina** [comment]
Yes, I think I would notify the person or group who nominated them that they are not a Core Contributor, as they have not signed any agreements, and any special access should not be granted until those Agreements are signed.
