### ISSUE TITLE
[GH Request] Add all Supernova team members to https://github.com/openedx/frontend-component-ai-translations

### ISSUE THREAD

**Issue by jristau1984** [openedx/axim-engineering#982]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

Please grant appropriate access to the following github users for this repo:
BrandonHBodine
Guilleves
Rodra
jristau1984
theinkedkraken

Thanks!

### Reasoning

Only one team member can approve PRs, causing a bottleneck in productivity.

**Comment by ormsbee** [comment]
Created the [2u-supernova](https://github.com/orgs/openedx/teams/2u-supernova/members) team with the above requested members and @hajorg (who already had access). 2u-supernova is now set up for write access to [frontend-component-ai-translations](https://github.com/openedx/frontend-component-ai-translations).
