### ISSUE TITLE
Requesting CC onboarding for Cecilia Liu

### ISSUE THREAD

**Issue by jyliugithub** [openedx/axim-engineering#985]
### Firm Name

Notion Wave Inc./edSPIRIT

### Urgency

Low (2 weeks)

### Problem/Request

Requesting CC onboarding for Cecilia Liu

### Reasoning

https://discuss.openedx.org/t/core-contributor-nomination-cecilia-liu-notionwave/11636

### Non-Coding CC Onboarding Checklist for Axim On-Call
- [x] Invite them to the [Core Contributor Onboarding course](https://training.openedx.org/courses/course-v1:Axim+New-CoreContributor+2023/course/) (link requires login) and let them know they need to complete the steps before they’re fully considered a core contributor (if you don’t know their email address, comment on the GH ticket and consider it blocked until you get that info).
- [x] Confirm with them that they received the course invitation and have successfully accessed the training course.
- [x] Set up access for CC in privacy & a11y courses (can skip for now, but let CC know that they may be upcoming)
- [x] Verify with Sarina or Axim Legal that the new Core Contributor successfully completed the required legal documents, including both the CLA and the CC Agreement. (Usually Legal will contact the CC Admins about this so you can check in with them if it’s been a little while).  Keep the ticket open with status “Blocked”, until this is done. Once complete, follow the remaining steps (some may be handled by the CC onboarding course now).
- [x] Invite the CC to the Open edX `#core-contributors` Slack channel.
- [x] Add them to the [Core Contributors list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833).
- [x] Look up their record in Salesforce and grant them the Core Contributor role.
- [x] Send Dean a direct message on Slack with the full name and email address of the new CC. (Dean will send the new CC an email explaining the bi-weekly check-ins at [Listaflow.com](https://www.listaflow.com/), the [report spreadsheet](https://docs.google.com/spreadsheets/d/1E4EGEBZLw1VSzVUZThnDn187cmHOKAdsgfnvncGDwF0/edit), and provide the CC with a link to the latest sprint retro recap thread [in the forums](https://discuss.openedx.org/c/working-groups/core-contributors/36). Dean will contact Fox Piacenti to add the new CC to the correct Listaflow list, and ensure the CC has successfully created an account.)
- [x] Ask a Forum Moderator to [award the “Core Contributor” badge](https://discuss.openedx.org/admin

**Comment by sarina** [comment]
@jyliugithub could you please check your spam folder before I try resending? We've been having a bit of trouble with our invites being caught as spam.

**Comment by jyliugithub** [comment]
> @jyliugithub Can you confirm that you have received the invite to the course?

Thanks @e0d  I have not seen the invite.

**Comment by jyliugithub** [comment]
> @jyliugithub could you please check your spam folder before I try resending? We've been having a bit of trouble with our invites being caught as spam.
Thanks @sarina Just checked the spam , nothing there yet. I tried to register at open edX training course site, it said I need to enroll to the core contributor course to access.  my email is : Cecilia.liu@notionwave.com Will you grant me the access?

**Comment by jyliugithub** [comment]
> > @jyliugithub could you please check your spam folder before I try resending? We've been having a bit of trouble with our invites being caught as spam.
> > Thanks @sarina Just checked the spam , nothing there yet. I tried to register at open edX training course site, it said I need to enroll to the core contributor course to access.  my email is : [Cecilia.liu@notionwave.com](mailto:Cecilia.liu@notionwave.com) Will you grant me the access?

@sarina  Thanks. I found the course on training.opened.org and enrolled , will try to finish this week. Anything else I need to do to complete the onboarding process?

**Comment by sarina** [comment]
@jyliugithub the course is all you need to complete - there will be some steps in there you need to follow. Glad you found the invite!

**Comment by jyliugithub** [comment]
> @jyliugithub the course is all you need to complete - there will be some steps in there you need to follow. Glad you found the invite!

@sarina  Sorry for circling back. I have not received the invite. It was very strange that I had found the course on the training site and enrolled by myself, saw a bit of your video even, not sure if it was preview though the other day from my phone( without clicking on any activation link), however, when I tried to access it today from my computer, it says I need that invitation link and activate it. I checked spam again, nothing still. I also tried to test by resetting my password for this site, never received the email. Would  you mind to send the invitation to my personal email to see if it works ( I just created a new account at the training site) with: cecilialiu1014@hotmail.com

**Comment by sarina** [comment]
@jyliugithub I'm sorry this is being difficult. I've sent it to your personal email address:

<img width="613" alt="image" src="https://github.com/openedx/axim-engineering/assets/1985317/6d405c8b-bef4-41fc-a627-a6488928097e">

I hope this works 🤞🏻

**Comment by jyliugithub** [comment]
> @jyliugithub I'm sorry this is being difficult. I've sent it to your personal email address:
> 
> <img alt="image" width="613" src="https://private-user-images.githubusercontent.com/1985317/292294721-6d405c8b-bef4-41fc-a627-a6488928097e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxODk5ODAsIm5iZiI6MTcwMzE4OTY4MCwicGF0aCI6Ii8xOTg1MzE3LzI5MjI5NDcyMS02ZDQwNWM4Yi1iZWY0LTQxZmMtYTYyNy1hNjQ4ODkyODA5N2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMjAxNDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGFlYjBjMWM4NjI4MDM4YWMzZDA1MzhiODc4NDNiYWVhNjM1ODcxY2FhY2Q4Y2JlZTI0YjNhYjJmMmE2Zjk0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Di_fQ_xwt4Cby0IhlpCbnmDx9dUEue3LACPVWkkRyag">
> I hope this works 🤞🏻

Yes!It finally worked. I guess it is my working email. Thanks a lot! @sarina

**Comment by sarina** [comment]
Hi @jyliugithub - I've finished the steps to welcome you to the CC program!

I added you to this wiki list, but I wasn't sure what your company is or what projects you're working on, so you may wish to fill that out here: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Core+Contributors+to+the+Open+edX+Project
