### ISSUE TITLE
[GH Request] Onboard shafqat-muneer

### ISSUE THREAD

**Issue by AmiraQuick** [openedx/axim-engineering#986]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Muhammad Shafqat Muneer Qadri, shafqat-muneer

### Start Date

04 December 2023

### Urgency

Low (2 weeks)

**Comment by georgebabey** [comment]
Approved

**Comment by e0d** [comment]
Updated, will be in the batch this afternoon.
