### ISSUE TITLE
[GH Request] Onboard <zwidekalanga; jono-booth>

### ISSUE THREAD

**Issue by hmccauley** [openedx/axim-engineering#988]
### Firm Name

2U

### User List (case sensitive!) - Please also include in ticket title

Cyril Nxumalo - zwidekalanga - cnxumalo@2u.com
Jono Booth - jono-booth - jbooth@2u.com

### Start Date

12/1/2023

### Urgency

High (< 3 days)

**Comment by georgebabey** [comment]
Approved

**Comment by e0d** [comment]
Added to SF and GH.  Will be in the batch this afternoon.
