### ISSUE TITLE
[GH Request] <Create a new repo for test automation of new openedx Mobile Apps>

### ISSUE THREAD

**Issue by bilalawan321** [openedx/axim-engineering#994]
### Firm Name

2U

### Urgency

Medium (< 2 weeks)

### Problem/Request

Previously, we had a repository named "[edx-app-test](https://github.com/openedx/edx-app-test)" that contained all the automation test cases for "[edx-app-android](https://github.com/openedx/edx-app-android)" and "[edx-app-ios](https://github.com/openedx/edx-app-ios)" repositories.
With the introduction of new code bases, specifically "[openedx-app-android](https://github.com/openedx/openedx-app-android)" and "[openedx-app-ios,](https://github.com/openedx/openedx-app-ios)" we aim to establish a new repository dedicated to writing automation test cases for these new applications.
The initial structure of the new repo will be the same as [edx-app-test](https://github.com/openedx/edx-app-test) and the name of the new repo will be `openedx-app-test`.

### Reasoning

@bilalawan321 and @miankhalid are the maintainers of this new repo.

**Comment by e0d** [comment]
I've create the repo, please review and let me know if you encounter any issues.

https://github.com/openedx/openedx-app-test

**Comment by feanil** [comment]
Looks like this work is done so closing this issue.
