### ISSUE TITLE
[GH Request] Mobile Roadmap access issues for 2U's Mobile team (Axinite)

### ISSUE THREAD

**Issue by miankhalid** [openedx/axim-engineering#995]
### Firm Name

2U

### Urgency

High (< 3 days)

### Requested Change

In the [Open edX Mobile Roadmap](https://github.com/orgs/openedx/projects/56/views/1) following are not accessible to the Axinite team (@openedx/2u-mobile-axinite):

1. “Add task list” and “Add tasks” buttons on the Issue view
2. Gear icon on the Development section on PRs to link a PR with an issue
3. Merge rights on PR upon approval, currently, only [Volodymyr](https://github.com/volodymyr-chekyrta) has it
4. We aren’t able to edit the description of tasks/issues created by someone else

### Reasoning

Make the collaboration between the Mobile teams smooth i.e.
1. product folks can add/update tickets/issues/tasks
2. dev folks can link PRs with issues/tasks

**Comment by e0d** [comment]
I've opened a support request with GH as I'm not seeing any documentation that clarifies what change we need to make.

https://support.github.com/ticket/enterprise/10202/2477978

**Comment by feanil** [comment]
@e0d did you get any updates from github support on this?

**Comment by e0d** [comment]
Yes, but not actionable without further information from the mobile team.  GH believes that triage should be sufficient for adding task lists and tasks.  There appear to be multiple ways of doing this.  We'd need to know what specifically @miankhalid and team were trying to do, screen cast or screen shots.

For the moment, they have write to unblock.  It should be possible to do what they need with triage.

**Comment by feanil** [comment]
It looks like part of the expectation from this ticket is that the 2U mobile team would be able merge PRs in the future(item 2), is that just a mis-match in expectations or should they indeed have write access?

**Comment by e0d** [comment]
That's TBD, all PRs should be reviewed by Volodymyr before they merge,
though I realized this can be a requirement AND they can have the ability
to merge their own PRs.

**Comment by miankhalid** [comment]
Feel free to close this issue as we've gotten the access we needed, thanks!
