### ISSUE TITLE
[GH Request] <https://edx.readthedocs.io/projects/edx-insights/en/latest/front_matter/preface.html#id16 access>

### ISSUE THREAD

**Issue by connollymj13** [openedx/axim-engineering#998]
### Firm Name

2U

### Urgency

Low (2 weeks)

### Requested Change

Hi! 

Reaching out to get Brian McCandless, bmccandless@2u.com edit access to https://edx.readthedocs.io/projects/edx-insights/en/latest/front_matter/preface.html#id16, which I believe is under https://github.com/openedx/edx-analytics-dashboard/tree/ed4862f49209a3263e2f9176be085a49f674f11b/docs/en_us/dashboard/source. Thank you and let me know if there is any other information you need.

### Reasoning

User needs to update the ReadtheDocs mentioned above.

**Comment by jsoto2u** [comment]
Michael is no longer at 2U, but to provide an update for this ticket since information is missing Brians Github username is  brianmccandless.  This request is related to his recent question in the shared Slack channel regarding getting access to this repo to update the Read the Docs site.

**Comment by sarina** [comment]
@jsoto2u  @connollymj13 @brianmccandless - we don't give edit access to repositories except for Core Contributors or people under special agreement with 2U. I recommend you follow the community workflow of cloning the repo and submitting pull requests. Thanks for understanding!
