### ISSUE TITLE
[GH Request] Update Read the Docs for Quince

### ISSUE THREAD

**Issue by cmltaWt0** [openedx/axim-engineering#999]
### Firm Name

BTR WG

### Urgency

High (< 3 days)

### Problem/Request

We just cut the open-release/quince.1 tag and need someone from Axim to perform [Step 4a from the "Process to create an Open edX Release" page](https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release#4a.-Ask-Axim-to-un-hide-the-release-versions-of-each-book) (pointing Read the Docs to the new version).

### Reasoning

Following documented steps at the https://openedx.atlassian.net/wiki/spaces/COMM/pages/19662426/Process+to+Create+an+Open+edX+Release after cutting a new release tag.

**Comment by feanil** [comment]
@cmltaWt0 this should be all set, the new versions are active and building successfully.
